### ISSUE TITLE
build: non standard library location or prefix

### ISSUE THREAD

**Issue by galou** [catkin/catkin_tools#128]
I cannot build with "catkin build" what I can build with "catkin_make". The problem occurs probably because of a non-standard library prefix or destination. I built a Python wrapper, so I didn't want to use `import libmy_package` but only `import my_package`.
Extract of the CMakeLists.txt of the `crossing_detector` package:

```
set_target_properties(crossing_detector_wrapper_cpp PROPERTIES
  PREFIX ""
  LIBRARY_OUTPUT_DIRECTORY ${CATKIN_DEVEL_PREFIX}/${CATKIN_PACKAGE_PYTHON_DESTINATION})
```

The reported issue:

```
CMake Error at /home/gael/ros_indigo_ws/devel/share/crossing_detector/cmake/crossing_detectorConfig.cmake:141 (message):
  Project 'dataset_analyzer' tried to find library
  'crossing_detector_wrapper_cpp'.  The library is neither a target nor
  built/installed properly.  Did you compile project 'crossing_detector'? Did
  you find_package() it before the subdirectory containing its code is
  included?
```

`crossing_detector` is included in `find_package()` in `dataset_analyzer/CMakeLists.txt`. And the error also appears if I compile `crossing_detector` beforehand.

Regards,
Gaël

**Comment by galou** [comment]
The question was asked here: http://answers.ros.org/question/201036/how-can-catkin-find-ros-libraries-in-non-standard-locations/

**Comment by adolfo-rt** [comment]
For the record, I posted another answer to the [question](http://answers.ros.org/question/201036/how-can-catkin-find-ros-libraries-in-non-standard-locations/?answer=209923#post-id-209923) where a solution that is compatible with both multi-CMake project (`catkin build`,  `catkin_make_isolated`) and single, nested CMake projects (`catkin_make`) is proposed.
