### ISSUE TITLE
catkin build --ignore-package

### ISSUE THREAD

**Issue by davetcoleman** [catkin/catkin_tools#130]
Is there a way with flags (or could we add a feature) to allow an entire workspace to be rebuilt *except* ignore certain packages? 

Use case: I keep OMPL in my workspace, but rarely need to rebuild it (it has not dependencies in my workspace), but unfortuantly their automatic CMake scripts are very slow to run even when there has been no modifications to that package. I do, however, occationally make edits to it and so want it in the same workspace.

**Comment by wjwwood** [comment]
So, if you put a `CATKIN_IGNORE` file in the `ompl` directory then `catkin build` will act like it is not there. This may not be what you want, instead what you want is to explicitly not build `ompl`, but you want it to be seen in the packages list and you want packages which depend on it to try and use it's installation space as part of it's environment. In that case I guess we would walk something like `--skip-packages pkg1 [pkg2 [pkgn]]` (or `--skip-building-packages` would be more exact) where the listed packages would be skipping similar to how packages are skipped when using the `--start-with` option.

I think that makes sense to have, but I don't have spare cycles this week. I'd be happy to help you get something like this merged though.

**Comment by davetcoleman** [comment]
> what you want is to explicitly not build ompl, but you want it to be seen in the packages list and you want packages which depend on it to try and use it's installation space as part of it's environment

Yes.

I haven't really dug into catkin_tools and don't know how it works, so I have to pass on making the change myself I'm afraid. I'm just here for testing, feedback, and documentation :-)

**Comment by jbohren** [comment]
@davetcoleman Check out #152 for whitelist / blacklist behavior

**Comment by jbohren** [comment]
I'm closing this now that the blacklist behavior has been merged with #152.

@davetcoleman feel free to reopen this if you want to keep talking about it.

**Comment by prithvimellacheruvu** [comment]
`catkin config` has an option `--skiplist PKG [PKG ...]
                        Set the packages on the skiplist. Packages on the skiplist are not built
                        with a bare call to "catkin build".
`
You can use this to skip building a package.
