### ISSUE TITLE
catkin list --depends-on ignores packages with run-only dependancies

### ISSUE THREAD

**Issue by IanTheEngineer** [catkin/catkin_tools#132]
The summary says it all. I noticed this mostly because the [baxter_sdk package](https://github.com/RethinkRobotics/baxter/blob/master/baxter_sdk/package.xml) was not being listed as a package that depends on any of the other baxter packages.

To verify, create a new workspace by merging [this rosinstall file](https://raw.githubusercontent.com/RethinkRobotics/baxter/master/baxter_sdk.rosinstall), and then run  `catkin list --depends-on baxter_interface`. You won't see baxter_sdk on that list!

**Comment by wjwwood** [comment]
Doh:

https://github.com/catkin/catkin_tools/blob/master/catkin_tools/verbs/catkin_list/cli.py#L50-54
