### ISSUE TITLE
config: cannot clear catkin make arguments with CLI

### ISSUE THREAD

**Issue by wjwwood** [catkin/catkin_tools#136]
I noticed this when I accidentally put a CMake argument into the extra catkin make arguments list. To reproduce:

1. Create a catkin workspace
1. Run `catkin config --catkin-make-args -DMISPLACED_CMAKE_ARG=foo`
1. Run `catkin config --no-catkin-make-args`
1. Observe that the "Additional catkin Make Args:" still contains the misplaced argument

My expectation would be that `--no-catkin-make-args` should clear the list of additional catkin make arguments. I looked through `-h` and I didn't see another way to clear this from the workspace configuration.

@jbohren is this expected behavior or a bug?

**Comment by wjwwood** [comment]
Another something strange, there is a `config.yaml` and a `build.yaml`. The `build.yaml` seems to be affected by the config command, but the `config.yaml` does not change and seems to dictate what is used. That seems strange, but it's hard to tell if that is intended without digging into the code.

**Comment by jbohren** [comment]
I think the args reset is a bug, focusing on this line: https://github.com/catkin/catkin_tools/blob/master/catkin_tools/context.py#L223

**Comment by jbohren** [comment]
I'll double-check the yaml files, but I believe config.yaml is the persistent config and build.yaml is the last build command (which might have temporarily overridden the config)

**Comment by wjwwood** [comment]
@jbohren Ok, thanks for looking into it. Let me know if I can help debugging it.

**Comment by jbohren** [comment]
This is fixed in https://github.com/catkin/catkin_tools/pull/147/files#diff-732cee0e8cd5f74e451d615599b79589R141
