### ISSUE TITLE
rostest outputting results to wrong workspace

### ISSUE THREAD

**Issue by davetcoleman** [catkin/catkin_tools#137]
When one has multiple workspaces overlayed on top each other, rostest seems to output its test results to the top (last sourced) workspace and this causes lots of errors:

Wrong location:
```
[ROSUNIT] Outputting test results to /home/dave/ros/ws_vision/build/homeworks/test_results/moveit_humanoid/rostest-launch_hrp2_tests.xml
```

Remaining output:
```
FAILURE: test [humanoid_tests] did not generate test results
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/dave/ros/ws_base/src/ros_comm/tools/rostest/src/rostest/runner.py", line 160, in fn
    self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[ROSTEST]-----------------------------------------------------------------------

[testhumanoid_tests][failed]

SUMMARY
 * RESULT: FAIL
 * TESTS: 0
 * ERRORS: 0
 * FAILURES: 1

ERROR: The following tests failed to run:
 * testhumanoid_tests

Cannot find results, writing failure results to '/home/dave/ros/ws_moveit/build/moveit_humanoid/test_results/moveit_humanoid/MISSING-rostest-launch_hrp2_tests.xml'
```

**Comment by wjwwood** [comment]
> Wrong location:

> `[ROSUNIT] Outputting test results to /home/dave/ros/ws_vision/build/homeworks/test_results/moveit_humanoid/rostest-launch_hrp2_tests.xml`

Why do you think this is the wrong location?

I find it helpful to read my issue as if I were someone else before posting. Not having your context I find myself with a lot of missing parts to the problem:

- What workspaces exist here?
- How were the workspaces built (what was sourced when they were built)?
- How was the current environment created?
- What was the desired behavior?
- How can I reproduce it?

I need more information to help you.

**Comment by davetcoleman** [comment]
@wjwwood I apologize for creating an issue in haste without proper details. It was mostly because I do not fully understand how ROSTESTS are suppose to work. I do believe that, while in a workspace in the middle of the stack of workspaces, ROSTEST still saves its log to the top most workspace (the last one sourced). However, after using ROSTEST longer the log issue did not seem to affect usability, so it wasn't that big of a deal. I'm going to close this for now.

**Comment by wjwwood** [comment]
Ok, well that's fine I guess.

One note is that when operating on a workspace in the middle of a stack of workspaces I think you should only source the workspace that workspace depends on.

Consider workspace A, B and C, where B was built with A sourced and C was built with B sourced.

If you source C and then run the tests on workspace B, I would consider that potentially have undefined behavior. In practice I think it should work, but it might cause the issue you are describing. I would recommend that for best results you should source workspace A in a fresh terminal and run the tests on workspace B there.

----

On a side note, none of the questions I posed above require an understanding of how `rostest` works. Even if some of the information you include isn't relevant, providing things you might think have some impact on the problem in the first post would get us started faster.
