### ISSUE TITLE
Unformated output to build within different tools (emacs)

### ISSUE THREAD

**Issue by adeguet1** [catkin/catkin_tools#145]
When building under emacs without any specific settings, the output of catkin build is close to unreadable.   Anyway to have little or no formatting nor colors when building?
```
-*- mode: compilation; default-directory: "/home/adeguet1/catkin_ws/" -*-
Compilation started at Tue Feb 24 15:25:58

cd ~/catkin_ws/; catkin build -i --no-status -v
[35m[0m[0m
[36mProfile:[0m                     [33mdefault[0m[0m
[36mExtending:[0m          [31m[cached][0m[0m [33m/opt/ros/hydro[0m[0m
[36mWorkspace:[0m                   [33m/home/adeguet1/catkin_ws[0m[0m
[36mSource Space:[0m       [31m[exists][0m[0m [33m/home/adeguet1/catkin_ws/src[0m[0m
[36mBuild Space:[0m        [31m[exists][0m[0m [33m/home/adeguet1/catkin_ws/build[0m[0m
[36mDevel Space:[0m        [31m[exists][0m[0m [33m/home/adeguet1/catkin_ws/devel[0m[0m
[36mInstall Space:[0m     [31m[missing][0m[0m [33m/home/adeguet1/catkin_ws/install[0m[0m
[36mDESTDIR:[0m                     [33mNone[0m[0m
[35m[0m[0m
[36mIsolate Develspaces:[0m         [33mFalse[0m[0m
[36mInstall Packages:[0m            [33mFalse[0m[0m
[36mIsolate Installs:[0m            [33mFalse[0m[0m
[35m[0m[0m
[36mAdditional CMake Args:[0m       [33mNone[0m[0m
[36mAdditional Make Args:[0m        [33mNone[0m[0m
[36mAdditional catkin Make Args:[0m [33mNone[0m[0m
[35m[0m[0m
[1m[36mWorkspace configuration appears valid.[0m[0m
[35m[0m[0m [0m[0m
Found '18' packages in 0.0 seconds. [0m[0m
Starting [1m[32m==>[0m [1m[36mcisst_msgs[0m[0m [0m[0m
[[36mcisst_msgs[0m] [1m[34m==>[0m '[1m/home/adeguet1/catkin_ws/build/cisst_msgs/build_env.sh /usr/bin/make cmake_check_build_system[0m' [30m[1min[0m '[1m/home/adeguet1/catkin_ws/build/cisst_msgs[0m'[0m [0m[0m

```

**Comment by wjwwood** [comment]
It looks like in the recent refactoring we lost the check for whether or not color should be used. I'll need to update that.

**Comment by wjwwood** [comment]
Actually it should work: https://github.com/catkin/catkin_tools/blob/master/catkin_tools/verbs/catkin_build/cli.py#L186-L187

I'd have to look into why it is not detecting the terminal correctly. Can you reproduce this just piping the output to a file or something like that?

**Comment by adeguet1** [comment]
Running Ubuntu 12.04, ROS Hydro with fresh apt-get update/upgrade.   /usr/bin/catkin has:
```python
#! /usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'catkin-tools==0.2.1','console_scripts','catkin'
__requires__ = 'catkin-tools==0.2.1'
```
I didn't customize emacs in any way.  I tried `catkin build > test.txt`.  When I open test.txt under emacs, slightly better output, i.e. the mangling seems to be related to progress display, not colors.

To avoid all confusion, in emacs, I do `M-x compile` followed by `catkin build`.  I'm not using `M-x shell` mostly so I can easily navigate to the source errors in `*compilation*` mode.  If there is another way to do that, I'm happy to switch.

**Comment by wjwwood** [comment]
I have no idea what the different emacs commands do, but based on what you've told me, `M-x compile` is capturing the output of the program it runs by emulating a terminal, where as the `M-x shell` does not.

The check `is_tty` basically checks to see if program connected to `catkin build`'s stdout is a terminal or not, and if it is a terminal or a program emulating a terminal, then it outputs ansi color escape sequences. Otherwise it doesn't.

We can probably add an option to force color off, but this strategy of detecting the tty and turning color on/off based on that is something that a lot of programs do.

Can you turn on colors for `git` then do `C-m compile` followed by `git diff` (or something similar) on a repository with changes and see if you get the escape sequences from `git` as well?

**Comment by jack-oquin** [comment]
As a long-time emacs user, I agree that an option to suppress color in the output would be very helpful.

Something similar to the ``grep --color=never`` option should suffice. Grep also allows ``--color=always`` or ``--color=auto`` (the default). For our British friends, it can also be spelled ``--colour=``.

**Comment by adeguet1** [comment]
Emacs `M-x compile` is describe in https://www.gnu.org/software/emacs/manual/html_node/emacs/Compilation.html but they don't say much about the tty and how the output is parsed.  I use shortcuts to go to the next error and it automatically opens the problematic file and jumps to the error line so there is obviously some parsing and implicit format expected.

I tested the result of `is_tty` using:
```python
#!/usr/bin/env python
import sys

# as defined in common.py
def is_tty(stream):
    return hasattr(stream, 'isatty') and stream.isatty()

if is_tty(sys.stdout):
    print 'is tty'
else:
    print 'is not tty'
```

Using `M-x compile`, the output is `is tty`.

Since there is no easy way to detect this specific Emacs tty, a manual option `--color=false` would be nice.  I hacked the common.py on my machine to always return False and the output is readable and parsable under emacs compilation mode.

**Comment by wjwwood** [comment]
I opened a pull request to add the `--no-color` option.

**Comment by adeguet1** [comment]
Thank you.
