### ISSUE TITLE
Whitelist Packages

### ISSUE THREAD

**Issue by aghazi** [catkin/catkin_tools#149]
I am use the whitelist command to select the packages I want to build. Is there something like this for catkin_tools?
``` catkin_make -DCATKIN_WHITELIST_PACKAGES="foo;bar" ```

**Comment by jbohren** [comment]
The simplest equivalent is:

```
catkin build too bar
```

I'm not certain what the behavior of this would be though:

```
catkin config --cmake-args -DCATKIN_WHITELIST_PACKAGES="foo;bar"
catkin build
```

**Comment by aghazi** [comment]
I tried this. It does not work for me. Can I selected packages to be build in another way? Not just once, but whenever catkin build is called after configuring the list once.

**Comment by jbohren** [comment]
@aghazi What do you think of the interface proposed in #152?

**Comment by jbohren** [comment]
I'm closing this now that #152 has been merged. @aghazi feel free to reopen this if you want to keep discussing it.
