### ISSUE TITLE
Catkin tools don't handle arch-specific library folders

### ISSUE THREAD

**Issue by scpeters** [catkin/catkin_tools#154]
Support for arch-specific library folders was added to catkin in https://github.com/ros/catkin/pull/624 but it does not seem to be present in catkin tools. This is needed to build gazebo with catkin tools.

**Comment by wjwwood** [comment]
Thanks for pointing this out, we'll have to port that functionality to `catkin_tools`, I'll put this issue on the list of things to do before recommending this over `catkin_make_isolated`: https://github.com/catkin/catkin_tools/issues/90

**Comment by scpeters** [comment]
I can take a crack at it, but it will take me a little while to find the time.

**Comment by wjwwood** [comment]
If you have time that'd be great, I could also take a stab at it, but it will also be a while before I have time to spend on it.

**Comment by jbohren** [comment]
> This is needed to build gazebo with catkin tools.

On which platforns / for which versions of Gazebo does this become necessary? I've been building Gazebo 2.x with `catkin_tools` ever since the 2.2.3 breakage.

**Comment by scpeters** [comment]
Starting with gazebo2, the libraries are installed to `${prefix}/lib/x86_64-linux-gnu` on my Ubuntu machine (due to GNUInstallDirs), so the `LD_LIBRARY_PATH` must be modified to include this extra folder.
