### ISSUE TITLE
verbs: catkin setup to source setup files

### ISSUE THREAD

**Issue by k-okada** [catkin/catkin_tools#164]
Hi,

catkin_tools is very useful because you can run `catkin build` from any location of the workspace, but after that I have to manually `source setup.bash` such as `source ../../.../....../devel/setup.bash`. Is this correct? or do you have any useful verbs to do this?

**Comment by wjwwood** [comment]
No we don't have a verb for that currently.

But I wouldn't recommend it anyways. You really shouldn't source in the same terminal as you build. This could, but often doesn't, lead to strange build problems.

**Comment by jbohren** [comment]
@k-okada Take a look at this proposal for a `catkin ws` verb: https://github.com/catkin/catkin_tools/issues/47

**Comment by tkruse** [comment]
Originally the plan was also to update the roscd command to jump to the ws root when invoked without an argument. That would help with various use-cases.

**Comment by jbohren** [comment]
> Originally the plan was also to update the roscd command to jump to the ws root when invoked without an argument. That would help with various use-cases.

Well, we could add a `catkin cd` verb that could _easily_ do that. Also it would make sense to expose the path to the current devel space target like the following:

```sh
$> catkin paths --devel
/path/to/ws/root/devel
```

Then you could add these to handy aliases:

```sh
source $(catkin path --devel)/setup.bash
source $(catkin path --install)/setup.bash
```

**Comment by gavanderhoorn** [comment]
@tkruse wrote:
> Originally the plan was also to update the roscd command to jump to the ws root when invoked without an argument. That would help with various use-cases.

Doesn't `roscd` do that already? I'm probably misunderstanding you, but if I source a ws, then do `roscd`, I end up in the root of that ws.

**Comment by tkruse** [comment]
Could be that roscd does that already.

**Comment by jbohren** [comment]
> Doesn't roscd do that already? I'm probably misunderstanding you, but if I source a ws, then do roscd, I end up in the root of that ws.

`$ROS_WORKSPACE` is no longer set by the catkin setup files (it used to be set by the setup files generated by `rosws`), so `roscd` wouldn't know where to go. The problem that @k-okada is talking about, however,  wouldn't be addressed by this anyway because in that example, the user has yet to source a workspace at all.

**Comment by tkruse** [comment]
I believe roscd has several heuristics for what to do in the case of no argument. 
See here:
https://github.com/ros/ros/blob/e1fbec8f26a4f29fb58c1192c6b9c88b6f7bc764/tools/rosbash/rosbash
for the bash version of roscd

IT seems to check
- ROS_WORKSPACE
- CMAKE_PREFIX_PATH with marker file

I believe it could be possible to have a third fallback, jumping to the first parent folder with a catkin marker file.

**Comment by jbohren** [comment]
> IT seems to check
>
> - ROS_WORKSPACE
> - CMAKE_PREFIX_PATH with marker file

Wow I guess `roscd` on zsh is just broken: https://github.com/ros/ros/blob/e1fbec8f26a4f29fb58c1192c6b9c88b6f7bc764/tools/rosbash/roszsh#L134

It doesn't look for anything in `CMAKE_PREFIX_PATH` and it just errors out with this:
```
No ROS_WORKSPACE set.  Please set ROS_WORKSPACE to use roscd with no arguments.
```

Regardless, any env-based resolution won't work for @k-okada's use case.

**Comment by k-okada** [comment]
If I can
catkin cd; source setup.sh; cd -
, that would make my life super easier, +10000 for this.


2015年3月17日火曜日、Jonathan Bohren<notifications@github.com>さんは書きました:

> IT seems to check
>
>    - ROS_WORKSPACE
>    - CMAKE_PREFIX_PATH with marker file
>
>  Wow I guess roscd on zsh is just broken:
> https://github.com/ros/ros/blob/e1fbec8f26a4f29fb58c1192c6b9c88b6f7bc764/tools/rosbash/roszsh#L134
>
> It doesn't look for anything in CMAKE_PREFIX_PATH and it just errors out
> with this:
>
> No ROS_WORKSPACE set.  Please set ROS_WORKSPACE to use roscd with no arguments.
>
> Regardless, any env-based resolution won't work for @k-okada
> <https://github.com/k-okada>'s use case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/catkin/catkin_tools/issues/164#issuecomment-82381553>.
>


-- 
--
◉ Kei Okada

**Comment by tkruse** [comment]
@jbohren: I think you were looking on the wrong branch (probably because I pointed to the wrong branch in the first place). Indigo should be:
https://github.com/ros/ros/blob/indigo-devel/tools/rosbash/roszsh
https://github.com/ros/ros/blob/indigo-devel/tools/rosbash/rosbash

**Comment by jbohren** [comment]
> @jbohren: I think you were looking on the wrong branch (probably because I pointed to the wrong branch in the first place).

Yeah, I knew I was looking at hydro, since that's what I'm still using. I hadn't checked if they had fixed it yet in indigo, though.

**Comment by jbohren** [comment]
@k-okada Take a look at PR #192 which adds a `catkin source` shell verb to source a setup file.

**Comment by k-okada** [comment]
thanks!

If I understand correctly

1) i think you need to update
https://github.com/catkin/catkin_tools/pull/165 to use locate not find
2) i had following error, I'm not sure where `${@[*]}` comes from, but
 need to use `ORIG_ARGS=($@)
` instead of `ORIG_ARGS=(${@[*]})`
```
$ catkin cd
bash: ${@[*]}: bad substitution

```

--
◉ Kei Okada

**Comment by k-okada** [comment]
created patch at #268

**Comment by k-okada** [comment]
catkin source has been supported on 0.3.1, so now we can close
