### ISSUE TITLE
Allow setting python version

### ISSUE THREAD

**Issue by v01d** [catkin/catkin_tools#166]
Currently, the _setup_util.py script, which sets environment variables, grabs python version 3, for which support is not complete. Furthermore, on ArchLinux, python2 is used for ROS (while python3 is the system default). I manally change the _setup_util.py to 2.7 and the problem is solved, however this is cumbersome.

**Comment by wjwwood** [comment]
The `_setup_util.py` is not created by `catkin_tools`, please refile this on the `catkin` repository:

https://github.com/ros/catkin/issues

Related links:

- https://github.com/ros/catkin/blob/indigo-devel/cmake/templates/_setup_util.py.in
- https://github.com/ros/catkin/pull/646

**Comment by dirk-thomas** [comment]
@v01d And before you fill a ticket in the `catkin` repository:

The file is being expanded with the Python version you use to invoke catkin / CMake in the first place. You can simply pass in the Python version you would like to use as a CMake variable (https://github.com/ros/catkin/blob/2599eb973762c2a23f103fdc8bd0ef40e779f2ed/cmake/python.cmake#L3):

    -DPYTHON_VERSION=2.7

Otherwise it will default to whatever Python version is called `python` on your system.

**Comment by v01d** [comment]
Thanks dirk, I will use the variable you mention. It does not sound like a bug then.

**Comment by v01d** [comment]
Hi,
I've actually tried settings this variable and it does not change the _setup_util.py file. What do you think could be happening?

**Comment by v01d** [comment]
Actually, it only seems to work when defining PYTHON_EXECUTABLE

**Comment by dirk-thomas** [comment]
If I run the following command:

    catkin_make -DPYTHON_VERSION=3.4

the generated `_setup_util.py` contains the shebang line:

    #!/usr/bin/python3.4

**Comment by v01d** [comment]
In my case I can only get the behavior by changing PYTHON_EXECUTABLE. The thing is that once it is defined, even including --force-cmake does not appear to clear the variable. So maybe PYTHON_VERSION is being overriden by the fact that PYTHON_EXECUTABLE still points to a specific version. I tried undefining the variable from within catkin but the -U syntax does not seem to be supported.

**Comment by dirk-thomas** [comment]
Have you tried it after clearing the build space?

**Comment by v01d** [comment]
I cleared the build space and I can confirm that when selecting PYTHON_VERSION it says it finds python 3.4.3 while saying "minimum requested version 2", so there's a problem there already. I have python2 installed so it should find the correct version.
I can work around this by defining PYTHON_EXECUTABLE, but I realized this flag is per-package so whenever I compile a different package the _setup_util.py is re-created with python 3. 

Is there any way of defining this flag as a default somewhere for catkin tools? ArchLinux uses python3 as default and therefore I would not like to make a system-wide change. Moreover, with catkin_make ArchLinux solved this by recommending to set a bash alias so that the correct cmake variable definitions are passed. However, since catkin uses the "verb" strategy it is not possible to define a bash alias since this flag only needs to be passed when the "build" verb is used.

**Comment by dirk-thomas** [comment]
Please post more information to allow debugging why passing the Python version does not work for you: e.g. what is the exact command you invoke, the CMake configure output, the PYTHON related variables from the generated CMake cache file. Also information about your environment: e.g. the exact names of the available Python binaries available.

**Comment by wjwwood** [comment]
> Is there any way of defining this flag as a default somewhere for catkin tools?

You can use a verb alias: http://catkin-tools.readthedocs.org/en/latest/advanced/verb_customization.html

**Comment by jbohren** [comment]
@v01d Did you ever find a good solution to this problem?

**Comment by v01d** [comment]
I simply added an alias as following:
build: build -DPYTHON_EXECUTABLE=/usr/bin/python2.7

**Comment by jbohren** [comment]
@v01d Thanks, we're compiling a list of solved issues for a migration guide.
