### ISSUE TITLE
Causes computer to occasionally run out of memory

### ISSUE THREAD

**Issue by davetcoleman** [catkin/catkin_tools#167]
When running ``catkin build`` my system sometimes runs out of memory, where it uses about 75% of my 16GB of RAM. I've had this issue both with and without the https://github.com/catkin/catkin_tools/pull/155 branch. Its happened twice today, so I figured I should finally report it. The memory history plot in System Monitor shows the usage at ~90% for a while, then it finally caps at 100% before I have to hard restart my PC. I'm not sure what else to provide to help at this point. Here are the packages in my workspace (some are not fully released):

```
hrl_kinematics/
moveit_core/
moveit_hrp2/
moveit_humanoid/
moveit_ompl/
moveit_ork/
moveit_ros/
moveit_visual_tools/
moveit_whole_body_ik/
ompl/
ompl_experience_demos/
ompl_thunder/
ompl_visual_tools/
rviz_visual_tools/
srdfdom/
```

**Comment by wjwwood** [comment]
AFAIK there's nothing to be done, other than build with a lower `-p` and/or a lower `-j`.

**Comment by jbohren** [comment]
@davetcoleman you can try to  modify #155 to only give out tokens if there's enough ram.

Also, you might want to consider giving your computer a swap partition.

**Comment by jbohren** [comment]
@davetcoleman can you run `vcs export --exact` in your workspace source root?

**Comment by jbohren** [comment]
@davetcoleman #155 now has a hidden experimental option `--mem-limit` which will prevent `catkin build` from dispatching jobs if your system memory usage exceeds the given percentage.

Example usage (don't dispatch more than one job if 95% memory is used):

```
catkin build --force-cmake --mem-limit 95
```

**Comment by tfoote** [comment]
@jbohren It might make sense to specify a minimum size in addition to a percentage since it's consistent across different systems. And the maximum size of a compile unit is hopefully consistent across machines.

**Comment by jbohren** [comment]
> @jbohren It might make sense to specify a minimum size in addition to a percentage since it's consistent across different systems. And the maximum size of a compile unit is hopefully consistent across machines.

Then I'd say there should be two args:

- `--mem-limit` -- limit to one parallel job if `catkin` uses more than some amount of memory 
 - `--mem-limit P%` -- `P` percent of total physical memory
 - `--mem-limit N` -- `N` bytes
 - `--mem-limit Nk` -- `N` kilobytes
 - `--mem-limit Nm` -- `N` megabytes
 - `--mem-limit Ng` -- `N` gigabytes
- `--sys-mem-limit` -- limit to one parallel job if more than some amount of memory is being used by the whole system 
 - `--sys-mem-limit P%` -- `P` percent of total physical memory
 - `--sys-mem-limit N` -- `N` bytes
 - `--sys-mem-limit Nk` -- `N` kilobytes
 - `--sys-mem-limit Nm` -- `N` megabytes
 - `--sys-mem-limit Ng` -- `N` gigabytes

**Comment by davetcoleman** [comment]
``vcs export --exact`` - though its fairly custom from released packages
https://gist.github.com/davetcoleman/170b7ef5753ee13473d0

**Comment by jbohren** [comment]
@davetcoleman The `--mem-limit` option is now on master, though it's a hidden option, it will be documented in #250.

**Comment by davetcoleman** [comment]
sweet, thanks!

**Comment by joao-aguizo** [comment]
I know this is out of the scope in what concerns to this package functionality, but  still it might be useful to users relying on older versions of this package. In my case the way I found to workaround this issue was to create a swap file. This helped the system release some memory, thus stopping it from freezing.
