### ISSUE TITLE
Possible bug in  catkin_tools/argument_parsing.py

### ISSUE THREAD

**Issue by abhinavkssk** [catkin/catkin_tools#171]
It seems that the latest version is ignoring the cmake args command while configuring, while this is not the case with the older version. On closer inspection of the commits, the culprit turned out to be 
line 119 in   catkin_tools/argument_parsing.py 

```python
end_index = args.index('--', start_index + 1) if '--' in args else None
```

changing it to 

```python
end_index = args.index('--', start_index + 1) if '--' in args else (len(args) - 1)
```

seems to have fixed it.

Could someone please confirm this?

**Comment by wjwwood** [comment]
Thanks for reporting the issue. That seems like a reasonable change, but I'll defer to @jbohren on this one. You might consider opening a pull request to that effect, it might make it go faster and you'll get some attribution for the fix.

**Comment by jbohren** [comment]
@abhinavkssk Are you still having this issue, and have you had a chance to try #184? Your PR #172 fails to pass the unit tests.

**Comment by abhinavkssk** [comment]
#184 Seems to fixing it. I've been using that with no problems.

**Comment by abhinavkssk** [comment]
#184 Seems to be fixing this, I've been using that without any problems
