### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by scpeters** [catkin/catkin_tools#177]
I'd really like to start recommending catkin tools, but I can't until the changes from #156 are released.

**Comment by wjwwood** [comment]
Can this wait until Thursday?

**Comment by scpeters** [comment]
Sure.

**Comment by scpeters** [comment]
bump

**Comment by jbohren** [comment]
@scpeters one thing that's blocking this is the release of the latest version of catkin_pkg getting out to the debs (it's already in pypi).

**Comment by scpeters** [comment]
I already have the `python-catkin-pkg_0.2.8-1_all.deb` on my system. Is there another version that we're waiting for?

**Comment by wjwwood** [comment]
@scpeters no, that's been pushed out now. The current delay is because of me and a few outstanding pull requests/issues which affect currently merged features like the job server. I'll try my best to get a version out today.

**Comment by scpeters** [comment]
Ok, I was just checking. Thanks for your attention, and take your time. I'm just really excited for the next release!

**Comment by wjwwood** [comment]
Ok, now that I got that bash completion issue merged I'm going to do a release.

**Comment by wjwwood** [comment]
`0.3.0` is released.

**Comment by scpeters** [comment]
Thanks! I see the 0.3.0 in [pypi](https://pypi.python.org/pypi/catkin_tools/0.3.0), but I can't apt-get it yet. I assume that will happen soon.

Thanks again!

**Comment by wjwwood** [comment]
I was able to `apt-get` install it:

```
$ cat /etc/apt/sources.list.d/ros-latest.list
deb http://packages.ros.org/ros/ubuntu trusty main

$ sudo apt-get remove python-catkin-tools
[sudo] password for william:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  python-catkin-tools
0 upgraded, 0 newly installed, 1 to remove and 252 not upgraded.
After this operation, 679 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 281846 files and directories currently installed.)
Removing python-catkin-tools (0.3.0-1) ...

$ sudo apt-get install python-catkin-tools
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  python-catkin-tools
0 upgraded, 1 newly installed, 0 to remove and 252 not upgraded.
Need to get 0 B/258 kB of archives.
After this operation, 679 kB of additional disk space will be used.
Selecting previously unselected package python-catkin-tools.
(Reading database ... 281767 files and directories currently installed.)
Preparing to unpack .../python-catkin-tools_0.3.0-1_all.deb ...
Unpacking python-catkin-tools (0.3.0-1) ...
Setting up python-catkin-tools (0.3.0-1) ...
```

Did you do an `sudo apt-get update` first?

**Comment by scpeters** [comment]
You're right, it's there, but it's not on shadow-fixed:

http://packages.ros.org/ros-shadow-fixed/ubuntu/pool/main/p/python-catkin-tools/

**Comment by wjwwood** [comment]
Apparently that's correct, it will eventually be in shadow-fixed, but the reason for why it isn't is complicated. @tfoote can explain it if you like.

**Comment by scpeters** [comment]
I'll take your word for it. I had just assumed that shadow-fixed would get all packages before the main repository, but I can believe that there are complicating factors. I'll just wait a little longer I guess.

**Comment by wjwwood** [comment]
I guess you have to have shadow-fixed? I can look at kicking it.

**Comment by wjwwood** [comment]
Ok I ran something that may have done something about it. Can you try again?

**Comment by scpeters** [comment]
Thanks, it's there now
