### ISSUE TITLE
Dependency not respected between two packages

### ISSUE THREAD

**Issue by hgaiser** [catkin/catkin_tools#180]
I have two packages, one called `dr_cmake` and one called `dr_util`. `dr_util` has `<build_depend>dr_cmake></build_depend>`, but regardless, `dr_util` and `dr_cmake` are started in parallel by `catkin build`. This causes a cmake error where `dr_util` cannot find `dr_cmake`. Running `catkin build` again allows it to compile because at that time `dr_cmake` has been built.

**Comment by jbohren** [comment]
Really? That's a petty dramatic failure. Can you post the output of:

`catkin config `

And

`catkin list --deps /path/to/ws/src`

**Comment by hgaiser** [comment]
Ah ... `catkin list --deps` gave me the reason it went wrong, a type in package.xml (it is also in the first post, `<build_depend>dr_cmake></build_depend>`). Strange that it does not give a warning or error about this..
