### ISSUE TITLE
config: Allow wildcard for blacklist / whitelist packages

### ISSUE THREAD

**Issue by hgaiser** [catkin/catkin_tools#191]
I'm using `catkin profile` to build certain projects, where I have to write down every package it should blacklist. It would be nice to blacklist all packages with a wildcard, such that I can blacklist `project1_*`.

**Comment by jbohren** [comment]
Yeah I think having regex or glob support would be great.

**Comment by NikolausDemmel** [comment]
glob support would be great, yeah. Same for the list of packages to build, i.e. allow `catkin build foo-*`.

**Comment by jbohren** [comment]
For anyone interested in implementing this, you could probably use `fnmatch`: https://docs.python.org/2/library/fnmatch.html
