### ISSUE TITLE
Order of arguments and package names wrong in catkin build usage message

### ISSUE THREAD

**Issue by tpet** [catkin/catkin_tools#193]
The usage message for catkin build (`catkin build --help`) seems to switch the order of arguments and package names.
While the usage message says `catkin build [--arguments] [package names]`, the correct order seems to be `catkin build [package names] [--arguments]`.

**Comment by jbohren** [comment]
Both orders work, this isn't really a bug.

**Comment by tpet** [comment]
It seems to depend on what arguments are used, for example
`catkin build --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo my_package`
does not work, but
`catkin build my_package --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo`
does work.

Using Ubuntu 12.04 with python-catkin-tools 0.2.2-1 (precise).

**Comment by wjwwood** [comment]
> --cmake-args ARG [ARG ...]
                        Arbitrary arguments which are passes to CMake. It
                        collects all of following arguments until a "--" is
                        read.

You'll have to pass a `--` before continuing with other options after `--cmake-args`. Please close this if you think this addresses your question.

**Comment by tpet** [comment]
Now I see that it is even documented in the help details. Thanks for clarifying this for me.
