### ISSUE TITLE
catkin tests: Catkin test results directory collides in devel space

### ISSUE THREAD

**Issue by jbohren** [catkin/catkin_tools#198]
The `05.catkin-test-results.sh` file is over-written by all packages built in a merged devel space. Each one of them puts a path to it's own build directory in that file.

Fixing this might require adding a `CATKIN_TEST_RESULTS_DESTINATION` CMake variable which `catkin_tools` can set so that test results go to the right place.

@dirk-thomas Does that look like a fair assessment?

Might be related to #139

**Comment by dirk-thomas** [comment]
The `CATKIN_TEST_RESULTS_DESTINATION` environment variable will be gone in the upcoming catkin version. See ros/catkin#719 for details.

**Comment by jbohren** [comment]
Ah cool. Will that be released into the hydro version of catkin?

**Comment by dirk-thomas** [comment]
I don't think the change will be backported to Hydro. Hydro will be EOL in about a month. I don't think it is a good idea to change it anymore.

**Comment by jbohren** [comment]
Resolved by https://github.com/ros/catkin/pull/728
