### ISSUE TITLE
Setting CMake Args

### ISSUE THREAD

**Issue by davetcoleman** [catkin/catkin_tools#199]
I'm not sure what I am doing wrong, but I'd like to build with warnings/etc but I can't get the compiler flags to be set from the ``catkin build`` command. I'm trying:

```
catkin build -v --cmake-args -DEXTRA_C_FLAGS=-Wall\ -g\ -W\ -Wno-unused-parameter
```

And in the top of the build process it correctly says:
```
Additional CMake Args:       -DEXTRA_C_FLAGS=-Wall\ -g\ -W\ -Wno-unused-parameter
```

But I get the error while building packages:
```
[hrp2jsknt_moveit_config] ==> '/home/dave/ros/ws_moveit/build/hrp2jsknt_moveit_config/build_env.sh /usr/bin/cmake /home/dave/ros/ws_moveit/src/moveit_hrp2/hrp2jsknt_moveit_config -DCATKIN_DEVEL_PREFIX=/home/dave/ros/ws_moveit/devel -DCMAKE_INSTALL_PREFIX=/home/dave/ros/ws_moveit/install -DEXTRA_C_FLAGS=-Wall\ -g\ -W\ -Wno-unused-parameter' in '/home/dave/ros/ws_moveit/build/hrp2jsknt_moveit_config'
CMake Error: The source directory "/home/dave/ros/ws_moveit/build/hrp2jsknt_moveit_config/-Wno-unused-parameter" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
[hrp2jsknt_moveit_config] <== '/home/dave/ros/ws_moveit/build/hrp2jsknt_moveit_config/build_env.sh /usr/bin/cmake /home/dave/ros/ws_moveit/src/moveit_hrp2/hrp2jsknt_moveit_config -DCATKIN_DEVEL_PREFIX=/home/dave/ros/ws_moveit/devel -DCMAKE_INSTALL_PREFIX=/home/dave/ros/ws_moveit/install -DEXTRA_C_FLAGS=-Wall\ -g\ -W\ -Wno-unused-parameter' failed with return code '1'
```

 In particular:
``CMake Error: The source directory "/home/dave/ros/ws_moveit/build/hrp2jsknt_moveit_config/-Wno-unused-parameter" does not exist.``

I can't find any documentation on how to correctly set these flags. Thanks for your help!

**Comment by wjwwood** [comment]
It's not clear to me how it is globing those together, but have you tried using `"` rather than escaping the whitespace? Something like this:

```
$ catkin build -v --cmake-args -DEXTRA_C_FLAGS="-Wall -g -W -Wno-unused-parameter"
```

Maybe that will work.

**Comment by jbohren** [comment]
It worked for me the exact way that @davetcoleman wrote it. One key difference is that the slashes didn't show up in my summary. I tried it both with `bash` and `zsh` on the `master` branch.

I recall this being a problem that was fixed in the past, but I couldn't find an issue related to it.

**Comment by davetcoleman** [comment]
Perfect, thanks: https://github.com/catkin/catkin_tools/issues/200
