### ISSUE TITLE
catkin_make vs. catkin build for CGAL

### ISSUE THREAD

**Issue by StephanOpfer** [catkin/catkin_tools#210]
Hi all,

I have a ROS package, which did work, when I compiled it with "catkin_make". It still compiles with "catkin build" (see   [catkin_tools](http://catkin-tools.readthedocs.org)), but it does not run anymore. The created executable is using [CGAL](http://www.cgal.org/), and that library is complaining about some rounding issue, when I compile it with "catkin build".

Here is the runtime error:

    terminate called after throwing an instance of 'CGAL::Assertion_exception'
        what():  CGAL ERROR: assertion violation!
    Expr: -CGAL_IA_MUL(-1.1, 10.1) != CGAL_IA_MUL(1.1, 10.1)
    File: /usr/include/CGAL/Interval_nt.h
    Line: 209
    Explanation: Wrong rounding: did you forget the  -frounding-math  option if you use GCC (or  -fp-model strict  for Intel)?
    Aborted (core dumped)

Does anybody has a clue, why catkin build breaks it? Here is my CMakeLists.txt:

    cmake_minimum_required(VERSION 2.8.3)
    project(msl_base)

    ## Use c++ 11x std
    set(CMAKE_CXX_FLAGS "-std=c++11 ${CMAKE_CXX_FLAGS}")

    ## Enable exception handling for segfaults
    set(CMAKE_CXX_FLAGS "-rdynamic -g -fnon-call-exceptions -ggdb ${CMAKE_CXX_FLAGS}")

    ## Used for cgal
    set(CGAL_DONT_OVERRIDE_CMAKE_FLAGS TRUE CACHE BOOL "Don't override flags")
    set(CMAKE_CXX_FLAGS "-lCGAL -lCGAL_Core -frounding-math ${CMAKE_CXX_FLAGS}")

    ## Find catkin macros and libraries
    ## if COMPONENTS list like find_package(catkin REQUIRED COMPONENTS xyz)
    ## is used, also find other catkin packages
    find_package(catkin REQUIRED COMPONENTS
      roscpp 
      system_config 
      system_util 
      fsystem 
      autodiff 
      event_handling 
      alica_engine 
      alica_ros_proxy 
      msl_expressions 
      msl_worldmodel
    )
    
    find_package(CGAL REQUIRED COMPONENTS Core)
    
    
    ###################################
    ## catkin specific configuration ##
    ###################################
    ## The catkin_package macro generates cmake config files for your package
    ## Declare things to be passed to dependent projects
    ## INCLUDE_DIRS: uncomment this if you package contains header files
    ## LIBRARIES: libraries you create in this project that dependent projects also need
    ## CATKIN_DEPENDS: catkin_packages dependent projects also need
    ## DEPENDS: system dependencies of this project that dependent projects also need
    catkin_package(
      INCLUDE_DIRS include
      LIBRARIES
      CATKIN_DEPENDS alica_engine alica_ros_proxy msl_expressions msl_simulator msl_worldmodel
      DEPENDS cgal
    )
    
    ###########
    ## Build ##
    ###########
    
    
    ## Specify additional locations of header files
    ## Your package locations should be listed before other locations
    include_directories(include ${catkin_INCLUDE_DIRS} ${CGAL_INCLUDE_DIRS})
    include(${CGAL_USE_FILE})
    
    ## Declare a cpp executable
    add_executable(msl_base src/Base.cpp)
    
    ## Specify libraries to link a library or executable target against
    target_link_libraries(msl_base ${catkin_LIBRARIES} ${CGAL_LIBRARIES})
    
    ## Add cmake target dependencies of the executable/library
    ## as an example, message headers may need to be generated before nodes
    add_dependencies(msl_base ${catkin_LIBRARIES} ${CGAL_LIBRARIES})

**Comment by jbohren** [comment]
@StephanOpfer Is the executable you're built in the `msl_base` package?

**Comment by StephanOpfer** [comment]
@jbohren Yes it is.

**Comment by jbohren** [comment]
Can you post the output from the following?

```
VERBOSE=1 catkin build -v -p1 msl_base
```

Putting it in a [gist](gist.github.com) would be best.

**Comment by StephanOpfer** [comment]
Here it is: https://gist.github.com/StephanOpfer/194b1ab029e73334a06c

Somewhat lengthy :smile:

**Comment by jbohren** [comment]
Ack. How about:

```
VERBOSE=1 catkin build --no-status -v -p1 msl_base
```

**Comment by StephanOpfer** [comment]
Updated the gist: https://gist.github.com/StephanOpfer/194b1ab029e73334a06c

**Comment by StephanOpfer** [comment]
I also did load up the output of 
    
    VERBOSE=1 catkin_make -d -j1 --pkg msl_base

Its really huge, but looking at the difference between the compile command for Base.cpp (the only source file in msl_base), I could only notice that  catkin_make is adding

    -DROS_BUILD_SHARED_LIBS=1

**Comment by jbohren** [comment]
Can you run it after building with `CMAKE_BUILD_TYPE=Debug`?

```
catkin config --cmake-args -DCMAKE_BUILD_TYPE=Debug
catkin build --force-cmake
```

**Comment by jbohren** [comment]
I suspect that you're getting cross-talk between your packages when using `catkin_make` which is hiding a bug in your build config.

Do you have the same problem with `catkin_make_isolated`?

**Comment by jbohren** [comment]
@StephanOpfer Take a look at https://github.com/carpe-noctem-cassel/cnc-msl/issues/1 for a potential explanation and fix.

**Comment by StephanOpfer** [comment]
@jbohren Thank you, for your help. Now it is fixed.

We are still learning CMake and all that build dependency stuff. "catkin build" is a great tool, as it showed a lot of failures in our build configurations. To be honest, it took be 1 hour to remove all the failures, we had in our configurations. The astonishing fact is, that it all worked with "catkin_make" before. 

The failure with the CGAL stuff, would have took be days to find! :)

I personally didn't know about the CFG_EXTRAS command, so here is the documentation for everyone interested: http://docs.ros.org/hydro/api/catkin/html/dev_guide/generated_cmake_api.html#catkin_package.

**Comment by jbohren** [comment]
> @jbohren Thank you, for your help. Now it is fixed.

Yeah, these sort of bugs are a huge pain. They can even appear when using `catkin_make` if an unrelated package changes the build topology. Unfortunately I've encountered them so often that I've gotten pretty good at fixing them, so I'm glad I could help.

> I personally didn't know about the CFG_EXTRAS command

Yeah, it's the replacement for the rosbuild's old `<cpp>` `cflags` export. It can be pretty powerful.
