### ISSUE TITLE
list: Clarify `--depends-on` behavior

### ISSUE THREAD

**Issue by jbohren** [catkin/catkin_tools#212]
@wjwwood Currently, `catkin list --depends-on` only shows the direct dependencies of each package. Is this the correct behavior, or should it be recursive?

**Comment by wjwwood** [comment]
That's a good question. My gut reaction is that the pair `--depends-on` and `--depends-on-recursive` are clearer than the pair `--depends-on-1` and `--depends-on`, which are direct dependencies and recursive dependencies respectively. However, I've seen both patterns used in similar command line options.

**Comment by jbohren** [comment]
I also like "recursive" since the meaning is clearer.

**Comment by jbohren** [comment]
This should be fixed in #293.
