### ISSUE TITLE
run compiled binaries from within qtcreator

### ISSUE THREAD

**Issue by simonschmeisser** [catkin/catkin_tools#217]
I followed the advice from http://wiki.ros.org/IDEs#catkin_tools-1 and set up a new catkin ws. I then called catkin init and catkin build. Finally I opened the CMakeLists.txt from one of the sub projects, set the build dir to ws/build/package and was able to build it nicely from within QtCreator

but what I would really like to be able to do is to run (Ctrl+R) the resulting binaries directly without further troubles. Currently I get "No executable specified."

I can easily workaround this by going to "Projects"->"Desktop Run"->Section run click on "Add" and then on the target. However some environment variable will still be missing, giving me "rospack" errors
    [rospack] Error: package 'workcell_config' not found

**Comment by jbohren** [comment]
>but what I would really like to be able to do is to run (Ctrl+R) the resulting binaries directly without further troubles. Currently I get "No executable specified."

Is this a problem with catkin or with your QtCreator install? It seems some other people have had troubles with this on Ubuntu: http://stackoverflow.com/questions/26868219/qtcreator-cmake-no-executable-specified

>I can easily workaround this by going to "Projects"->"Desktop Run"->Section run click on "Add" and then on the target. However some environment variable will still be missing, giving me "rospack" errors
[rospack] Error: package 'workcell_config' not found

Yeah, you will need to source `devel/setup.bash` in order for rospack to be able to find your package and the binaries associated with it.

**Comment by NikolausDemmel** [comment]
> but what I would really like to be able to do is to run (Ctrl+R) the resulting binaries directly without further troubles. Currently I get "No executable specified."

It would be great to generate the QtCreator project file (`CMakeLists.txt.user`) automatically from command line with the correct build space similar to how it can be done for Eclipse, and then also automatically include run configurations for the executables as you suggest. I am not sure if something like this is possible with QtCreator though.

I have been using QtCreator for my catkin projects and with `catkin_tools` for a while now and am quite happy with it, but adding projects initially is a bit cumbersome. With the latest QtCreator 3.6.0 it defaults to creating 5 build spaces, of which you probably want to unselect 4 and the choose the right folder for the 5th.

**Comment by simonschmeisser** [comment]
This is now working at QtCreator 3.6.0.

I usually do

1. catkin build
2. open CMakeLists.txt of the subproject in QtCreator
3. disable all build targets except "Debug" (usually) and set the build dir to CATKIN_WS/build/PACKAGENAME *
4. works like a charm

* choose the actual folders, these are no environment variables or similar but only placeholders

**Comment by NikolausDemmel** [comment]
Just for reference, I started a discussion on the qtcreator mailing list about generating the project files with correct builld-directories from commandline: http://lists.qt-project.org/pipermail/qt-creator/2016-March/005621.html
