### ISSUE TITLE
please fix: install location of bash_completion file

### ISSUE THREAD

**Issue by wkentaro** [catkin/catkin_tools#222]
In my environment,

* OSX, Yosemite
* python which is installed via Homebrew

the shell completion file is installed at

`/usr/local/lib/python2.7/site-packages/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/etc/bash_completion.d/catkin_tools-completion.bash`

but I think it should be `/usr/local/etc/bash_completion.d`.

**Comment by wjwwood** [comment]
This is probably because you're not using the system Python and while there is special logic to handle the system python on OS X, there's no logic to handle it when its in the Cellar.
