### ISSUE TITLE
catkin_make vs. catkin build in case of linking static libraries

### ISSUE THREAD

**Issue by StephanOpfer** [catkin/catkin_tools#228]
Hi all,

I have a static library "libcling_wrap", which links three other static libraries (libgringo, libprogram_opts, libclasp). Each library is compiling, but the gunit-test, which tests the "libcling_wrap" gives me a linker error, when I compile it with 
```catkin build cling_wrap --no-deps --catkin-make-args run_tests```
But is compiles and runs the test with
```catkin_make run_tests_cling_wrap_gtest```

The ros-package and its CMakeLists.txt is here:
https://github.com/carpe-noctem-cassel/supplementary/tree/master/cling_wrap

In order to compile it, you will need the following ubuntu system packages:
bison re2c libtbb-dev

catkin build has problems to link tbb stuff:
```
Linking CXX executable /home/emmeda/Research/dev/cnc-ws/devel/lib/cling_wrap/cling_wrap-test
/home/emmeda/Research/dev/cnc-ws/devel/lib/liblibclasp.a(clasp_facade.cpp.o): In function `~tbb_thread_v3':
/usr/include/tbb/tbb_thread.h:173: undefined reference to `tbb::internal::tbb_thread_v3::detach()'
/home/emmeda/Research/dev/cnc-ws/devel/lib/liblibclasp.a(clasp_facade.cpp.o): In function `Clasp::ClaspFacade::SolveImpl::join()':
/home/emmeda/Research/dev/cnc-ws/src/supplementary/cling_wrap/libclasp/src/clasp_facade.cpp:156: undefined reference to `tbb::internal::tbb_thread_v3::join()'
/home/emmeda/Research/dev/cnc-ws/devel/lib/liblibclasp.a(clasp_facade.cpp.o): In function `Clasp::mt::ParallelSolveOptions::recommendedSolvers()':
/home/emmeda/Research/dev/cnc-ws/src/supplementary/cling_wrap/libclasp/clasp/parallel_solve.h:76: undefined reference to `tbb::internal::tbb_thread_v3::hardware_concurrency()'
/home/emmeda/Research/dev/cnc-ws/src/supplementary/cling_wrap/libclasp/clasp/parallel_solve.h:76: undefined reference to `tbb::internal::tbb_thread_v3::hardware_concurrency()'
/home/emmeda/Research/dev/cnc-ws/devel/lib/liblibclasp.a(clasp_facade.cpp.o): In function `tbb::interface5::condition_variable::wait(tbb::interface5::unique_lock<tbb::mutex>&)':
/usr/include/tbb/compat/condition_variable:390: undefined reference to `tbb::internal::throw_exception_v4(tbb::internal::exception_id)'
/home/emmeda/Research/dev/cnc-ws/devel/lib/liblibclasp.a(clasp_facade.cpp.o): In function `Clasp::ClaspFacade::SolveImpl::join()':
/home/emmeda/Research/dev/cnc-ws/src/supplementary/cling_wrap/libclasp/src/clasp_facade.cpp:156: undefined reference to `tbb::internal::tbb_thread_v3::join()'
/home/emmeda/Research/dev/cnc-ws/devel/lib/liblibclasp.a(clasp_facade.cpp.o): In function `tbb::interface5::condition_variable::wait(tbb::interface5::unique_lock<tbb::mutex>&)':
/usr/include/tbb/compat/condition_variable:390: undefined reference to `tbb::internal::throw_exception_v4(tbb::internal::exception_id)'
/home/emmeda/Research/dev/cnc-ws/devel/lib/liblibclasp.a(clasp_facade.cpp.o): In function `Clasp::ClaspFacade::SolveImpl::join()':
/home/emmeda/Research/dev/cnc-ws/src/supplementary/cling_wrap/libclasp/src/clasp_facade.cpp:156: undefined reference to `tbb::internal::tbb_thread_v3::join()'
/home/emmeda/Research/dev/cnc-ws/devel/lib/liblibclasp.a(clasp_facade.cpp.o): In function `tbb::interface5::condition_variable::wait(tbb::interface5::unique_lock<tbb::mutex>&)':
/usr/include/tbb/compat/condition_variable:390: undefined reference to `tbb::internal::throw_exception_v4(tbb::internal::exception_id)'
/home/emmeda/Research/dev/cnc-ws/devel/lib/liblibclasp.a(clasp_facade.cpp.o): In function `tbb::interface5::condition_variable::wait_for(tbb::interface5::unique_lock<tbb::mutex>&, tbb::tick_count::interval_t const&)':
...
```

Any help is welcome! :)

Greetings,
  Stephan

**Comment by wjwwood** [comment]
You need to link the executable `cling_wrap-test` against `tbb` or you need to `find_package` it before trying to use it. Probably you only see this with `catkin build` because `catkin_make` has only one cmake invocation and often hides missing dependencies. Basically, package A find's `tbb` and uses it, then package B also uses `tbb`. This works with `catkin_make` because package A comes first and finds `tbb`. But when you build package B by itself (which is what happens with `catkin build`) you get the error because it uses `tbb` but doesn't find it.

**Comment by StephanOpfer** [comment]
@wjwwood Thx, I fixed it with your help!

What I didn't achieve, was that the static library "libclasp", which needed the shared system library "tbb" it the first place, made every library linking to "libclasp" also link to "tbb". The CMake docu talks about the LINK_PUBLIC flag in the target_link_libraries command, but that didn't work for me...

Is there a special issue with static libraries and interface libraries?

Thanks for your help.

**Comment by wjwwood** [comment]
Unfortunately, I don't have a lot of experience with static libraries being used in that way and so I don't know. If you find some way to solve it, then make a mention here, so others might benefit too. I think you'll have to delve into the CMake docs/issue tracker for those issues.
