### ISSUE TITLE
catkin create pkg with -p seems to be broken

### ISSUE THREAD

**Issue by NikolausDemmel** [catkin/catkin_tools#233]
$ catkin create pkg -p quux quax
path: quux
Creating package "quax" in "quux"...
Created file quax/quux/quax/package.xml
Created file quax/quux/quax/CMakeLists.txt
Successfully created package files in quux/quax.

$ ls quux/quax/quux/quax/
CMakeLists.txt  package.xml

**Comment by jbohren** [comment]
This is fixed in #260
