### ISSUE TITLE
Question about target naming

### ISSUE THREAD

**Issue by davetcoleman** [catkin/catkin_tools#236]
The [catkin documentation section 7.1 Target Naming](http://wiki.ros.org/catkin/CMakeLists.txt) says:

> the names of build targets in catkin must be unique regardless of the folders they are built/installed to. This is a requirement of CMake.

And someone was explaining to me in a [PR](https://github.com/ros-planning/moveit_setup_assistant/pull/108/files#r46586441):

> Since catkin collects all cmake target there is recommendation of prefixing all targets with the package name.

Which surprised me because
1. I feel like this is not followed much in ROS
2. This is cumbersome for long package names: ``moveit_setup_assistant_collision_updater``
3. I think this is no longer true with catkin_tools, only catkin_make

Is this recommendation very important?

**Comment by jbohren** [comment]
This doesn't matter for `catkin_tools` if your workspace is configured to use an isolated build space (the default).

**Comment by davetcoleman** [comment]
Thanks, that's what I thought. So now we just need to get everyone to switch to the far better catkin_tools :)

**Comment by wjwwood** [comment]
It's still a good idea to do it if you remember to, because many people still use/prefer `catkin_make` and they'll potentially run into trouble trying to use your package if you don't do this. You can use the `${PROJECT_NAME}` expansion to more easily prefix your targets and avoid typing the package name over and over. You could even do something like this:

```
set(_pn ${PROJECT_NAME})
add_executable(${_pn}_node1 ...)
add_executable(${_pn}_node2 ...)
```

Just to keep things short.

> This doesn't matter for catkin_tools if your workspace is configured to use an isolated build space (the default). Build targets only need to be unique within a single catkin package.

There's no merged build space as an option for `catkin build`, as far as I know, so it's not just the default, but rather the only option you have.

**Comment by davetcoleman** [comment]
This seems like a surprising limitation in catkin_make - all ROS developers around the world need to make sure there are no target naming conflicts. Like... I have packages that build a ``main`` executable, because I thought they were namespaced by package name. Luckily I use catkin_tools.

Recommendation: add this prefix naming standard to the CMakeLists.txt example that is created when running ``catkin_create_pkg``.

**Comment by wjwwood** [comment]
It's not a limitation of `catkin_make` (which would imply we could somehow improve `catkin_make` to not have this problem), it is in fact a limitation based on CMake's ability to control scope which is exposed by the approach of `catkin_make`.

`catkin_create_pkg` is in `catkin_pkg`, please consider opening a pull request there which updates the templates: https://github.com/ros-infrastructure/catkin_pkg/pulls

I'm going to close this for now, feel free to continue the discuss though.

**Comment by davetcoleman** [comment]
I've contributed to those templates before and would be happy to again, but actually, it already has that functionality. My bad:

> # add_executable(${PROJECT_NAME}_node src/@{name}_node.cpp)

I'll add an explanation to the prefix so people like myself don't just remove it every time I create a new binary.

**Comment by davetcoleman** [comment]
Documented with PR: https://github.com/ros-infrastructure/catkin_pkg/pull/132
