### ISSUE TITLE
Travis failing on master branch

### ISSUE THREAD

**Issue by NikolausDemmel** [catkin/catkin_tools#253]
Not sure why, but it seems travis started failing for the master branch. Something about `sudo apt-get install ...` failing...

**Comment by jbohren** [comment]
I think this might have to do with the configuration of the precise "legacy" builds:
https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future

Note that my updated test harness is not failing:
https://travis-ci.org/catkin/catkin_tools/builds/97122680

**Comment by jbohren** [comment]
This is fixed by #255

**Comment by wjwwood** [comment]
Closing from #255.

**Comment by NikolausDemmel** [comment]
thanks
