### ISSUE TITLE
There should be an index of all known entry_points-based plugins for catkin_tools

### ISSUE THREAD

**Issue by jbohren** [catkin/catkin_tools#258]
It could be managed via PR.

https://github.com/catkin/catkin_tools/pull/241#issuecomment-166922509

**Comment by NikolausDemmel** [comment]
See also https://github.com/catkin/catkin_tools/issues/71

**Comment by jbohren** [comment]
> See also #71

Ah yeah I hadn't seen that. I'll close this, and comment over there.
