### ISSUE TITLE
OS runs out of file descriptors when building workspace with 300+ packages (Large workspace issues)

### ISSUE THREAD

**Issue by mikepurvis** [catkin/catkin_tools#277]
I'm having an interesting issue building a workspace with 300+ packages— at a certain point in the build, everything fails due to the linker having exhausted the open files limit. Representative output:

```
/usr/bin/ld: cannot find /usr/lib/libvtkCommon.so.5.8.0: Too many open files^M
/usr/bin/ld: cannot find /usr/lib/libvtkRendering.so.5.8.0: Too many open files^M
/usr/bin/ld: cannot find /usr/lib/libvtkHybrid.so.5.8.0: Too many open files^M
/usr/bin/ld: cannot find /usr/lib/libvtkCharts.so.5.8.0: Too many open files^M
/usr/bin/ld: cannot find /usr/lib/x86_64-linux-gnu/libopencv_videostab.so.2.4.8: Too many open files^M
/usr/bin/ld: cannot find /usr/lib/x86_64-linux-gnu/libopencv_video.so.2.4.8: Too many open files^M
/usr/bin/ld: cannot find /usr/lib/x86_64-linux-gnu/libopencv_superres.so.2.4.8: Too many open files^M
/usr/bin/ld: cannot find /usr/lib/x86_64-linux-gnu/libopencv_stitching.so.2.4.8: Too many open files^M
/usr/bin/ld: cannot find /usr/lib/x86_64-linux-gnu/libopencv_photo.so.2.4.8: Too many open files^M
/usr/bin/ld: cannot find /usr/lib/x86_64-linux-gnu/libopencv_ocl.so.2.4.8: Too many open files^M
/usr/bin/ld: cannot find /usr/lib/x86_64-linux-gnu/libopencv_objdetect.so.2.4.8: Too many open files^M
/usr/bin/ld: cannot find /usr/lib/x86_64-linux-gnu/libopencv_ml.so.2.4.8: Too many open files^M
...
```

I've tried raising the limit with sysctl, but the issue persists. I can work around it by sourcing the setup file from the failed build, and then creating a new overlaid workspace with just the failed packages—which then builds fine.

Does catkin_tools leak fds? Is this something which the 0.4.0 executor will handle better?

Thanks for any thoughts or pointers.

**Comment by mikepurvis** [comment]
Interesting, looks like this was a legit exhaustion of fds, on some packages which were indeed linking... many things. With the [user fd limit raised](http://askubuntu.com/a/162230/98081), the problem has gone away.

Still odd to me that this worked when built in an overlay but not in the large workspace. Any comment on that?

**Comment by jbohren** [comment]
> Still odd to me that this worked when built in an overlay but not in the large workspace. Any comment on that?

It might be due to the use of the jobserver (which opens additional fds). You could try it with `--no-jobserver`.  Any chance you could post a rosinstall for that workspace?

**Comment by NikolausDemmel** [comment]
Is this with the released version or master?

**Comment by mikepurvis** [comment]
Unfortunately, it's a mix of public and private source, and the stuff that ultimately triggers the errors are pretty proprietary. :|

I'm using catkin_tools as of f92f7bb7780dadc52d11a6cd6cc79ddb915a325c.

**Comment by jbohren** [comment]
@mikepurvis Give the current master a shot. It's got a completely different backend.

**Comment by mikepurvis** [comment]
Done.

```
[build] Warning: Skipping package 'xx' because it has an unknown package build type: "catkin"
```

This is attempting to build a workspace with no context, where catkin is part of the workspace itself.

**Comment by jbohren** [comment]
>```
[build] Warning: Skipping package 'xx' because it has an unknown package build type: "catkin"
```

>This is attempting to build a workspace with no context, where catkin is part of the workspace itself.

Haha, that's cute. I think your `catkin_tools` `master` isn't installed right. Did you re-run `python setup.py develop` or `python setup.py install` again after checking out `master`?

**Comment by mikepurvis** [comment]
Whoops, didn't occur to me that that would be necessary to re-run— works now (though I'm using `sudo python setup.py develop` so I can keep fiddling with it).

I'll have to revert raising the open file limit on my machine in order to test whether the new executor has any change, no promise on timeline for that; feel free to close the ticket if you'd like, until myself or someone else has the issue again.

**Comment by jbohren** [comment]
> Whoops, didn't occur to me that that would be necessary to re-run— works now (though I'm using sudo python setup.py develop so I can keep fiddling with it).

Yeah, the build types are semi-pluggable now, so it needed to the install with references to those modules.

> I'll have to revert raising the open file limit on my machine in order to test whether the new executor has any change, no promise on timeline for that; feel free to close the ticket if you'd like, until myself or someone else has the issue again.

Feel free to do it whenever you have a chance, this can stay open until we've confirmed that it's not an issue with the current master, too.

**Comment by mikepurvis** [comment]
Having tested a bit more, I'm pretty confident the 0.4 executor handles this correctly. If others run into something like this again, they can re-open this ticket or open a new one.
