### ISSUE TITLE
Doesn't build <exec_depend> dependencies

### ISSUE THREAD

**Issue by mikepurvis** [catkin/catkin_tools#278]
When running:

    catkin build foo_package

I only build `<depend>`ed packages, and not `<exec_depend>`ed ones. Is this intentional, or is it a support issue for package format 2?

**Comment by jbohren** [comment]
This looks like bad support for F2: https://github.com/catkin/catkin_tools/blob/c5c88071750c4d66253faf83bbd3c312c9f1576e/catkin_tools/common.py#L207

**Comment by mikepurvis** [comment]
Hmm. I made the following changes and it's still not picking up exec_depends dependencies in a clean workspace: https://github.com/catkin/catkin_tools/commit/ef3064f9aa1fa04230a74ee6c6a6ee5475543cab

**Comment by wjwwood** [comment]
I don't think it has anything to do with format version 2, but instead this: https://github.com/catkin/catkin_tools/issues/148

**Comment by mikepurvis** [comment]
I've commented in #148. Let's continue the discussion there.
