### ISSUE TITLE
roslaunch_add_file_check and exec_depends

### ISSUE THREAD

**Issue by ipa-mdl** [catkin/catkin_tools#285]
I have been experimenting with catkin_tools and roslaunch_add_file_check.
The combination does not work properly in all cases.

I setup a test repository (https://github.com/ipa-mdl/catkin_test.git) with travis testing (https://travis-ci.org/ipa-mdl/catkin_test). It includes a simplified version of the problem and uses the `ros_canopen` repository.

`catkin run_tests` executes in the wrong order: the run of `canopen_test_utils` tests does not include `canopen_motor_node` in its package path: https://travis-ci.org/ipa-mdl/catkin_test/jobs/106789641#L2793

The order can be fixed by adding `canopen_motor_node` as `test_depend`, but this not a generic solution because transitive exec_depends are not covered.
(Think of a launch-only packages..)

`catkin_make` works (https://travis-ci.org/ipa-mdl/catkin_test/jobs/106789639) ; `catkin_make_isolated` works for `ros_canopen`, but not for the simplified version (https://travis-ci.org/ipa-mdl/catkin_test/jobs/106789640).

Did I get something wrong?
Do I have to source devel/setup.bash for some reason?

I think the issue results from two facts:
1. roslaunch_add_file_check needs run/exec_depends as transitive test depends
2. exec_depends (apart form run_depends) are no transitive build depends anymore

A solution could be to include all exec_depends as test_depends for calculating the dependency graph.

**Comment by ipa-mdl** [comment]
Just saw that it's even worse:
The package path includes non existent paths that seem to be merged from two different paths.

The error I was referring to can be found here: https://travis-ci.org/ipa-mdl/catkin_test/jobs/106612268#L2683

**Comment by jbohren** [comment]
@ipa-mdl This might be related to a bug in the inclusion and ordering of run dependencies which has been fixed in a pending PR (#276). Can you try it with that branch (pre-0.4.0-linked-devel)?

**Comment by jbohren** [comment]
I tried your test package with the current master @ 76bfe96, and `catkin run_tests` succeeds for me.

**Comment by ipa-mdl** [comment]
I was not yet able to confirm this, travis fails with some "trollius not found" errors (https://travis-ci.org/ipa-mdl/catkin_test/jobs/107116215).

**Comment by jbohren** [comment]
Take a look at the current Travis configuration for catkin tools to figure out how to install trollius and osrf_pycommon

**Comment by ipa-mdl** [comment]
I had trollius installed, but installing osrf_pycommon as well did the trick :)
It works now and all tests pass, so I will close this issue.

However, the new version displays "Ignored:   1 packages were skipped or are blacklisted."
I guess the skipped package is the meta-package, but I don't know why. Is this intended or a new issue?
