### ISSUE TITLE
Cmake is always forced

### ISSUE THREAD

**Issue by NikolausDemmel** [catkin/catkin_tools#288]
With the latest master, cmake seems to be always forced for my workspace. I believe the following line is the culprit:

https://github.com/catkin/catkin_tools/blob/558d0f4395861a097adc0e877291df67e58212a0/catkin_tools/verbs/catkin_build/cli.py#L367-L368

The build metadata and the context have the same cmake arguments, but otps does not (it has none specified). I guess in case of empty cmake arguments from command line they should be ignored for this test.

**Comment by NikolausDemmel** [comment]
Actually, shouldn't whatever was in opts already have been merged with the context?

**Comment by jbohren** [comment]
This is before build metadata gets updated, but it should be checking if `opts.cmake_args` is `None`.

**Comment by jbohren** [comment]
This should be fixed in #293.

**Comment by NikolausDemmel** [comment]
I have been using the branch of #293 for a while and haven't noticed this since. Closing this. Thanks!
