### ISSUE TITLE
catkin create pkg: should build a format two package.xml

### ISSUE THREAD

**Issue by jack-oquin** [catkin/catkin_tools#292]
The current version builds format one, which should not be recommended for new packages.

**Comment by togaen** [comment]
This would be super useful.

**Comment by jack-oquin** [comment]
Especially considering that ROS2 does not plan to support package format 1.

**Comment by wjwwood** [comment]
I agree, if anyone has anytime to put a pr together that would be great! I'd even consider one that just replaces version 1 with version 2 (no longer supporting generating one with version 1).

**Comment by timonegk** [comment]
`catkin_tools` generates `package.xml` format 2 since `catkin_pkg` version 0.3.7 (late 2017), see https://github.com/ros-infrastructure/catkin_pkg/pull/191.
