### ISSUE TITLE
prefix option to setup.py is broken

### ISSUE THREAD

**Issue by cottsay** [catkin/catkin_tools#294]
Before 9bec9e7bd7dc9d26a4372e14e3911bb175ee04d3, we didn't need to set the `--prefix` option when calling the `setup.py` because bash completion was installed to the right place. Now without the `--prefix` option set to `/usr`, the bash completion directory ends up in `/usr/etc` (which is obviously wrong).

However, we can't set `--prefix` because it breaks the actual setup script. We see this:
```
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --prefix not recognized
```
...when specifying the prefix option to `python setup.py build --prefix=/usr`.

**Comment by wjwwood** [comment]
@cottsay does the `build` verb have the `--prefix` option? If I do `python setup.py install --prefix=...` it seems to work.

**Comment by cottsay** [comment]
Yeah, looks like I had the `--prefix` option on `build`, not `install`. Works fine if I only pass it to `install`.

Sorry for the noise.

**Comment by wjwwood** [comment]
It's ok, I think though you shouldn't have to pass it. I think we need to fallback to `sys.prefix` when prefix is not given on the command line. I'm looking at that now.
