### ISSUE TITLE
 File I/O issues with 0.4.0.

### ISSUE THREAD

**Issue by mikepurvis** [catkin/catkin_tools#309]
Getting some weird error messages with the 0.4.0 candidate (currently 2cb5ddb1faf6e2f85633c191eeae44f7c98abe80):

```
Finished <== rqt_pose_view                 [ 18.8 seconds ]
Starting ==> urdf_parser_plugin

[rqt_srv] ==> '/home/mpurvis/rosbundles/build/clearpath-1.6pre/clearpath-1.6pre_20160404024324/debian/tmp/build/build-sdk/rqt_srv/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' in '/home/mpurvis/rosbundles/build/clearpath-1.6pre/clearpath-1.6pre_20160404024324/debian/tmp/build/build-sdk/rqt_srv'
/home/mpurvis/rosbundles/build/clearpath-1.6pre/clearpath-1.6pre_20160404024324/debian/tmp/build/build-sdk/rqt_srv/build_env.sh: 43: .: Can't open /home/mpurvis/rosbundles/build/clearpath-1.6pre/clearpath-1.6pre_20160404024324/debian/tmp/opt/clearpath/1.6pre/sdk/setup.sh
[rqt_srv] <== '/home/mpurvis/rosbundles/build/clearpath-1.6pre/clearpath-1.6pre_20160404024324/debian/tmp/build/build-sdk/rqt_srv/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' failed with return code '2'
```

I also got another version of this which looked like some kind of bogus permissions problem, also around the `setup.*`/`_setup_util.py` files— it looked a lot like a full disk actually, but this VM's disk has 100+GB free.

It's a large workspace build that succeeds with catkin_tools 0.3.1. Let me know if I can provide additional info to assist.

**Comment by jbohren** [comment]
@mikepurvis Are you sure you're on 0.4.0? 0.4.0 no longer uses `build_env.sh` but your CLI dump is using it. It's also using `==>` and `<==` which have long since been replaced with `>>>` and `<<<`, respectively.

**Comment by mikepurvis** [comment]
Ack, well spotted— I definitely had it checked out, but I think this was another case of failing to re-run `setup.py`. With that fixed, the problem goes away. Sorry for the noise.
