### ISSUE TITLE
out of place package.xml in the devel space

### ISSUE THREAD

**Issue by wjwwood** [catkin/catkin_tools#319]
After following the quick start guide (new documentation): http://catkin-tools.readthedocs.org/en/pre-0.4.0-docs-rebase/quick_start.html

You can see in the generated documentation, and if you reproduce it locally, that the devel space has a `package.xml` in the root, which seems wrong. Is that intended or a bug?

**Comment by wjwwood** [comment]
It's not there if you build a workspace that contains `catkin`. It looks to be related to the "prebuild".

**Comment by jbohren** [comment]
At some point we ended up moving the prebuild package source into the same target as it's private develspace, so those files were getting linked too (including CMakeLists.txt). This is now fixed in #321.

**Comment by jbohren** [comment]
This is fixed with #321.
