### ISSUE TITLE
genjava_message_artifacts not working with catkin build

### ISSUE THREAD

**Issue by samuelba** [catkin/catkin_tools#322]
I recently discovered, that `genjava_message_artifacts` is not working when using `catkin build` instead of `catkin_make`. On the first glance, everything seems to be right, but the generated `.jar` files are empty without the message classes inside.

**Comment by jbohren** [comment]
@samuelba Any chance you could post a minimal workspace that works with `catkin_make`  but not `catkin build `?

**Comment by jbohren** [comment]
Additionally, do you see the same problem with `catkin_make_isolated?`

**Comment by samuelba** [comment]
@jbohren I uploaded here https://github.com/samuelba/catkin_ws_messages a minimal workspace with a single message package `any_msgs`. If I build this workspace with `catkin_make` everything is ok and the `any_msgs-0.1.0.jar` is about 6.5kB and contains all message classes. However, if I build with `catkin build` or `catkin_make_isolated` the generated `any_msgs-0.1.0.jar` is only about 418 bytes and empty.

**Comment by jbohren** [comment]
>  However, if I build with `catkin build` or `catkin_make_isolated` the generated `any_msgs-0.1.0.jar` is only about 418 bytes and empty.

Thanks for following through with this! So since it's not building with `catkin_make_isolated` either, it means that the java message generator is relying on CMake cross-talk in order to function.

**Comment by samuelba** [comment]
So this has to be fixed on the genjava side, if it is fixable at all? Is rosjava still actively maintained/developed or doesn't it make sense to develop Android apps depending on rosjava?

**Comment by jbohren** [comment]
> So this has to be fixed on the `genjava` side, if it is fixable at all? Is rosjava still actively maintained/developed or doesn't it make sense to develop Android apps depending on rosjava?

Well, rosjava is an important thing, @stonier do you have any resources to make `genjava` work with an isolated build layout, or do we need to source it from somewhere else in the community?

**Comment by gaochangyu** [comment]
I found a weird way to fix this. I moved my custom msgs to /opt/ros/indigo/share/ and run genjava_message_artifact in my catkin workspace. Then correct jar files are generated.

**Comment by jbohren** [comment]
> I found a weird way to fix this. I moved my custom msgs to /opt/ros/indigo/share/ and run genjava_message_artifact in my catkin workspace. Then correct jar files are generated.

Wow that's ugly.

**Comment by meyerj** [comment]
The patch proposed in https://github.com/rosjava/genjava/issues/6 solved this issue for me.

**Comment by stonier** [comment]
`catkin_pkg.packages.find_package` is returning funny paths with a smattering of '.''s in them. At any rate, genjava is now robust to this with the patch indicated above, so you can close this issue.
