### ISSUE TITLE
Make migration guide into a tutorial, add CONTRIBUTING.md, jazz up README.md.

### ISSUE THREAD

**Issue by jbohren** [catkin/catkin_tools#325]
As mentioned by @dirk-thomas, we should add a two-step migration so that people try to get their workspaces building with `catkin_make_isolated` before trying `catkin build`.

Additionally, we should detail these steps in CONTRIBUTING.md:
https://github.com/blog/1184-contributing-guidelines

Third, we should add slightly more to README.md on the main page.

**Comment by jack-oquin** [comment]
I like treating isolation as a separate first step, but I suspect introducing ``catkin_make_isolated`` will increase the total cognitive burden for casual users, who are not familiar with CMI.

That said, I don't have a better proposal.

**Comment by jbohren** [comment]
> I like treating isolation as a separate first step, but I suspect introducing catkin_make_isolated will increase the total cognitive burden for casual users, who are not familiar with CMI.

Yeah, I think there's the conceptual migration, and then there's the process you should use to migrate.  I think I'd keep the first two sections the same, but then a "Steps to Migrate" section, which walks users through first building with CMI, and then with CB.

**Comment by jbohren** [comment]
Closing this since I had a chance to implement it over in #326.
