### ISSUE TITLE
Spelling: dependant vs dependent

### ISSUE THREAD

**Issue by scpeters** [catkin/catkin_tools#330]
The spelling `dependant` (with an `a`) is used in several command-line parameters and places within the code (first noticed in the [catkin clean docs](http://catkin-tools.readthedocs.org/en/latest/verbs/catkin_clean.html)). This is the British spelling, which looks weird to me, but it is also not consistent, since the US spelling is used as well on that same page.

**Comment by wjwwood** [comment]
I agree we should find/replace the instances.
