### ISSUE TITLE
forget to upload python-osrf-pycommon on 12.04

### ISSUE THREAD

**Issue by k-okada** [catkin/catkin_tools#336]
Hi

Thanks for updating catkin_tools for 12.04, but you're forgetting to upload osrf-pycommon 
http://packages.ros.org/ros-shadow-fixed/ubuntu/dists/trusty/main/binary-amd64/Packages
http://packages.ros.org/ros-shadow-fixed/ubuntu/dists/precise/main/binary-amd64/Packages

**Comment by k-okada** [comment]
need to upload python-trollius as well

**Comment by wjwwood** [comment]
@tfoote

**Comment by wjwwood** [comment]
@tfoote do you know why it might not be there? I ran the normal release process and precise is in the stdeb file in this repo.

**Comment by tfoote** [comment]
The package for catkin_tools is there, but the missing deb is osrf_pycommon which does not appear to have precise as a target in the stdeb: https://github.com/osrf/osrf_pycommon/blob/master/stdeb.cfg#L4 I think it needs a rerelease for precise. 

For python-trollius I guess we need to fill that backwards.

**Comment by wjwwood** [comment]
Oh, sorry. I misread this as catkin tools was missing. I'll have to see about trollius. I'm not sure I can backport that to precise.

**Comment by wjwwood** [comment]
@k-okada I'm not certain I can backport trollius to 12.04. There are a lot of dependencies missing. Therefore I cannot release a `.deb` of `osrf_pycommon` on precise either.

What I may have to do is release a new version of catkin tools into precise that doesn't include the 0.4.0 changes (basically it will be a re-release of 0.3.1) and therefore does not depend on trollius. For newer versions you'd have to install with pip.

Sorry, I know that's not a very convenient answer, but without being able to backport trollius' `.deb` to precise I can't really fix this properly.

**Comment by wjwwood** [comment]
For anyone interested in trying to package up trollius for precise, this is the error:

From https://launchpadlibrarian.net/254572780/buildlog_ubuntu-precise-i386.python-trollius_2.1~b1-3~ubuntu12.04.1~ppa1_BUILDING.txt.gz
```
The following packages have unmet dependencies:
 sbuild-build-depends-python-trollius-dummy : Depends: dh-python but it is not installable
                                              Depends: openstack-pkg-tools but it is not installable
                                              Depends: python-concurrent.futures but it is not installable
                                              Depends: python3-unittest2 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Those don't seem trivial to resolve. So I'm going to have to decline to provide a `.deb` for precise for 0.4.0. I'll look into options for getting a working `.deb` version on precise again, but I won't be updating it afterwards for precise.

**Comment by jbohren** [comment]
@wjwwood It looks like `openstack-pkg-tools`, `python-concurrent.futures`, `python3-unittest2` are all available on 12.04, but `dh-python` is not available (though the LibreOffice PPA does provide it).

**Comment by wjwwood** [comment]
@jbohren I've tried to backport `dh-python` to precise in my PPA as well. Let's see if it builds. If so, then I can retry `python-trollius`.

**Comment by wjwwood** [comment]
The next missing dep is `libpython3-stdlib`: http://packages.ubuntu.com/search?keywords=libpython3-stdlib

That one looks more problematic. I'll look at the libreoffice PPA again.

**Comment by jbohren** [comment]
@wjwwood Do we need to support Python3 on 12.04?

**Comment by jbohren** [comment]
@wjwwood Specifically, the Python3 that comes through the debs on 12.04 is Python3.2, which I'm not even sure we've ever tested before.

**Comment by wjwwood** [comment]
No, but conditioning on it just for precise is not easy to do... I'd rather fix or craft custom deb that resets things to 0.3.1 and never update it again.

**Comment by wjwwood** [comment]
Next problem: `openstack-pkg-tools`, `python-concurrent.futures`, and `python3-unittest2` are only in `precise-backports`. I'll have to figure out if I can use the backports in my PPA or if I have to backport them myself. Two of those are even Python3 agnostic (so they're a problem even if I could easily cut out Python 3 support). 🐰 ⚫

**Comment by k-okada** [comment]
even if I installed `python-concurrent.futures` from `precise-backports` I have next problem running catkin. may be we have to put 0.3.x to precise and ask to use pip for people willing to use new feature.
```
$ catkin 
Traceback (most recent call last):
  File "/usr/bin/catkin", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: futures
```

**Comment by wjwwood** [comment]
Yeah, I've run into about three more issues trying to get it working in my PPA. I think I'm going to push `0.3.1` back to 12.04.

**Comment by wjwwood** [comment]
Ok, I've got a new deb released for `catkin_tools` on precise (and other platforms that we cannot support due to the lack of a trollius backport). I can now install it on my precise VM.

I'm going to close this for now. If someone can produce a trollius backport for precise that works then I'll consider adding precise back to the list of support platforms for the newer versions of `catkin_tools`.

**Comment by jbohren** [comment]
@wjwwood Any chance we could revisit this and try to get the dependencies into your PPA? I don't think Precise backports is going to change much, it might be easy enough to just copy the dependencies into the PPA.

**Comment by wjwwood** [comment]
> Yeah, I've run into about three more issues trying to get it working in my PPA.

I tried that already and ran into issues at each dependency.

> If someone can produce a trollius backport for precise that works then I'll consider adding precise back to the list of support platforms for the newer versions of `catkin_tools`.

If you want to try and make the backport, then that's fine, but I don't have time to do so. You can make a PPA easily. That way I don't have to be a blocker. I'm on vacation this week, and probably won't have time for this afterwards.

**Comment by jbohren** [comment]
> If you want to try and make the backport, then that's fine, but I don't have time to do so. You can make a PPA easily. That way I don't have to be a blocker.

Alright, I might go ahead and try that at some point, then.

**Comment by wjwwood** [comment]
Since both 12.04 and the ROS distributions that use them are EOL, I'm going to close this. If someone actually has time to look into, we can consider reopening it.
