### ISSUE TITLE
did not exist immediately  when smaller limit-status-rate

### ISSUE THREAD

**Issue by k-okada** [catkin/catkin_tools#337]
when we set very small number on the limit-status-rate, the catkin build did not return until the system shows next status info, for example;
```
catkin build --limit-status-rate 0.01
```
will wait for 100 sec, even if you compile a single empty package.

**Comment by jbohren** [comment]
I assume this is with 0.4.0?

**Comment by k-okada** [comment]
Yes

--
◉ Kei Okada

2016/04/19 20:27、Jonathan Bohren <notifications@github.com> のメッセージ:

**Comment by jbohren** [comment]
@k-okada This should be fixed with #344.

**Comment by jbohren** [comment]
@k-okada I reopened this because #344 introduced a regression.
