### ISSUE TITLE
builds broken due to KeyError in controllers.py

### ISSUE THREAD

**Issue by defunctzombie** [catkin/catkin_tools#347]
[//]: # (Thank you for reporting an issue for catkin_tools!)

Builds do not work due to a KeyError in controllers.py

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: `Linux 3.19.0-56-generic #62~14.04.1-Ubuntu SMP Fri Mar 11 11:03:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: 2.7.6
* Version of catkin_tools: 0.4.1
* ROS Distro: indigo (on ubuntu trusty)

### Build / Run Issue

Builds via `catkin build` do not work because of a logic issue exposed in https://github.com/catkin/catkin_tools/commit/69ecfce4a7e6f881bcf8ed64701374924fcc56a9.

Builds fail with the following error at random times:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/catkin_tools/execution/controllers.py", line 615, in run
    del active_stages[event.data['job_id']]
KeyError: 'launch_task'
```

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [ ] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [ ] I did  not `read this`

I did not try catkin_make

### Expected Behavior

The build to not fail with a threading issue.

[//]: # (Please describe what you expected or think should happen.)

### Actual Behavior

Fails at stated above.

[//]: # (Please describe what actually happens.)

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)

### Steps to Reproduce the Issue

Run `catkin build` using version 0.4.1 of the tools. I don't have a project I can link to but here is why it fails.

The above referenced commit exposes some incorrect logic in the run handler. My understanding of the logic in the run handler is that it first gets an event from the queue (blocking or non-blocking depending) and then proceeds to process the event.

I believe that the commit exposed the issue because it changed the behavior of `self.show_active_status` which then cases the `if` statement with the `continue` block to execute. This continue statement makes the while loop skip the actual handling of the event that may have come off the queue and thus the STARTED_STAGE event is not processed and when the FINISHED_STAGE event is invoked (and processed) it cannot delete the key cause STARTED_STAGE was skipped.

The original commit that introduced the continue statement is here:
https://github.com/catkin/catkin_tools/commit/28f0cf1f3ba5320c52832db4fbca1cab722357ba

I think it makes sense to revert the logic (or rework the continue) and ship a new 0.4.2 release cause right now I suspect you will get a lot of complaints once users upgrade to a new version of the tools and builds no longer work.

P.S. This is written based on my quick read of the code and it may be that the above assessment is not 100% accurate on the logic but I can confirm that we cannot build using 0.4.1 tools and when we revert that commit (the one that changed the if statement logic) it at least allows us to build. The continue statement overall looks out of place to me inside of the loop.

[//]: # (Please give a series of command-line commands which cause the problem.)
[//]: # (Include a checkout URI for the workspace so that we can reproduce the issue.)
[//]: # (If we can't reproduce it on our own machines, we can't fix it!)

**Comment by wjwwood** [comment]
Looking at #344, it's not immediately obvious to me how to fix it. So, sorry @k-okada I'll have to revert that until we time to re-evaluate the fix.

**Comment by defunctzombie** [comment]
@wjwwood Also note that the `continue` statement is the thing fundamentally out of place and that #344 seems like it might have just exposed it in more situations.

**Comment by wjwwood** [comment]
@defunctzombie I agree, but this is the best I can do at the moment. We'll do a proper fix within a few days. https://github.com/catkin/catkin_tools/pull/348

**Comment by wjwwood** [comment]
Ok, `0.4.2` is out. We'll try to address the issue properly asap. Thanks for the detailed report.

**Comment by defunctzombie** [comment]
Thanks for the super fast fix! Will it also land in the ros Debian/Ubuntu
repos?

**Comment by wjwwood** [comment]
Should already be in the apt repositories.

**Comment by jbohren** [comment]
> I believe that the commit exposed the issue

Nice catch, @defunctzombie. You're absolutely correct. See #351 for a fix for both problems.

**Comment by defunctzombie** [comment]
On further review, I am not sure if my assessment of the continue statement is correct. The statement is only in the `except` part of the logic which shouldn't cause messages to be skipped (unless I don't fully understand how the `except Empty` logic is suppose to work.

**Comment by jbohren** [comment]
> On further review, I am not sure if my assessment of the continue statement is correct. The statement is only in the `except` part of the logic which shouldn't cause messages to be skipped (unless I don't fully understand how the `except Empty` logic is suppose to work.

@defunctzombie Well, the continue statement was definitely the problem, just not exactly in the way you thought it was.

Initially, we had:

```bash
While True
  If active status
    Try
     Pop non blocking
    Except empty
      Print status
      If status rate is nonzero # This was almost always true, so we never get to "Handle event" without an event
        Wait a bit
        Continue
      Endif
    Endtry
  Else
    Try
      Pop blocking
    Except empty
      Break
    Endtry
  Endif

  Handle event
Endwhile
```

In 95556318fe9b8b53dbcdfd6e66ede0fdd5df9ba9, I decoupled the loop rate from the print rate, so that the print rate doesn't prevent the loop from running. This resulted in:

```bash
While True
  If active status
    Try
     Pop non blocking
    Except empty
      Print status
      If status is stale # This was often false for status rates lower than 100Hz, so it was possible to get to "Handle Event" without a new event
        Wait a bit
        Continue
      Endif
    Endtry
  Else
    Try
      Pop blocking
    Except empty
      Break
    Endtry
  Endif

  Handle event # At this point, event might have been set by a previous iteration of the loop, which will get handled again, and crash in the way you saw
Endwhile
```

So the problem wasn't that messages were getting skipped, the problem was that messages were being handled *multiple times*. So to fix it, 52c58ab50b9e6c781b1b7e5d1f17e45987ab30ff makes it so there's no way to get to the event handling without a new event:

```bash
While True
  If active status
    Try
     Pop non blocking
    Except empty # no event to handle, we should always continue from this block
      If stale status
        Print status
      Else
        Wait a bit
      Endif
      Continue
    Endtry
  Else
    Try
      Pop blocking
    Except empty
      Break
    Endtry
  Endif

  Handle event
Endwhile
```

**Comment by jbohren** [comment]
@defunctzombie This should be resolved (and has been released). If you want to keep discussing it, feel free to reopen. Thanks again!

**Comment by stuglaser** [comment]
Thanks for the quick fix jon!
