### ISSUE TITLE
LD_LIBRARY_PATH stripped when explicitly extending workspace

### ISSUE THREAD

**Issue by mikepurvis** [catkin/catkin_tools#350]
### System Info

* Operating System: Linux 3.16.0-69-generic x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 2.7.6
* Version of catkin_tools: 0.4.2-1
* ROS Distro: indigo

### Build / Run Issue

I'm building two catkin workspace inside a dpkg-buildpackage environment, one which extends the other. The first one (which starts with `catkin`) succeeds, and then the second one bails out right at the beginning, with the first thing it tries to build, which is `catkin_tools_prebuild` for a linked develspace or the first actual package with isolated develspace.

Error is:

```
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

**Comment by jbohren** [comment]
@mikepurvis Does this happen if both workspaces have `merged` or `isolated` develspaces?

**Comment by mikepurvis** [comment]
Both workspaces are merged installspaces, and the second extends the first's installspace. I'm working on a MWE for you.

**Comment by mikepurvis** [comment]
The issue is that the `--extend` option is wiping out LD_LIBRARY_PATH. On the first build, I get:

```
echo ${LD_PRELOAD}
libfakeroot-sysv.so
echo ${LD_LIBRARY_PATH}
/usr/lib/x86_64-linux-gnu/libfakeroot:/usr/lib64/libfakeroot:/usr/lib32/libfakeroot:
```

After sourcing that, I still have LD_PRELOAD set, but now:

```
echo $LD_LIBRARY_PATH
/home/mpurvis/rosbundles/build/clearpath-1.7pre/clearpath-1.7pre_20160420205118/debian/tmp/opt/clearpath/1.7pre/demo1/lib
```

So I can no longer find the specified library. I can probably hack around this by mangling the path post-sourcing, but this is something catkin_tools needs to handle better.

**Comment by jbohren** [comment]
> The issue is that the `--extend` option is wiping out `LD_LIBRARY_PATH`.

So if you build with an implicit underlay do you see the same problem?

**Comment by mikepurvis** [comment]
I believe so, yeah (but I don't see the problem with 0.3.x, with either explicit or implicit extension).

**Comment by jbohren** [comment]
> but I don't see the problem with 0.3.x, with either explicit or implicit extension

Alright. It would be great to have a complete out-of-the-box repro, when you have time to put it together. I suspect the resultspace loading is cleaning out variables that should be making it through.

**Comment by mikepurvis** [comment]
Here you are:

```
git clone --recursive https://github.com/mikepurvis/catkin_tools_350.git
cd catkin_tools_350
./run  # happiness
git clean -fdx
fakeroot ./run  # sadness
```
