### ISSUE TITLE
elapsed time does not format correctly when when greater than one hour and minutes are zero

### ISSUE THREAD

**Issue by tfoote** [catkin/catkin_tools#356]
### System Info

* Operating System: Linux linaro-alip 4.4.6-linaro-lt-qcom #1 SMP PREEMPT Wed Apr 13 14:39:16 UTC 2016 aarch64 GNU/Linux
* Python Version: Python 2.7.9
* Version of catkin_tools: 0.4.2
* ROS Distro: Kinetic/Indigo hybrid

### Build / Run Issue

The timer in the bottom left corner counting elapsed time. 

When it gets to 1 hours, for the first minute it counts `hh:ss.s` where it should be `hh:mm:ss.s` when `mm` should read `00`

### Expected Behavior

It should not collapse the zero minutes field out of site. 

### Steps to Reproduce the Issue

Run a build for an hour and look at the displayed elapsed time between the 60th and 61st minute of running.

**Comment by jbohren** [comment]
> Run a build for an hour and look at the displayed elapsed time between the 60th and 61st minute of running.

@tfoote I really hope you weren't staring at it for each of the first 60 minutes.

**Comment by tfoote** [comment]
But it's so colorful I can't help but watch it....

Good luck reproducing it quickly ;-)

**Comment by NikolausDemmel** [comment]
There is always `date -s "..."` :sunglasses:

**Comment by jbohren** [comment]
> Good luck reproducing it quickly ;-)

See #357 :dizzy_face:


```python
from catkin_tools.common import format_time_delta_short as ftds
ftds(3601)
```
