### ISSUE TITLE
Migration guide steps fail in indigo and 14.04

### ISSUE THREAD

**Issue by miguelprada** [catkin/catkin_tools#363]
### System Info

* Operating System: `Linux xxx 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `Python 2.7.6`
* Version of catkin_tools: `catkin_tools 0.4.2`
* ROS Distro: `indigo`

### Build / Run Issue

* [ ] Works with `catkin_make`
* [x] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [ ] I did  not `read this`

### Expected Behavior

Configure and build packages in workspace using the different methods suggested in the [step-by-step instructions][step-by-step] in the migration guide.

### Actual Behavior

When following the instructions in the migration guide, step 1 and 3 don't work as expected:
- `catkin_make` does not accept the `--devel` argument to change the develspace
- `catkin_make_isolated` works fine as described in the guide
- `catkin config` complains about the `--suffix` argument

Please note that these are not issues related to my workspace/packages or the catkin tool itself, since everything configures and builds fine if I get rid of the build/develspace suffixes and just run the commands one by one deleting the products by hand in between. This issue is related to the migration guide, instead.

Also, the checkmarks above are meaning to indicate the validity of the CLI arguments as they appear in the guide. As said, compilation succeeds with the three tools if avoiding incorrect args.

### Steps to Reproduce the Issue

Follow the [step-by-step instructions][step-by-step] in the migration guide.

[step-by-step]: http://catkin-tools.readthedocs.io/en/latest/migration.html#step-by-step-migration

**Comment by jbohren** [comment]
@miguelprada Thanks for the feedback and detailed report! The documentation should be fixed, now, after b5c5458.
