### ISSUE TITLE
Problem with exec_depend

### ISSUE THREAD

**Issue by VictorLamoine** [catkin/catkin_tools#364]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: Linux M6700 3.16.0-70-generic #90~14.04.1-Ubuntu SMP Wed Apr 6 22:56:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux 
* Python Version: Python 2.7.6
* Version of catkin_tools: 
```
catkin_tools 0.4.2 (C) 2014-2016 Open Source Robotics Foundation
catkin_tools is released under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
---
Using Python 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
```
* ROS Distro: indigo

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [X] Works with `catkin_make`
* [X] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`

### Actual Behavior
```                                                                                                                                   
[build] Updating package table.                                                                                                                                                       
Abandoned <<< fanuc_motion             [ Depends on unknown jobs: fanuc ]
```

https://github.com/InstitutMaupertuis/fanuc_motion/issues/2#issuecomment-215702117
[//]: # (Please describe what actually happens.)

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)

### Steps to Reproduce the Issue

```bash
mkdir catkin_test catkin_test/src
cd catkin_test/src
catkin_init_workspace
cd ..
git clone https://github.com/InstitutMaupertuis/fanuc_motion.git src/fanuc_motion
git clone https://github.com/ros-industrial/fanuc.git src/fanuc
catkin build
```

### Comments
- Happens only when the `fanuc` repository is here.
- Commenting `exex_depend` on `fanuc`, `fanuc_experimental`, `industrial_core` makes compilation work again ([package.xml](https://github.com/InstitutMaupertuis/fanuc_motion/blob/indigo-devel/package.xml#L24-L26)).
- Also see https://github.com/InstitutMaupertuis/fanuc_motion/issues/2.

What is wrong with these `exec_depend` tags?

**Comment by jbohren** [comment]
> What is wrong with these exec_depend tags?

The `fanuc`, `fanuc_experimental`, and `industrial_core` packages are all metapackages, so you can't depend on them unless your package is also a metapackage.

[REP-140](http://www.ros.org/reps/rep-0140.html#metapackage) says this on metapackages:
> They cannot be used for catkin builds and compile nothing themselves. 

This is not the first time we've seen this problem reported, however, so I think it's a usability problem with `catkin build`. See #366 for a continued focused discussion.
