### ISSUE TITLE
Behavior of catkin build when it comes to auto-generated dynamic_reconfigure config files

### ISSUE THREAD

**Issue by spmaniato** [catkin/catkin_tools#367]
Not sure if this is an actual "issue" or simply a question about how the behavior of `catkin build` differs from `catkin_make` when it comes to `dynamic_reconfigure`. But I thought it was worth brining it up / documenting it. I've already found a way around it btw (see "Actual Behavior")

### System Info

* Operating System: Darwin (Mac OS X El Capitan 10.11.4)
* Python Version: 2.7.11 (Homebrew Python)
* Version of catkin_tools: 0.4.0
* ROS Distro: indigo

### Build Issue

* [x] Works with `catkin_make`
* [x] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [ ] I did  not `read this`

I was migrating from `catkin_make` and had one C++ package fail even though it worked with `catkin_make_isolated --merge` (as per the migration guide). That package, let's call it `company_action_name`, defined a dynamic reconfigure file, let's call it `ActionName.cfg` (modeled after [`MoveBase.cfg`](https://github.com/ros-planning/navigation/blob/jade-devel/move_base/cfg/MoveBase.cfg)). The `generate` command looked like this:

```python
exit(gen.generate("action_name", "action_name_node", "ActionName"))
```

Similarly, the `CMakeLists.txt` file for the package `company_action_name` declared the following dependency:

```cmake
add_dependencies(action_name action_name_gencfg)
```

This setup resulted in the following error when using `catkin build`:

```bash
path/to/repo/company_action_name/include/company_action_name/action_name.h:64:10:
fatal error: 'action_name/ActionNameConfig.h' file not found
#include <action_name/ActionNameConfig.h>
         ^
```

### Actual Behavior

In order to make this work with `catkin build`, I had to change the namespace of the autogenerated config files from `action_name` to `company_action_name` (i.e., same as the package name):

```python
exit(gen.generate("company_action_name", "action_name_node", "ActionName"))
```

```cmake
add_dependencies(action_name company_action_name_gencfg)
```

And of course change the C++ source code as well. For example:

```cpp
#include <company_action_name/ActionNameConfig.h>
// ...
dynamic_reconfigure::Server<company_action_name::ActionNameConfig> *dsrv_;
```

### Steps to Reproduce the Issue

[//]: # (Please give a series of command-line commands which cause the problem.)
[//]: # (Include a checkout URI for the workspace so that we can reproduce the issue.)
[//]: # (If we can't reproduce it on our own machines, we can't fix it!)

TODO, if deemed necessary

**Comment by jbohren** [comment]
@spmaniato Thanks for the detailed report! We'll add this as a test case and go from there.

**Comment by jbohren** [comment]
@spmaniato I was reading this over again, and if this is in the `company_action_name` package, then your generate line is actually in error:

> ```python
exit(gen.generate("action_name", "action_name_node", "ActionName"))
```

The `ParameterGenerator.generate()` function's first argument isn't just the namespace, but it's supposed to be the package name, as shown on the [wiki](http://wiki.ros.org/dynamic_reconfigure/Tutorials/HowToWriteYourFirstCfgFile#dynamic_reconfigure.2BAC8-Tutorials.2BAC8-HowToWriteYourFirstCfgFile.2BAC8-catkin.CA-9cb5076ac680c37f95dd942c3e9dc2cd9cac6954_21) and in the [source code](https://github.com/ros/dynamic_reconfigure/blob/master/src/dynamic_reconfigure/parameter_generator.py#L284). I'm sort of surprised your package as described before modification works with `catkin_make` or `catkin_make_isolated` either. The first option to`generate()` is actually not even used to generate the include directory [as seen here](https://github.com/ros/dynamic_reconfigure/blob/master/src/dynamic_reconfigure/parameter_generator_catkin.py#L256).

**Comment by spmaniato** [comment]
Hmm, you're right. How did that ever work 😮 

It looks like `catkin build` is behaving correctly then. Feel free to close the issue 😁 
I may comment in the future if end up reverting the fixes and doing some detective work 🔎

**Comment by jbohren** [comment]
> Hmm, you're right. How did that ever work 😮 

Haha, alright, well I'm glad `catkin build` helped you fix your package! I'm going to close this for now then. Feel free to re-open it if there's anything else you need related to this issue.
