### ISSUE TITLE
QtCreator 4 removes necessary entries from CMakeCache

### ISSUE THREAD

**Issue by simonschmeisser** [catkin/catkin_tools#369]
### System Info

* Operating System: Linux sisbox 4.4.0-22-generic #39-Ubuntu SMP Thu May 5 16:53:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

* Python Version: Python 2.7.11+
* Version of catkin_tools:
catkin_tools 0.4.2 (C) 2014-2016 Open Source Robotics Foundation
catkin_tools is released under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
---
Using Python 2.7.11+ (default, Apr 17 2016, 14:00:29) [GCC 5.3.1 20160413] 
* ROS Distro: kinetic
QtCreator: qtcreator -version

Qt Creator 3.6.83 based on Qt 5.6.0

  Android 3.6.83 Support for deployment to and execution on Android Devices.
  AutoTest 3.6.83 Auto Test plugin.
  AutotoolsProjectManager 3.6.83 Autotools project integration.
  BareMetal 3.6.83 This plugin adds a target for bare metal development.
  Bazaar 3.6.83 Bazaar integration.
  Beautifier 3.6.83 Format source files with the help of beautifiers like AStyle, uncrustify or clang-format.
  BinEditor 3.6.83 Binary editor component.
  Bookmarks 3.6.83 Bookmarks in text editors.
  CMakeProjectManager 3.6.83 CMake support.
  CVS 3.6.83 CVS integration.
  ClangStaticAnalyzer 3.6.83 ClangStaticAnalyzer Plugin.
  ClassView 3.6.83 Class View component.
  ClearCase 3.6.83 ClearCase integration.
  CodePaster 3.6.83 Codepaster plugin for pushing/fetching diff from server.
  Core 3.6.83 The core plugin for the Qt IDE.
  CppEditor 3.6.83 C/C++ editor component.
  CppTools 3.6.83 Tools for analyzing C/C++ code.
  Debugger 3.6.83 Debugger integration.
  Designer 3.6.83 Qt Designer integration.
  DiffEditor 3.6.83 Diff editor component.
  EmacsKeys 3.6.83 The main idea behind this plugin is to provide additional actions a typical emacs user would expect. It doesn't claim to provide full emacs emulation. The following actions are available:
 - Movement [C-f, C-b, C-n, C-p, M-f, M-b, C-a, C-e, M-<, M->]
 - Mark-based selection [C-SPC, C-x C-x]
 - Cut/copy/yank (doesn't provide kill ring feature) [M-w, C-w, C-y]
 - Kill actions, which interact properly with clipboard [C-k, M-d, C-d]
 - Scrolling (half of the screen, keeps cursor visible) [C-v, M-v]
 - Insert new line and indent [C-j]

IMPORTANT: Actions are not bound to any key combinations by default. You can find them under 'EmacsKeys' section in keyboard shortcuts settings.

Also it's worth mentioning that EmacsKeys plugin forces disabling of menu mnemonics by calling Qt's qt_set_sequence_auto_mnemonic function with false argument. Many of the english menu mnemonics get into the way of typical emacs keys, this includes: Alt+F (File), Alt+B (Build), Alt+W (Window). It's a temporary solution, it remains until there is a better one.
  FakeVim 3.6.83 VI-style keyboard navigation.
  GLSLEditor 3.6.83 Editor for GLSL.
  GenericProjectManager 3.6.83 Generic support.
  Git 3.6.83 Git integration.
  Help 3.6.83 Help system.
  ImageViewer 3.6.83 Image Viewer component.
  Ios 3.6.83 Support for deployment to and execution on iOS Devices.
  Macros 3.6.83 Macros in text editors.
  Mercurial 3.6.83 Mercurial integration.
  ModelEditor 3.6.83 Graphical modeling with structured diagrams.
  Perforce 3.6.83 Perforce integration.
  ProjectExplorer 3.6.83 ProjectExplorer framework that can be extended with different kind of project types.
  PythonEditor 3.6.83 Editor and file creation wizards for Python. Example plugin for QtCreator API demonstration.
  QbsProjectManager 3.6.83 QBS support.
  QmakeAndroidSupport 3.6.83 Android support for qmake project manager.
  QmakeProjectManager 3.6.83 Provides project type for Qt/QMake .pro files and tools.
  QmlDesigner 3.6.83 Visual Designer for QML files.
  QmlJSEditor 3.6.83 Editor for QML and JavaScript.
  QmlJSTools 3.6.83 Tools for analyzing Qml/JS code.
  QmlProfiler 3.6.83 Qml Profiler Plugin.
  QmlProfilerExtension 3.6.83 Qml Profiler Extension Plugin.
  QmlProjectManager 3.6.83 Qt Quick support
  Qnx 3.6.83 Adds support for QNX to Qt Creator.
  QtSupport 3.6.83 Provides support code for build systems.
  RemoteLinux 3.6.83 Support for deployment to and execution on a remote Linux host.
  ResourceEditor 3.6.83 Editor for qrc files.
  Subversion 3.6.83 Subversion integration.
  TaskList 3.6.83 Use .tasks-files to populate the Issues view.
  TextEditor 3.6.83 Text editor framework and the implementation of the basic text editor.
  Todo 3.6.83 Adds pane that lists all TODO, FIXME, etc. entries in comments.
  UpdateInfo 3.6.83 Displays Update-Infos for Qt Installer Framework-based Updaters.
  Valgrind 3.6.83 Valgrind Plugin.
  VcsBase 3.6.83 Version Control System Base Plugin.
  Welcome 3.6.83 Default Welcome Screen Plugin.
  WinRt 3.6.83 Helper for Windows Runtime projects.

(C) 2016 The Qt Company Ltd

### Build / Run Issue

I setup a catkin workspace (ws), works as normal. Now I open the CMakeLists.txt of one package and set ws/build/package as build dir. This used to work in QtCreator 3.6. I change some stuff in the code and hit compile.

### Expected Behavior

I expect the code to be compiled into ws/devel/ ..., but it ends up in ws/build/package/devel

### Actual Behavior

I expect the code to be compiled into ws/devel/ ..., but it ends up in ws/build/package/devel

QtCreator used to use make for building, now it does
    cmake --build . --target all

if I subsequently call
    catkin build
it will still compile to ws/build/package/devel

removing ws/build/package and calling
    catkin build

will restore everything (ie the binaries in ws/devel are updated)

**Comment by jbohren** [comment]
@simonschmeisser Can you please tell us if you also experience this problem with `catkin_make` and `catkin_make_isolated --merge`?

**Comment by simonschmeisser** [comment]
I haven't used those for a while and actually my code does not compile using them. Do you have a simple test workspace I could use?

**Comment by jbohren** [comment]
> I haven't used those for a while and actually my code does not compile using them. Do you have a simple test workspace I could use?

So you have been building with the `catkin build` command until now?

**Comment by simonschmeisser** [comment]
Sorry if that has not been clear, I switched from QtCreator 3.5/3.6 to QtCreator 4.0 Beta. The version of catkin_tools stayed the same.

**Comment by jbohren** [comment]
> Yes, always catkin build. Sorry if that has not been clear, I switched from QtCreator 3.5/3.6 to QtCreator 4.0 Beta. The version of catkin_tools stayed the same.

Ok, and what was the build command that you used with QtCreator 3.x?

**Comment by NikolausDemmel** [comment]
It looks like I have the same problem. This happens when the cmake project is loaded in qtcreator and qtcreator re-runs cmake. The issue might be with the way it calls qmake. At least for this instance this causes cmake to drop the cache and re-run itself, resulting in an unset devel prefix.

```
Running "/usr/bin/cmake /home/den2pal/work/ros_ws/src/ethzasl_msf/msf_updates '-GCodeBlocks - Unix Makefiles' -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++ -DQT_QMAKE_EXECUTABLE:STRING=/usr/bin/qmake-qt4" in /home/den2pal/work/ros_ws/build/msf_updates.
-- Using CATKIN_DEVEL_PREFIX: /home/den2pal/work/ros_ws/devel/.private/msf_updates
-- Using CMAKE_PREFIX_PATH: /home/den2pal/work/ros_ws/devel;/opt/ros/indigo
-- This workspace overlays: /home/den2pal/work/ros_ws/devel;/opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/den2pal/work/ros_ws/build/msf_updates/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- Using these message generators: gencpp;genlisp;genpy
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/bin/g++
CMAKE_CXX_COMPILER= /usr/bin/g++

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/den2pal/work/ros_ws/build/msf_updates/devel
-- Using CMAKE_PREFIX_PATH: /home/den2pal/work/ros_ws/devel;/opt/ros/indigo
-- This workspace overlays: /home/den2pal/work/ros_ws/devel;/opt/ros/indigo
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/den2pal/work/ros_ws/build/msf_updates/test_results
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- Using these message generators: gencpp;genlisp;genpy
CMake Warning at /home/den2pal/work/ros_ws/src/catkin/cmake/catkin_package.cmake:414 (message):
  catkin_package() include dir
  '/home/den2pal/work/ros_ws/build/msf_updates/devel/include' should be
  placed in the devel space instead of the build space
Call Stack (most recent call first):
  /home/den2pal/work/ros_ws/src/catkin/cmake/catkin_package.cmake:98 (_catkin_package)
  CMakeLists.txt:26 (catkin_package)


-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    QT_QMAKE_EXECUTABLE


-- Build files have been written to: /home/den2pal/work/ros_ws/build/msf_updates
```

In qtcreator 3.6 it seems that the call to cmake is different (not containing CMAKE_CXX_COMPILER probably). The only output show in 3.6 for the same package is:

```
-- Using CATKIN_DEVEL_PREFIX: /home/den2pal/work/ros_ws/devel/.private/msf_updates
-- Using CMAKE_PREFIX_PATH: /home/den2pal/work/ros_ws/devel;/opt/ros/indigo
-- This workspace overlays: /home/den2pal/work/ros_ws/devel;/opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/den2pal/work/ros_ws/build/msf_updates/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- Using these message generators: gencpp;genlisp;genpy
-- Configuring done
-- Generating done
-- Build files have been written to: /home/den2pal/work/ros_ws/build/msf_updates
```

I don't think this is really something that needs to be changed on catkin_tool side.

**Comment by simonschmeisser** [comment]
Ah, so there we go. There are some new features in QtCreator 4 to use compiler and Qt version defined by a Kit (QtCreator setting) in CMake projects. This seems to remove the special catkin information.

if we look at your output above, it boils down to:

```
Running "/usr/bin/cmake /home/den2pal/work/ros_ws/src/ethzasl_msf/msf_updates '-GCodeBlocks - Unix Makefiles' -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++ -DQT_QMAKE_EXECUTABLE:STRING=/usr/bin/qmake-qt4" in /home/den2pal/work/ros_ws/build/msf_updates.
-- Using CATKIN_DEVEL_PREFIX: /home/den2pal/work/ros_ws/devel/.private/msf_updates
-- Using CMAKE_PREFIX_PATH: /home/den2pal/work/ros_ws/devel;/opt/ros/indigo
-- This workspace overlays: /home/den2pal/work/ros_ws/devel;/opt/ros/indigo
.........
-- catkin 0.6.18
-- Using these message generators: gencpp;genlisp;genpy
-- Configuring done
```

**You have changed variables that require your cache to be deleted.**
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/bin/g++
CMAKE_CXX_COMPILER= /usr/bin/g++

```
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
....
-- Using CATKIN_DEVEL_PREFIX: /home/den2pal/work/ros_ws/build/msf_updates/devel
-- Using CMAKE_PREFIX_PATH: /home/den2pal/work/ros_ws/devel;/opt/ros/indigo
-- This workspace overlays: /home/den2pal/work/ros_ws/devel;/opt/ros/indigo
........
-- Using these message generators: gencpp;genlisp;genpy
CMake Warning at /home/den2pal/work/ros_ws/src/catkin/cmake/catkin_package.cmake:414 (message):
  catkin_package() include dir
  '/home/den2pal/work/ros_ws/build/msf_updates/devel/include' should be
  placed in the devel space instead of the build space
Call Stack (most recent call first):
  /home/den2pal/work/ros_ws/src/catkin/cmake/catkin_package.cmake:98 (_catkin_package)
  CMakeLists.txt:26 (catkin_package)


-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    QT_QMAKE_EXECUTABLE


-- Build files have been written to: /home/den2pal/work/ros_ws/build/msf_updates

```

**Comment by NikolausDemmel** [comment]
Exactly, so it seems we need to "fix" qtcreator to at least optionally not pass `CMAKE_CXX_COMPILER` to cmake. As far as I know for the next version of QtCreator there are plans to generate Kits from existing cmake build directories on the fly (in case none of the existing kits match the choises identified from cmake cache). Maybe in this mode the additional cmake calls would not need to contain CMAKE_CXX_COMPILER, or maybe only if it was explicitly set in the cache already before opening with qtcreator.

I guess as a workaround, one could simply configure catkin_tools to pass that variable to cmake itself in the first place, i.e. in my case it would amount to adding `-DCMAKE_CXX_COMPILER= /usr/bin/g++` catkin_tools cmake-args.

Ill give this a shot and report back.

**Comment by simonschmeisser** [comment]
Good idea, this works:
`catkin build --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++`

Longer Version:
`catkin clean --build`
`catkin build --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++
`
open QtCreator, select CMakeLists.txt of your package, select ws/build/package as build dir, enjoy :)

**Comment by NikolausDemmel** [comment]
It turns out that qtcreator can already do that. Just clone the Kit that you were using, call it "catkin_tools" or similar, and remove the CMAKE_CXX_COMPILER argument from the "CMake Configuration" settings.

**Comment by simonschmeisser** [comment]
Cloning also works, but just removing CMAKE_CXX_COMPILER from the default kit doesn't. I will add some lines to the wiki soon if nobody beats me at it.

**Comment by NikolausDemmel** [comment]
Really? I wonder why that wouldnt work.

 +1 for Wiki update

**Comment by simonschmeisser** [comment]
It always adds the CMAKE_CXX_COMPILER and QMAKE.. part even though its not in the variables list. A bug in QtCreator I guess.

**Comment by kopp** [comment]
Just as a note to people not well used to catkin: You can also set the `CMAKE_CXX_COMPILER` flag in your catkin configuration using, so that you do not have to add it to each call of `catkin build`.

    catkin config --cmake-args -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++ --

By the way I guess that you can disable qtcreator from setting `CMAKE_CXX_COMPILER`:

1. Go to Tools -> Options
1. Select _Build & Run_ on the left and tab _Kits_
1. Select your kit (normally called _Default_) and at the very bottom _CMake Configuration_.  Hit _Change..._ besides that and remove the offending line with the `CMAKE_CXX_COMPILER`.

If you build the package first using `catkin build`, it seems to work with QtCreator 4.0.0 and catkin 0.4.2.

**Comment by NikolausDemmel** [comment]
> By the way I guess that you can disable qtcreator from setting CMAKE_CXX_COMPILER

Yes, as reported above this also works for me and @simonschmeisser. Thanks for the more detailed instructions!

@simonschmeisser reported that he had trouble with this when using the /Default/ Kit, so maybe you need to also create a new Kit that is not /Default/ and use that for your catkin projetcs.

In any case IMHO using a Kit with removed `CMAKE_CXX_COMPILER` argument is the preferred method as opposed to setting catkin's `cmake-args` configuration, but either should work.

**Comment by andrejpan** [comment]
Hey,
did somebody tried debugging with `Qt Creator`? Run mode works well, but with debug I just get message like this:
```
Debugging starts
Debugging has finished
```

**Comment by kopp** [comment]
@andrejpan actually I did not have problems with debugging.  Normally, I first build the project using catkin, then open it in QtCreator, work on it, and then debug it with QtCreator.  Did you make sure to select the correct target to debug?  You can select the binary to get debugged on the computer symbol on the bottom left (over the green debug-arrows).  I assume did you start roscore etc accordingly?

**Comment by andrejpan** [comment]
@kopp you are not building ros packages with qt-creator? You fix the code with qt-creator and then run catkin tools again at the console? I selected right binary to run and my roscore is also running. How did you select folders for normal build and debug build? Is the same or different?

**Comment by simonschmeisser** [comment]
@andrejpan I usually run catkin once with

    catkin build --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++

and then open the projects in QtCreator. Now I select ReleaseWithDebugInfo (and unselect all other) and set the build dir to CATKIN_WS/build/PACKAGENAME. Now I can use both run and debug in QtCreator. It seems to be helpful to run catkin tools from time to time again

**Comment by andrejpan** [comment]
Hey, 

I still having problems. I [recoded](https://youtu.be/HIsDU3bBlec) how I set up development environment. Does somebody has idea, what I am doing wrong?

**Comment by kopp** [comment]
@andrejpan When I hit _Configure Project_ I do not _accept_/_apply_.  As far as I recall, the text is a little different from what you recorded when you open the project for the first time; try to purge your qtcreator config (CMakeLists.txt.user in the project and stuff in ~/.config/QtProject).

Can you add some `std::cout` in your code, compile in QtCreator and run your program once in the terminal and once using QtCreator's _run_ button -- if you see the `cout` stuff in the latter and not in the former, this indicates that the binary is built in the wrong directory...

Have you successfully debugged other programs (hello world) with QtCreator?

**Comment by andrejpan** [comment]
Hey, 

I apologize for delayed response, but I did not work on the project for last 2 weeks. I removed `~/.config/QtProject` and debugging mode is working now. It has few glitches(I think), but I need to see what exactly is wrong. Tnx!

**Comment by kopp** [comment]
@andrejpan welcome.  Happy hacking.

**Comment by kopp** [comment]
@simonschmeisser  is this still considered an open issue for `catkin_tools`?  It looks to me like it is a QtCreator problem.  Did you add the necessary instructions in the wiki?  Maybe I overlooked it...

**Comment by andrejpan** [comment]
[This](http://wiki.ros.org/IDEs#catkin_tools-1) entry should determinately updated.

**Comment by kopp** [comment]
I asked for permission; I hope I'll be allowed to do it in the next few days ...

**Comment by simonschmeisser** [comment]
the issue is only open as far as updating documentation should still be done. I'll be on vacation starting a few hours ago (in theory) so I can only do it in about three weeks.

**Comment by kopp** [comment]
I just updated the wiki.  Could you please check it and if you (at least @simonschmeisser) are satisfied with it, could you please close this ticket?

**Comment by simonschmeisser** [comment]
Thanks a lot, looks good to me!
