### ISSUE TITLE
consider abandoning packages as an error

### ISSUE THREAD

**Issue by rhaschke** [catkin/catkin_tools#371]
catkin build should return an error code when packages are abandoned. See #370.
If catkin build is used in CI, abandoning packages should be signaled as an error.

**Comment by tulku** [comment]
Or at least make this optional, like the current `--continue-on-failure`, a new option could be added to fail on abandoned packages.

**Comment by mikepurvis** [comment]
Also related is #447, silently skipping packages it doesn't know how to build.

**Comment by simonschmeisser** [comment]
Is there a workaround available? Has this been fixed?
