### ISSUE TITLE
catkin build package_name can't link shared libraries that are in catkin_ws/devel/lib correctly

### ISSUE THREAD

**Issue by yuzhangbit** [catkin/catkin_tools#385]
### There are some problems with catkin build command.

 ROS package1 generated a shared library and I install it into catkin_ws/devel/ . Package2 links the shared lib generated by package1.  When I run catkin build package2, it reports 

```
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "package1"
......................
```

If I run catkin build package1(no error when building package1), then run catkin build package2.  I got 

```
/usr/bin/ld: cannot find -lpackage1
collect2: error: ld returned 1 exit status

```

If I delete catkin_ws/build and catkin_ws/devel and run catkin_make in catkin_ws, there is no error at all. 

It seem catkin build can't handle dependences of ros packages and can't link shared libs correctly. 
### System Info
- Operating System: Ubuntu 14.04 LTS
- Python Version: Python 2.7.6
- Version of catkin_tools: catkin_tools 0.4.2 [GCC 4.8.2]
- ROS Distro: Indigo

**Comment by jbohren** [comment]
@yuzhangbit Can you post the example packages that you think should be building?
