### ISSUE TITLE
warnings and errors from stderr should be output on stderr (instead of stdout)

### ISSUE THREAD

**Issue by rhaschke** [catkin/catkin_tools#396]
The compact output summary of catkin tools is really great.
However, using it with qtcreator (> 4), poses the issue, that warnings and errors are no longer on stderr, but they are redirected to stdout by catkin_tools. For this reason, qtcreator doesn't parse those warnings/errors anymore to allow for source-code hyperlinking.

Could you consider to output warnings/errors on stderr again?

**Comment by dseifert** [comment]
This is not only an issue with QtCreator 4.x but also earlier versions. And I would expect also other IDEs. It was also shortly discussed in #157. A quick work-around is to simply pipe the entire `catkin build` output to stderr - the result is not pretty, but it usually works well enough.

**Comment by rhaschke** [comment]
Ping.

**Comment by wjwwood** [comment]
@rhaschke I was looking at these this week. I'm still trying to figure out how https://github.com/catkin/catkin_tools/pull/400 and https://github.com/catkin/catkin_tools/pull/362 and https://github.com/catkin/catkin_tools/pull/362#issuecomment-215560993 all fit together.

**Comment by wjwwood** [comment]
Closed by #424.
