### ISSUE TITLE
list: fill out documentation

### ISSUE THREAD

**Issue by wjwwood** [catkin/catkin_tools#4]
The `catkin list` command needs documentation, but the stub is already there:

https://github.com/catkin/catkin_tools/blob/master/docs/commands/catkin_list.rst

It probably isn't worth working on this until this issue is addressed: https://github.com/catkin/catkin_tools/issues/3

**Comment by jbohren** [comment]
The current live documentation has more details on `catkin list` usage. Is there anything else that needs to be documented?

**Comment by wjwwood** [comment]
http://catkin-tools.readthedocs.org/en/latest/verbs/catkin_list.html looks sufficient.
