### ISSUE TITLE
Coverage builds?

### ISSUE THREAD

**Issue by dustingooding** [catkin/catkin_tools#401]
### System Info

* Operating System: Linux bacon 3.13.0-95-generic #142~precise1-Ubuntu SMP Fri Aug 12 18:20:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 2.7.3
* Version of catkin_tools: catkin_tools 0.4.2 (C) 2014-2016 Open Source Robotics Foundation
* ROS Distro: hydro

(I also have a machine running 14.04+Indigo.)

### Build / Run Issue

I would like to run some code coverage analysis on a package in my workspace.  I've read lots of stuff on the web about setting build flags, using CMake macros/build types, etc.  I'm more asking what the right way to do this is with catkin_tools.

I tried simply using `catkin config --cmake-args -DCMAKE_BUILD_TYPE=Coverage`, but the executables (unit tests mainly) didn't generate any gcov output.  I tried manually adding build flags with `catkin config --cmake-args -DCMAKE_C_FLAGS=-fprofile-arcs -DCMAKE_C_FLAGS=-ftest-coverage -DCMAKE_EXE_LINKER_FLAGS=-fprofile-arcs -DCMAKE_EXE_LINKER_FLAGS=-ftest-coverage` and it didn't help.  (Also, I had a hard time with the syntax there, is that how you should add multiple CMAKE_C_FLAGS values? When I use quotes, they get stripped and weird errors pop up ("source directory "/path/to/catkin_tools_prebuild/-ftest-coverage"" does not exist").  Neither of these (and more) helped generate useful information.

At the end of the day, I want to build executables (unit tests, etc) with coverage options such that they generate data I can analyze using lcov.  How should I go about that?  Is that supported easily with catkin_tools?  Not easily?  Thanks for the help and your time.

**Comment by wjwwood** [comment]
You're adding the arguments the correct way, i.e. anything that comes after `--cmake-args` is captured and sent to cmake until a bare `--` is encountered.

In my opinion, this has nothing to do with catkin_tools, i.e. it doesn't need explicit support for coverage. If you figure out how to add coverage to your unit tests with a single CMake project, then catkin_tools will allow you to pass arguments to your package's cmake and/or make calls.

If you run into unhelpful errors when trying to use the CLI, please open an issue about that with specific details.

In my opinion, you'll likely need to have a custom CMake option like `MY_PKG_DO_COVERAGE`, and then in your CMake code conditionally add the appropriate flags. It may be possible to achieve what you want without changing the cmake code of the project but I haven't done that before.

**Comment by dustingooding** [comment]
Ok, thanks!  If I figure out a good way, I'll post back here for documentation purposes.

**Comment by romainreignier** [comment]
@dustingooding Did you manage to use gcov with catkin_tools?

**Comment by fabianoboril** [comment]
Yes, this would be interesting to know, even +2 years later

**Comment by romainreignier** [comment]
For your information @fabianoboril , I have been using the package [code_coverage](https://github.com/mikeferguson/code_coverage) by @mikeferguson and it works even with catkin-tools.
