### ISSUE TITLE
Backwards compatibility for catkin_install_python

### ISSUE THREAD

**Issue by wxmerkt** [catkin/catkin_tools#410]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: Linux xxx 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 2.7.6
* Version of catkin_tools: catkin_tools 0.4.2
* ROS Distro: indigo

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [x] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge` (didn't verify)
* [ ] Works with `catkin build` (doesnt work!)
* [ ] Works with `catkin build -p1` (didn't verify)

### Expected Behavior

[//]: # (Please describe what you expected or think should happen.)

The scripts specified in the macro should be installed to the BIN destination.

### Actual Behavior

[//]: # (Please describe what actually happens.)

Nothing happens - no scripts are installed.

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)

### Steps to Reproduce the Issue

[//]: # (Please give a series of command-line commands which cause the problem.)
[//]: # (Include a checkout URI for the workspace so that we can reproduce the issue.)
[//]: # (If we can't reproduce it on our own machines, we can't fix it!)

Any ROS package which uses catkin_install_python, e.g. the husky/husky packages.

```bash

```

**Comment by wxmerkt** [comment]
Replacing ``catkin_install_python`` with ``install(PROGRAMS scripts/my_script DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})`` also doesn't create a ``bin`` folder in the install workspace.

A similar issue can be observed for ``catkin_add_env_hooks``

**Comment by wjwwood** [comment]
This is a feature of catkin itself: https://github.com/ros/catkin/blob/5a7f61d594a56ca4b3ae1705e64140e9f29e0bd7/cmake/catkin_install_python.cmake

Which lives in [ros/catkin](https://github.com/ros/catkin/). I'm not sure I follow what your issue is, but I think it would have to be solved in catkin proper, not in the `catkin build` tool which is what is in the repository.

Can you confirm whether or not this works with `catkin_make` but not `catkin build` and provide more details about why you think this might be the case. I don't have enough information here to help you.

**Comment by wxmerkt** [comment]
Hi William,
Thanks for your response. The installation worked with ``catkin_make`` but not ``catkin build`` - the package in question was a husky-related package. I've since switched back to ``catkin_make`` for that particular robot/changed the CMakeLists.
