### ISSUE TITLE
Unable to use PKG_CONFIG_PATH to locate external non-catkin libraries

### ISSUE THREAD

**Issue by jlack1987** [catkin/catkin_tools#413]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: `Linux link01 3.18.9-rt5-ihmc7-generic #ihmc7-Ubuntu SMP PREEMPT RT Tue Nov 10 18:52:05 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `2.7.6`
* 0.4.2
* ROS Distro: `indigo`

### Build

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [x] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge` - didn't try
* [ ] Works with `catkin build` - doesn't work
* [ ] Works with `catkin build -p1` - didn't try
* [ ] I did  not `read this`- did read 👍 

### Expected Behavior
When running `catkin build`, my custom `PKG_CONFIG_PATH` is getting ignored/wiped instead of appended to. If there are external, non-catkin things I would like to link against and I rely on this path to do it, I am unable to do so with catkin tools.

### Actual Behavior
I get build errors because my `PKG_CONFIG_PATH` isn't correct.

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)

### Steps to Reproduce the Issue
Have a catkin package that rely's on the PKG_CONFIG_PATH to navigate to some external library that is not created by a catkin pkg, then just `catkin build`.

```bash

```

**Comment by wjwwood** [comment]
I can't think of any reason that this would happen. I know it's a lot to ask if your project is not completely open, but can you suggest a concrete set of packages which display this issue, either your workspace or a minimal example that you can make up to demonstrate the issue? Thanks.

**Comment by scpeters** [comment]
@jlack1987 I noticed that `gazebo_ros_pkgs` [uses pkg-config to find stuff for gazebo_plugins](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/kinetic-devel/gazebo_plugins/CMakeLists.txt#L33-L41). Can you reproduce this failure when building that package?

**Comment by jlack1987** [comment]
Hey @scpeters, i'm really not sure. This has been a long time ago and I don't really remember very much about it. Also I think I opened this issue when working with the MIT SRC group on Valkyrie and it was something with their software not ours.

**Comment by scpeters** [comment]
Ok, maybe we can close this issue for now then and re-open it if we get more information.
