### ISSUE TITLE
catkin -h is not showing `install` information

### ISSUE THREAD

**Issue by matt3o** [catkin/catkin_tools#420]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: `Linux matteo-notebook 4.8.12-040812-generic #201612020431 SMP Fri Dec 2 09:33:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `Python 2.7.12`
* Version of catkin_tools: `catkin_tools 0.4.2`
* ROS Distro: `kinetic`

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

No build / run issue.

### Expected Behavior

`catkin -h` should list `catkin install` which is an alias of `catkin config --install`. Tried to find information on how to install the packages but found now way to do so in the main catkin help. 

[//]: # (Please describe what you expected or think should happen.)

### Actual Behavior

Nothing is shown,`catkin -h  | grep install` returns nothing.

### Steps to Reproduce the Issue

[//]: # (Please give a series of command-line commands which cause the problem.)
[//]: # (Include a checkout URI for the workspace so that we can reproduce the issue.)
[//]: # (If we can't reproduce it on our own machines, we can't fix it!)

```bash
catkin -h
```

**Comment by wjwwood** [comment]
Aliases are just that. As an alias it does not show up in the help, but does show up when you do `catkin --list-aliases`.

There's no good (or easy) way to capture the aliases in the doc strings. I'm going to close this as wontfix, but if anyone has an idea on how to improve this, you all can continue the conversation here.

**Comment by wjwwood** [comment]
Also see https://catkin-tools.readthedocs.io/en/latest/cheat_sheet.html#configuring-workspaces for how to turn on install.
