### ISSUE TITLE
catkin build fails when build space on a different device due to cross-device link

### ISSUE THREAD

**Issue by guihomework** [catkin/catkin_tools#422]
### System Info

* Operating System: Ubuntu 16.04  Linux brutus 4.8.1-tf1-ll #1 SMP PREEMPT Thu Oct 13 11:18:32 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 2.7.12
* Version of catkin_tools: catkin_tools 0.4.3
* ROS Distro: kinetic

### Build / Run Issue

* [ ] Works with `catkin_make`  --build <some folder on another device>
* [ ] Works with `catkin_make_isolated --merge` --build <some folder on another device>
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`

In an NFS mounted home (slow) I have a catkin workspace explicitly extending /opt/ros/kinetic, with only robot_state_publisher repo cloned inside (for the test). 
devel space is on the NFS mounted home, but I would like to have the build space on a local SSD (fast)
hence setting --build-space to point to another folder on *another device*

This fails due to cross-device hardlinks even in the non link-devel mode

### Expected Behavior

build should work at least when using --merge-devel or --isolate-devel

### Actual Behavior
```
Errors     << robot_state_publisher:cmake /homes/myname/work/dev/catkin_test_ws/logs/robot_state_publisher/build.cmake.000.log                                                  
CMake Error at /opt/ros/kinetic/share/catkin/cmake/atomic_configure_file.cmake:8 (file):
  file RENAME failed to rename
    /media/local-fast/myname/build/catkin_test_ws/robot_state_publisher/atomic_configure_file
  to
    /homes/myname/work/dev/catkin_test_ws/devel/_setup_util.py

  because: Invalid cross-device link

Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/catkin_generate_environment.cmake:40 (atomic_configure_file)
  /opt/ros/kinetic/share/catkin/cmake/all.cmake:170 (catkin_generate_environment)
  /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:5 (find_package)

Traceback (most recent call last):
  File "/media/local-fast/myname/build/catkin_test_ws/robot_state_publisher/catkin_generated/generate_cached_setup.py", line 22, in <module>
    code = generate_environment_script('/homes/myname/work/dev/catkin_test_ws/devel/env.sh')
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/catkin/environment_cache.py", line 61, in generate_environment_script
    output = subprocess.check_output([env_script, sys.executable, '-c', python_code])
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
CMake Error at /opt/ros/kinetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python
  "/media/local-fast/myname/build/catkin_test_ws/robot_state_publisher/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/all.cmake:186 (safe_execute_process)
  /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:5 (find_package)
```

### Steps to Reproduce the Issue

```bash
mkdir -p catkin_test_ws/src
cd catkin_test_ws; catkin init
catkin config --extend /opt/ros/kinetic
catkin config --merge-devel --build-space <someotherdevice/mybuildfolder>
cd src; git clone https://github.com/ros/robot_state_publisher
catkin build
```

**Comment by wjwwood** [comment]
There are some modes where symbolic linking would be required, but since you're using `--merge-devel` I don't think it should require them. I could be wrong though, so it's hard for me to tell if this is unintentional (a bug) or something we rely on purposely in which case avoiding the symlink would be an enhancement.

I don't have time to look into this at the moment, but obviously a work around would be to use the local hdd for everything and copy it to your home folder when you want to back it up.

**Comment by adrienbarral** [comment]
Hello, I had the same problem, and I think (but I haven't really tested it) that this can solve the problem.

Problem is in file /opt/ros/kinetic/share/catkin/cmake/atomic_configure_file.cmake line 8. 
This file is : 
```
function(atomic_configure_file input output)
  set(atomic_file "${CMAKE_BINARY_DIR}/atomic_configure_file")
  configure_file("${input}" "${atomic_file}" ${ARGN})
  get_filename_component(output_path ${output} PATH)
  if(NOT EXISTS ${output_path})
    file(MAKE_DIRECTORY ${output_path})
  endif()
  file(RENAME "${atomic_file}" "${output}")
endfunction()
```

Line 8 a file is "renamed". But rename signature of FILE method in cmake works only on the same volume. On different volume we have to copy file... So the following patch solve this problem : 

```
function(atomic_configure_file input output)
  set(atomic_file "${CMAKE_BINARY_DIR}/atomic_configure_file")
  configure_file("${input}" "${atomic_file}" ${ARGN})
  get_filename_component(output_path ${output} PATH)
  if(NOT EXISTS ${output_path})
    file(MAKE_DIRECTORY ${output_path})
  endif()
  message("Copying from " "${atomic_file}" " to " "${output}" )
  file(COPY "${atomic_file}" DESTINATION "${output_path}")
  file(RENAME "${output_path}/atomic_configure_file" "${output}")
endfunction()
```
I just replaced the RENAME by a copy and a rename.

**Comment by jbohren-hbr** [comment]
> @jbohren-hbr I wonder how your fix https://github.com/honeybee-robotics-forks/catkin/blob/kinetic-devel/cmake/atomic_configure_file.cmake can work since DESTINATION of COPY must be a directory, it completely messed up my devel space, creating directories instead of files...

Yeah, that sounds about right. I was just sketching it out in order to preserve the atomicity. I hadn't tested it yet, sorry for the accidental deception.

**Comment by guihomework** [comment]
I was keeping an eye on this issue, and not using a fast build space, but @rhaschke  told me it should work now, so gave my step by step instructions a try, and it now even works with linked space on  catkin_tools 0.4.5.
closing
