### ISSUE TITLE
Error of catkin build: Unable to find source space ....

### ISSUE THREAD

**Issue by Happyjie1993** [catkin/catkin_tools#425]
catkin build unable to find source space if I made a directory within a sub-directory of the main folder, such as /home/computername/sub_folder/my_workspace/src. But it works well if I put the workspace folder just under the main folder like  /home/computername/my_workspace/src. It's strange since I never have met this problem before (and catkin_make always works well). So what's wrong with my system setting? 

Here is some of my system configuration information:
Operating System: Ubuntu 16.04 Linux
Python Version: Python 2.7.11
ROS Distro: kinetic

**Comment by wjwwood** [comment]
Please give a list of exact commands, copy-pasting the entire terminal output if possible. I can't tell what the issue is based on the information you've given me.

**Comment by oscar-lima** [comment]
I had a similar problem, the following solved my problem:

rm -rf ~/.catkin_tools

According to the catkin tools [documentation](https://catkin-tools.readthedocs.io/en/latest/verbs/catkin_init.html) : The only constraint is that catkin workspaces cannot contain other catkin workspaces.

**Comment by Happyjie1993** [comment]
@wjwwood thanks and sorry for replaying so late. The command I used and the entire terminal output are:

happy@happy-X550JK:~/workspaces$ cd test2
happy@happy-X550JK:~/workspaces/test2$ mkdir src
happy@happy-X550JK:~/workspaces/test2$ cd src 
happy@happy-X550JK:~/workspaces/test2/src$ catkin_init_workspace
Creating symlink "/home/happy/workspaces/test2/src/CMakeLists.txt" pointing to "/opt/ros/kinetic/share/catkin/cmake/toplevel.cmake"
happy@happy-X550JK:~/workspaces/test2/src$ cd ..
happy@happy-X550JK:~/workspaces/test2$ catkin build
[build] Error: Unable to find source space `/home/happy/workspaces/src`


If I put the test2 folder within the home folder directly, every thing goes OK as following output shows:

happy@happy-X550JK:~$ cd test1
happy@happy-X550JK:~/test1$ mkdir src
happy@happy-X550JK:~/test1$ cd src
happy@happy-X550JK:~/test1/src$ catkin_init_workspace
Creating symlink "/home/happy/test1/src/CMakeLists.txt" pointing to "/opt/ros/kinetic/share/catkin/cmake/toplevel.cmake"
happy@happy-X550JK:~/test1/src$ cd ..
happy@happy-X550JK:~/test1$ catkin build
------------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/kinetic
Workspace:                   /home/happy/test1
------------------------------------------------------
Source Space:       [exists] /home/happy/test1/src
Log Space:         [missing] /home/happy/test1/logs
Build Space:        [exists] /home/happy/test1/build
Devel Space:        [exists] /home/happy/test1/devel
Install Space:      [unused] /home/happy/test1/install
DESTDIR:            [unused] None
------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
------------------------------------------------------
[build] No packages were found in the source space '/home/happy/test1/src'
[build] No packages to be built.
[build] Package table is up to date.                                           
Starting  >>> catkin_tools_prebuild                                            
Finished  <<< catkin_tools_prebuild                [ 1.4 seconds ]             
[build] Summary: All 1 packages succeeded!                                     
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: None.                                                     
[build]   Failed:    None.                                                     
[build] Runtime: 1.5 seconds total.

So is there anything goes bad to my system setting? One more thing I want to stress is that I never have met this problem before. It seems to happen suddenly.

**Comment by Happyjie1993** [comment]
@wjwwood thanks and sorry for replaying so late. The command I used and the entire terminal output are:

happy@happy-X550JK:~/文档/FVIIS/build$ man rm
happy@happy-X550JK:~/文档/FVIIS/build$ cd /home/happy/workspaces
happy@happy-X550JK:~/workspaces$ clear

happy@happy-X550JK:~/workspaces$ cd test2
happy@happy-X550JK:~/workspaces/test2$ mkdir src
happy@happy-X550JK:~/workspaces/test2$ cd src 
happy@happy-X550JK:~/workspaces/test2/src$ catkin_init_workspace
Creating symlink "/home/happy/workspaces/test2/src/CMakeLists.txt" pointing to "/opt/ros/kinetic/share/catkin/cmake/toplevel.cmake"
happy@happy-X550JK:~/workspaces/test2/src$ cd ..
happy@happy-X550JK:~/workspaces/test2$ catkin build
[build] Error: Unable to find source space `/home/happy/workspaces/src`
happy@happy-X550JK:~/workspaces/test2$


If I put the test2 folder within the home folder directly, every thing goes OK as following output shows:


happy@happy-X550JK:~$ cd test1
happy@happy-X550JK:~/test1$ mkdir src
happy@happy-X550JK:~/test1$ cd src
happy@happy-X550JK:~/test1/src$ catkin_init_workspace
Creating symlink "/home/happy/test1/src/CMakeLists.txt" pointing to "/opt/ros/kinetic/share/catkin/cmake/toplevel.cmake"
happy@happy-X550JK:~/test1/src$ cd ..
happy@happy-X550JK:~/test1$ catkin build
------------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/kinetic
Workspace:                   /home/happy/test1
------------------------------------------------------
Source Space:       [exists] /home/happy/test1/src
Log Space:         [missing] /home/happy/test1/logs
Build Space:        [exists] /home/happy/test1/build
Devel Space:        [exists] /home/happy/test1/devel
Install Space:      [unused] /home/happy/test1/install
DESTDIR:            [unused] None
------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
------------------------------------------------------
[build] No packages were found in the source space '/home/happy/test1/src'
[build] No packages to be built.
[build] Package table is up to date.                                           
Starting  >>> catkin_tools_prebuild                                            
Finished  <<< catkin_tools_prebuild                [ 1.4 seconds ]             
[build] Summary: All 1 packages succeeded!                                     
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: None.                                                     
[build]   Failed:    None.                                                     
[build] Runtime: 1.5 seconds total.

So is there anything goes bad to my system setting? One more thing I want to stress is that I never have met this problem before. It seems to happen suddenly.

**Comment by Happyjie1993** [comment]
@wjwwood thanks and sorry for replaying so late. The command I used and the entire terminal output are:

happy@happy-X550JK:~/workspaces$ cd test2
happy@happy-X550JK:~/workspaces/test2$ mkdir src
happy@happy-X550JK:~/workspaces/test2$ cd src 
happy@happy-X550JK:~/workspaces/test2/src$ catkin_init_workspace
Creating symlink "/home/happy/workspaces/test2/src/CMakeLists.txt" pointing to "/opt/ros/kinetic/share/catkin/cmake/toplevel.cmake"
happy@happy-X550JK:~/workspaces/test2/src$ cd ..
happy@happy-X550JK:~/workspaces/test2$ catkin build
[build] Error: Unable to find source space `/home/happy/workspaces/src`


If I put the test2 folder within the home folder directly, every thing goes OK as following output shows:

happy@happy-X550JK:~$ cd test1
happy@happy-X550JK:~/test1$ mkdir src
happy@happy-X550JK:~/test1$ cd src
happy@happy-X550JK:~/test1/src$ catkin_init_workspace
Creating symlink "/home/happy/test1/src/CMakeLists.txt" pointing to "/opt/ros/kinetic/share/catkin/cmake/toplevel.cmake"
happy@happy-X550JK:~/test1/src$ cd ..
happy@happy-X550JK:~/test1$ catkin build
------------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/kinetic
Workspace:                   /home/happy/test1
------------------------------------------------------
Source Space:       [exists] /home/happy/test1/src
Log Space:         [missing] /home/happy/test1/logs
Build Space:        [exists] /home/happy/test1/build
Devel Space:        [exists] /home/happy/test1/devel
Install Space:      [unused] /home/happy/test1/install
DESTDIR:            [unused] None
------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
------------------------------------------------------
[build] No packages were found in the source space '/home/happy/test1/src'
[build] No packages to be built.
[build] Package table is up to date.                                           
Starting  >>> catkin_tools_prebuild                                            
Finished  <<< catkin_tools_prebuild                [ 1.4 seconds ]             
[build] Summary: All 1 packages succeeded!                                     
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: None.                                                     
[build]   Failed:    None.                                                     
[build] Runtime: 1.5 seconds total. 

So is there anything goes bad to my system setting? One more thing I want to stress is that I never have met this problem before. It seems to happen suddenly.

**Comment by Happyjie1993** [comment]
@oscar-lima Thank your so much~. Your method solved my problem! The .catkin_tools(a hidden folder) and the other workspaces can't be placed in the same folder (unluckily it happens to me :( ).

**Comment by Happyjie1993** [comment]
@wjwwood Thank you and sorry for replaying so late. My problem is solved by using @oscar-lima 's method~~

**Comment by ebimor** [comment]
thank you very much Oscar-Lima :) you saved my day.

**Comment by JosePlaza92** [comment]
Thank you Oscar. I had similar problem and your solution worked.

**Comment by kheaactua** [comment]
I got this problem when I was attempting to build tf2 on Windows bash (using conan.) Switching to the normal windows shell resolved the problem.

**Comment by AshfakYeafi** [comment]
@oscar-lima   thanks for the solution.

**Comment by JuJingYiLove** [comment]
你是我爹
