### ISSUE TITLE
catkin build hangs on circular run depdendency

### ISSUE THREAD

**Issue by jspricke** [catkin/catkin_tools#429]
### System Info

* Operating System: Linux PDEMUC1CML000024 4.4.0-59-generic #80~14.04.1-Ubuntu SMP Fri Jan 6 18:02:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 2.7.6
* Version of catkin_tools: 0.4.3
* ROS Distro: indigo

### Build / Run Issue

* [ ] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`

### Expected Behavior
``[build] Error: The workspace packages have a circular dependency``
or working build.

### Actual Behavior

`catkin build` hanging.

### Steps to Reproduce the Issue

```bash
. /opt/ros/indigo/setup.bash
mkdir -p /tmp/test_ws/src
cd /tmp/test_ws
catkin init
cd src
catkin create pkg pkg_a --catkin-deps pkg_b
catkin create pkg pkg_b --catkin-deps pkg_a
sed -i '/build_depend/d' pkg_*/package.xml
catkin build
```

**Comment by wjwwood** [comment]
Reproducible example provided in https://github.com/catkin/catkin_tools/issues/439#issue-211495939

**Comment by wjwwood** [comment]
@jspricke if you have a chance, could you confirm https://github.com/catkin/catkin_tools/pull/440 fixes this for you? Thanks.

**Comment by 130s** [comment]
@geoffreychiou (wanna share version info?) just ran into the similar issue today.

**Comment by Miliks** [comment]
Hi, i have a similar problem some version forward. Raspberry Pi 4 with 4G RAM, unìbuntu 18.04 64Bit, with ROS Melodic installed, i was trying to do catkin build following Moveit tutorial for Franka and it hungs up forever with no errors. TNot only terminal, but Raspberry is not reacting on anything, so i have to powerdown it not really greacefuly.
Any idea what could be a problem?
Thanks in advance!

**Comment by jspricke** [comment]
@Miliks this issue is already closed, please open a new ticket and fill out the template.
