### ISSUE TITLE
Official debs out of date?

### ISSUE THREAD

**Issue by mikepurvis** [catkin/catkin_tools#435]
Unsure if I'm just looking in the wrong spot, but the ones at packages.ros.org are still 0.4.0-2:

http://packages.ros.org/ros/ubuntu/pool/main/c/catkin-tools/

**Comment by wjwwood** [comment]
It's `python-catkin-tools`. I don't know where `catkin-tools` came from...

**Comment by wjwwood** [comment]
http://packages.ros.org/ros/ubuntu/pool/main/p/python-catkin-tools/

**Comment by wjwwood** [comment]
@tfoote can we remove the `catkin-tools` debs from our repository? I don't even know how I would make those if I wanted to (stdeb handles the names...).

**Comment by mikepurvis** [comment]
Oh of course, how silly of me. Thanks!

**Comment by tfoote** [comment]
removed from buildfarm repos. it will propogate in the next upload/sync
