### ISSUE TITLE
Circular exec dependency causes catkin_tools to hang

### ISSUE THREAD

**Issue by mikepurvis** [catkin/catkin_tools#439]
When I have a workspace with a circular `build_depend`, and I attempt to `catkin build` it, I get the expected behaviour:

```
[build] Found '2' packages in 0.0 seconds.                                                                           
[build] Error: The workspace packages have a circular dependency, and cannot be built. Please run `catkin list --deps` to determine the problematic package(s).
```

However, when my workspace has a circular `exec_depend`, the build step simply hangs:

```
[build] Found '2' packages in 0.0 seconds.                                                                           
[build] Updating package table.                                                                                      
```

This is with catkin_tools 0.4.4.

Minimum working example: https://github.com/mikepurvis/catkin_tools_439

**Comment by wjwwood** [comment]
Duplicate of https://github.com/catkin/catkin_tools/issues/429?

**Comment by mikepurvis** [comment]
Oh blah, so it is.
