### ISSUE TITLE
pip installing catkin_tools doesn't install trollius

### ISSUE THREAD

**Issue by jlack1987** [catkin/catkin_tools#445]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: `uname -a` - 4.8.0-41-generic #44~16.04.1-Ubuntu SMP Fri Mar 3 17:11:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: `python --version` - 3.5
* Version of catkin_tools: `catkin --version` OR *Git revision* - 0.4.4
* ROS Distro: `echo $ROS_DISTRO` - kinetic

### Build / Run Issue
Run issue

### Expected Behavior
[//]: # (Please describe what you expected or think should happen.)
I would just expect it to configure the catkin workspace to extend `/opt/ros/kinetic` and use the install space.

### Actual Behavior

[//]: # (Please describe what actually happens.)
For context I have been doing all this in a docker. To reproduce, the docker ros:kinetic-ros-base will do. The following snippet shows the problem i'm having.
```
$ catkin config --extend /opt/ros/$ROS_DISTRO/ --install
Traceback (most recent call last):
  File "/usr/local/bin/catkin", line 7, in <module>
    from catkin_tools.commands.catkin import main
  File "/usr/local/lib/python3.5/dist-packages/catkin_tools/commands/catkin.py", line 23, in <module>
    from catkin_tools.common import is_tty
  File "/usr/local/lib/python3.5/dist-packages/catkin_tools/common.py", line 23, in <module>
    import trollius as asyncio
ImportError: No module named 'trollius'
```

### Steps to Reproduce the Issue

```bash
pip install -U catkin_tools
catkin config
```

**Comment by slivingston** [comment]
I also observe this behaviour on a similar platform: Ubuntu 16.04, Python 3.5.2, catkin_tools v0.4.4 installed via `pip`.

Part of a solution was merged in pull request #282, but it remains to express the dependency in setup.py. In particular, `trollius` should be listed [in `install_requires` in setup.py](https://github.com/catkin/catkin_tools/blob/8b2d68f65f6a43d732dd1a2467f287b8fecfd3ae/setup.py#L13-L18).

**Comment by atomoclast** [comment]
I too am experiencing this issue.

**Comment by slivingston** [comment]
Let me know if I should open a PR that provides the patch [proposed above](https://github.com/catkin/catkin_tools/issues/445#issuecomment-302977665)

**Comment by jacknlliu** [comment]
I got the error on **Ubuntu 14.04**, python 3.4.3, catkin 0.4.4 with ROS indigo.

**Comment by mikepurvis** [comment]
I still see this issue doing a `pip install catkin_tools` on Ubuntu within a Python 3 virtualenv— the fix is merged but not released.
