### ISSUE TITLE
Syntax for running tests

### ISSUE THREAD

**Issue by davetcoleman** [catkin/catkin_tools#453]
Not sure where to post this:

I've been struggling with a [weird bug](https://github.com/ros-planning/moveit_robots/pull/60) in how we run tests using [moveit_ci](https://github.com/ros-planning/moveit_ci/). We use the same CI script for all our moveit repos but only one repo fails, and it only fails on Travis, not locally when using the same commands. A working example is [here](https://travis-ci.org/ros-planning/moveit/jobs/221098475) and a broken one is [here](https://travis-ci.org/ros-planning/moveit_robots/builds/223017528). Overall, though, it boils down to this one problem:

```
catkin build --no-status --summarize --make-args tests -- --no-deps atlas_moveit_config
```

works, but this does not for certain packages:

```
export TEST_PKGS="--no-deps atlas_moveit_config"
catkin build --no-status --summarize --make-args tests -- $TEST_PKGS
```

Any help is appreciated, I'm sure its something really simple.

**Comment by k-okada** [comment]
Did you try
```
diff --git a/travis.sh b/travis.sh
index 58888a0..b9d9fbe 100755
--- a/travis.sh
+++ b/travis.sh
@@ -157,7 +157,7 @@ SOURCE_PKGS=$(catkin_topological_order "$CI_SOURCE_PATH" --only-names)
 echo -e "Catkin packages in source repo: $SOURCE_PKGS"
 
 echo "--------------"
-TEST_PKGS=$(catkin_topological_order "$CI_SOURCE_PATH" --only-names | grep -Fvxf <(echo "$TEST_BLACKLIST" | tr ' ;,' '\n'))
+TEST_PKGS=$(catkin_topological_order "$CI_SOURCE_PATH" --only-names | grep -Fvxf <(echo "$TEST_BLACKLIST" | tr ' ;,' '\n') | tr '\n' ' ')
 if [ -n "$TEST_PKGS" ]; then
     TEST_PKGS="--no-deps $TEST_PKGS";
 fi
```

**Comment by wjwwood** [comment]
This looks to be the problem:

```
[build] Given package '--no-deps atlas_moveit_config
atlas_v3_moveit_config
baxter_ikfast_left_arm_plugin
baxter_ikfast_right_arm_plugin
baxter_moveit_config
iri_wam_moveit_config
moveit_robots
r2_moveit_generated' is not in the workspace
```

For some reason all of:

```
--no-deps atlas_moveit_config
atlas_v3_moveit_config
baxter_ikfast_left_arm_plugin
baxter_ikfast_right_arm_plugin
baxter_moveit_config
iri_wam_moveit_config
moveit_robots
r2_moveit_generated
```

Is getting parsed as a package name. This might be to do with how you're invoking the command, either with the spaces escaped or otherwise passing all of that as a single argument to the Python script.

**Comment by mikepurvis** [comment]
I'm now actively working on a `catkin_tools_test` plugin, so there may be some good news in the next week or two. :) In the meantime, most of our devs just navigate into the build tree and run tests directly from there with `make`. So:

```
catkin build --no-status
pushd build/atlas_moveit_config
make run_tests
popd
```

**Comment by jack-oquin** [comment]
That's the way I've been doing it. A fully-functional ``test`` verb would be very welcome.

**Comment by davetcoleman** [comment]
@k-okada your suggestion [did not work](https://travis-ci.org/ros-planning/moveit_robots/jobs/221488759), but thanks

@mikepurvis do you have more example code for converting from a list of packages to running each build? Does it cover both make and cmake tests?

**Comment by mikepurvis** [comment]
The way I'm doing it (currently) only works for packages which follow the `run_tests_[pkg]_[type]_[name]` pattern used by catkin, eg:

```
$ ~/catkin_tools_env/bin/catkin test --list
[test] Tests available in workspace packages:
[test] * catkin
[test]   - nosetests
[test]   - nosetests_test.local_tests
[test]   - nosetests_test.unit_tests
[test] * genmsg
[test]   - nosetests
[test]   - nosetests_test
[test] * genpy
[test]   - nosetests
[test]   - nosetests_test
[test] * message_filters
[test]   - gtest
[test]   - gtest_message_filters-msg_cache_unittest
[test]   - gtest_message_filters-test_approximate_time_policy
[test]   - gtest_message_filters-test_chain
[test]   - gtest_message_filters-test_exact_time_policy
[test]   - gtest_message_filters-test_simple
[test]   - gtest_message_filters-test_synchronizer
[test]   - gtest_message_filters-time_synchronizer_unittest
[test]   - nosetests
[test]   - nosetests_test.test_approxsync.py
[test]   - nosetests_test.test_message_filters_cache.py
[test]   - rostest
[test]   - rostest_test_test_subscriber.xml
[test]   - rostest_test_time_sequencer_unittest.xml
```

This covers my immediate need, but it would of course be possible to have it fall back on recognizing the `test` target used by CMake, or even pluggable, to pick up testing schemes used by other build systems.

It's not in a usable state yet, but I've dumped the source here for anyone interested to look: https://github.com/mikepurvis/catkin_tools_test/blob/master/catkin_tools_test/test.py

One of the barriers at the moment is #454. The usefulness of `catkin test` is severely limited without completion, but I'm not sure if I should proceed by trying to make completion pluggable, or by attempting to contribute the `test` verb directly to `catkin_tools` proper.

**Comment by k-okada** [comment]
@davetcoleman I see ,now, I finally understand how weird it is. see WORKAROUND for this https://github.com/k-okada/moveit_ci/commits/master and confirmed it is working https://travis-ci.org/k-okada/moveit_robots/jobs/225488119,
The problem is when you pass `catkin run_tests...`  to `travis\run` function , the last argument is treated as one long string and I suspect travis is reading from tarvis.yaml and do some processing then pass to shell, and something goes wrong on this 'processing' mode.
Since we do not allow space character as package name, so we can fix this problem in catkin_tools side, but not sure if that is the right way to go.

**Comment by davetcoleman** [comment]
@k-okada that seems to have worked on my first test! I'm re-running the tests to be sure, please review the PR https://github.com/ros-planning/moveit_ci/issues/28

**Comment by davetcoleman** [comment]
I use catkin test often and believe this can be closed.
