### ISSUE TITLE
Verb alias doesn't support arguments with spaces

### ISSUE THREAD

**Issue by Xfel** [catkin/catkin_tools#464]
I'm trying to create a verb alias for generating eclipse project files. The regular command for this is:
```bash
catkin build  --force-cmake -G"Eclipse CDT4 - Unix Makefiles"
```
So I tried to define the alias like this:
```yaml
eclipse: 'build  --force-cmake -G"Eclipse CDT4 - Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug'
```

This does not work since the argument contains spaces and the quoting is not recognized.

I'd suggest to either use something like shlex to process the alias definition, or allow using a yaml list to define the arguments.

**Comment by wjwwood** [comment]
That sounds reasonable, please consider a pull request to either use shlex or allow commands to be a list in YAML. Both sound reasonable to me.

**Comment by wjwwood** [comment]
I think this is closed with https://github.com/catkin/catkin_tools/pull/476.
