### ISSUE TITLE
Plugin for per-package build contexts?

### ISSUE THREAD

**Issue by mikepurvis** [catkin/catkin_tools#465]
We're having a situation in our bundle builds where it would be really helpful to be able to tweak aspects of the Context object (particularly the make/cmake args) on a per-package basis. I think adding this functionality natively to catkin_tools might overcomplicate things for users who don't want or need that capability, so my proposal would be:

- Add a new plugin hook for registering functions which are passed the package name and a copy of the Context object at the beginning of each job and have an opportunity to mutate the Context according to their own internal logic.
- When one or more such plugins exists, each one is added as a "step" to every job, where the mutated version's summary is dumped to that step's log file for post-build inspection purposes.

I feel that this would offer the flexibility we'd like to have while keeping the overall surface area and complexity low. Thoughts?

FYI @tspicer01

**Comment by wjwwood** [comment]
This? https://github.com/catkin/catkin_tools/issues/205

**Comment by wjwwood** [comment]
Well not with the plugin architecture you're talking about, but the general idea of package specific settings (specifically cmake and make arguments) was in #205.

**Comment by mikepurvis** [comment]
Closing in favour of #205.
