### ISSUE TITLE
Dependencies in workspace not found when installing with -DCMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by v-lopez** [catkin/catkin_tools#473]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: Linux 4.4.0-64-generic #85~14.04.1-Ubuntu
* Python Version: Python 2.7.6
* Version of catkin_tools: master (https://github.com/catkin/catkin_tools/commit/2280a2a51f86949af7896af3876cb1f4c6e7bf46)
* ROS Distro: indigo

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [x] Works with `catkin_make` (catkin_make -DCMAKE_INSTALL_PREFIX=/tmp install)
* [x] Works with `catkin_make_isolated --merge` (catkin_make_isolated --install --install-space /tmp  --merge)
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [ ] I did  not `read this`

### Expected Behavior
Should build and install the packages in the workspace (hardware_interface and combined_robot_hw) at the specified INSTALL_PREFIX (/tmp)

### Actual Behavior
hardware_interface is built properly, but combined_robot_hw fails to find hardware_interface.
This happens with other packages as well. 

[logs.zip](https://github.com/catkin/catkin_tools/files/1127713/logs.zip)

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)

### Steps to Reproduce the Issue
Make sure you have not installed ros-indigo-hardware-interface or it might find that one instead of the one in the workspace.
```bash
cd `mktemp -d`
git clone https://github.com/ros-controls/ros_control src/ros_control
catkin init
catkin install
catkin build  hardware_interface combined_robot_hw --cmake-args -DCMAKE_INSTALL_PREFIX=/tmp
```

If the CMAKE_INSTALL_PREFIX is removed or changed to $PWD/install it works.

**Comment by NikolausDemmel** [comment]
I believe you should not set `CMAKE_INSTALL_PREFIX` manually have you tried with 

```
catkin config --install-space /tmp
```

instead?

**Comment by v-lopez** [comment]
You are right, thanks for the quick help. It stopped working when we migrated from 0.3.0 to the current version, but probably was working by sheer luck.

Thanks again.
