### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by cmuck** [catkin/catkin_tools#485]
Hi,

the last release v0.4.4 was made in February, v0.4.3 was released in January. I would like to know when it is planned to tag/create a new release v0.4.5 or v0.5.0?
I'm asking because many fixes and enhancements were contributed in the meantime.

Thanks!

**Comment by davetcoleman** [comment]
+1

**Comment by v-lopez** [comment]
No release planned?

**Comment by scott-eddy** [comment]
There is an active discussion about the life-cycle of this project ongoing in #507.  From @wjwwood:
>>There is a bunch of fixes that have already landed into master but have not been released as of now (last release a year ago).

>That's pretty much solely my fault. I didn't have time to do it at the time and it has slipped down the priority queue for me over and over (people keep pointing it out). One of the reasons it was released about a year ago is because that's when Lunar was released, and I tend to spend the most time on my ROS related projects (this, rviz, rosdep, wstool/rosinstall/vcstools, etc...) around release time. So I'll probably get to some of the stuff on this repository soon in preparation for Melodic, but that's never certain.

**Comment by DLu** [comment]
Okay, setting up a checklist based on William's comment on the other thread.:
 * [ ] Merge Outstanding PRs
 * [ ] Write Changelogs
 * [ ] Perform Testing

I was going to take a pass at labelling the PRs, but I don't have adequate permissions. 

@jbohren You are the owner of a couple of the PRs which have accumulated some merge errors. Do you have time to resolve any of them?

**Comment by wjwwood** [comment]
@DLu do you want permissions so you can do labeling, retrigger CI, etc.?

**Comment by DLu** [comment]
Sure, although in truth I have very little idea what this code base contains.

**Comment by 130s** [comment]
Or could @mikepurvis as https://github.com/catkin/catkin_tools/issues/507#issuecomment-422457629 mentions get release ready?

**Comment by jbvo** [comment]
I'm trying to get some attention on this issue, since with the recent bug #538 now I'm guessing the majority of the catkin_tools users is getting affected by not having a new release. Seeing that @mikepurvis merged a fix within a few days, would it also make sense if he could release it?

**Comment by wjwwood** [comment]
I'll help make the release (special permissions are required), when someone asks me.

**Comment by mikepurvis** [comment]
I was hoping to tackle a few more low-hanging fruit issues (#523, #528, #510), but the reality is that none of them are impacting my day-to-day, and given the importance of the current fixes, I think the current state of master should become 0.4.5. I've been using it for several days from source and it's been good to me.

@wjwwood Do the thing.

**Comment by wjwwood** [comment]
@mikepurvis do you want to do something like like these two commits from the previous release first?

- https://github.com/catkin/catkin_tools/commit/44aa461cd35e77be3f922259bc66c59f6d477d55
- https://github.com/catkin/catkin_tools/commit/a5db715ef4dd9176d079d2a01ae2f7a57f9c9536

At least the second one would be needed to actually release. Then I can push all the buttons to generate debs and push it to pypi. I can give you permissions so you can do/edit the latter. Do you have a pypi account (send it offline if you like)?

**Comment by wjwwood** [comment]
I just pushed the `0.4.5` release for @mikepurvis, it should be available from pip now and apt soon.

Thanks for working on it @mikepurvis, I appreciate it and I know the community does too :)
