### ISSUE TITLE
Any Plug-in that can be used with qt creator?

### ISSUE THREAD

**Issue by hyx007** [catkin/catkin_tools#494]
Hi,I'm using Qt5.7，but I found that this version of qt doesn't support compile packages  that can be used catkin  build , is there any plug in that can be used catkin build with qt creator?

**Comment by NikolausDemmel** [comment]
You can use it with a plugin, but also without works nicely, see

http://wiki.ros.org/IDEs#Qt_Creator_Plugin_for_ROS

http://wiki.ros.org/IDEs#catkin_tools-1
