### ISSUE TITLE
find_package(catkin) failed QTCreator 4.5

### ISSUE THREAD

**Issue by Bla1** [catkin/catkin_tools#495]
I'm trying to open up a ROS project with QtCreator 4.5. Here is what I did.
1. clone ROS project from github
2. run catkin_make
3. copy toplevel.cmake into the /src/ folder of my project and rename it CMakeLists.txt
4. modified ~/.bashrc to include the line 
`source ~/[project]/devel/setup.bash`
5. ran source .bashrc
6. modified ~/.local/share/applications/QtCreator to have bash -i -c [pathtoexecutable] %F
7. Opened up QtCreator and clicked open project and selected [project]/src/CMakeLists and set the Build path to [project]/build

Except it failed with this message:
```
Running "/usr/bin/cmake /home/[me]/[project]/src '-GUnix Makefiles' -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++-5 -DCMAKE_C_COMPILER:STRING=/usr/bin/gcc-5 '-DCMAKE_PREFIX_PATH:STRING=%{Qt:QT_INSTALL_PREFIX}' -DQT_QMAKE_EXECUTABLE:STRING= -Dcatkin_DIR:PATH=/home/[me]/[project]/build/catkin" in /home/[me]/[project]/build.
CMake Error at CMakeLists.txt:58 (message):
  find_package(catkin) failed.  catkin was neither found in the workspace nor
  in the CMAKE_PREFIX_PATH.  One reason may be that no ROS setup.sh was
  sourced before.
```
I believe I followed all the instructions at http://wiki.ros.org/IDEs#QtCreator fully. Am I missing something?

**Comment by racko** [comment]
catkin_tools is not catkin. catkin_make is part of https://github.com/ros/catkin.

And from what I've seen, the maintainers would prefer to see these questions at https://answers.ros.org/questions/ so other users can find the answers easier.

**Comment by Bla1** [comment]
Ah sorry about that, I have asked my question in https://answers.ros.org/questions/ . Thanks for providing me with the info!
