### ISSUE TITLE
Gentoo ebuild complaining about tests installed during emerging

### ISSUE THREAD

**Issue by MalcolmMielle** [catkin/catkin_tools#498]
I'm creating a custom ebuild file for catkin_tools for gentoo. However, during emerge, it complains about test being installed:

```
 * ERROR: dev-ros/catkin_tools-0.4.4::overlaid failed (install phase):
 *   Package installs 'tests' package which is forbidden and likely a bug in the build system.
 * 
```

I guess it's because setup.py is trying to install some test files. I'm no expert with setuptools but when I looked in the code however, it seemed to me that test where ignored, as the last line here shows:

```
setup(
    name='catkin_tools',
    version='0.4.4',
    packages=find_packages(exclude=['tests', 'docs']),
```

So I'm a bit at a loss understanding why I have this message during the emerge and came here to confirm that no test are supposed to be installed with the version 0.4.4

Best,

**Comment by racko** [comment]
Interesting. I checked the Arch Linux [python2-catkin-tools](https://aur.archlinux.org/packages/python2-catkin-tools/) package. As you can see in the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python2-catkin-tools) script, it runs `python2 setup.py install --root="$pkgdir/" --optimize=1`, and the result indeed contains

```
$ pacman -Ql python2-catkin-tools
...
python2-catkin-tools /usr/lib/python2.7/site-packages/tests/
...
$ pacman -Ql python2-catkin-tools | grep tests | wc -l
80
```

So 80 files get installed below (and including) /usr/lib/python2.7/site-packages/tests/ :worried:

**Comment by MalcolmMielle** [comment]
Because I'm such a noob at setuptool I went berserk and added a patch that basically remove the test folder and now the install succeeded. Far from  being a solution but at least the problem is indeed 100% confirmed to be the installation of test files :)

**Comment by racko** [comment]
Here's the issue:

```
> find_packages()
['tests', 'catkin_tools', 'tests.unit', 'tests.system', 'tests.system.verbs', 'tests.system.verbs.catkin_profile', 'tests.system.verbs.catkin_init', 'tests.system.verbs.catkin_config', 'tests.system.verbs.catkin_build', ...]
> find_packages(exclude=['tests', 'docs'])
['catkin_tools', 'tests.unit', 'tests.system', 'tests.system.verbs', 'tests.system.verbs.catkin_profile', 'tests.system.verbs.catkin_init', 'tests.system.verbs.catkin_config', 'tests.system.verbs.catkin_build', ...]
```

I guess I'll create a pull request tomorrow or so.

**Comment by wjwwood** [comment]
Those are already excluded:

https://github.com/catkin/catkin_tools/blob/d3d5442bb0ab0cd3af696d42913390d0ca703af3/setup.py#L113

Though I remember an issue or pull request, either on this repository or another I maintain (maybe `osrf_pycommon` or one of the `wstool` and friends packages), that these might need wildcards to work properly? For instance, `osrf_pycommon` uses a `*`:

https://github.com/osrf/osrf_pycommon/blob/e32de70e8b42dcd96bb66d29ddfb62e7fd8b795e/setup.py#L12

**Comment by racko** [comment]
Ah, perfect:

```
> find_packages(exclude=['tests*'])
['catkin_tools', 'catkin_tools.verbs', 'catkin_tools.notifications', 'catkin_tools.jobs', 'catkin_tools.execution', 'catkin_tools.commands', 'catkin_tools.verbs.catkin_profile', 'catkin_tools.verbs.catkin_locate', 'catkin_tools.verbs.catkin_list', 'catkin_tools.verbs.catkin_init', 'catkin_tools.verbs.catkin_env', 'catkin_tools.verbs.catkin_create', 'catkin_tools.verbs.catkin_config', 'catkin_tools.verbs.catkin_clean', 'catkin_tools.verbs.catkin_build', 'catkin_tools.jobs.commands']
```

**Comment by racko** [comment]
Here's a pull request: #499

**Comment by MalcolmMielle** [comment]
PR fixes the issues for the ebuild, thanks :)
