### ISSUE TITLE
Autocomplete only find src instead of executable

### ISSUE THREAD

**Issue by lz89** [catkin/catkin_tools#504]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: 4.10.0-37-generic 16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 2.7.12
* Version of catkin_tools: catkin_tools 0.4.4
* ROS Distro: kinetic

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [ ] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [x] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [ ] I did  not `read this`

### Expected Behavior

[//]: # (Please describe what you expected or think should happen.)
I am using zsh and I have sourced the devel/setup.zsh.

`rosrun package_name [tab]`
shows the package src files (files in the same folder as the manifest and CMakeLists).
However, I would expect the executable would appear. For example:
`rosrun package_name package[tab] `

give me
`rosrun package_name package_name_node`
Note that if I run the above comment directly, it works (run the node/executable). It just the autocompletion is not working.

I wonder if anything special I need to configure in the CMakeLists, the manifest or the catkin configrue.

**Comment by matthaeusheer** [comment]
Same problem for me, is there any solution to this yet?
