### ISSUE TITLE
Support for 'condition' for dependencies (Package Manifest Format Three)

### ISSUE THREAD

**Issue by stwirth** [catkin/catkin_tools#508]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

The current [draft for Package Manifest Format Three](http://www.ros.org/reps/rep-0149.html#id19) specifies a new attribute [`condition`](http://www.ros.org/reps/rep-0149.html#id19) for depend tags.
catkin_pkg already supports this new attribute (see https://github.com/ros-infrastructure/catkin_pkg/pull/197).

However, when running `catkin list --deps` for a package that uses a condition, I still see the dependencies listed that should have been filtered out by the condition.

Is catkin_tools going to support the new attribute `condition` in the near future?

**Comment by wjwwood** [comment]
I don't have time to work on updating `catkin_tools` to support this, but @mikepurvis or I might have time to review a pr.
