### ISSUE TITLE
How to run a single test executable from a package containing many

### ISSUE THREAD

**Issue by jlack1987** [catkin/catkin_tools#515]
When I used O.G. catkin, I could run a single test executable from a package that contained many test executables by running,
```
catkin_make run_tests_my_package_gtest_my_package_test
```
and that would only run the one test. I have yet to be able to figure out how to do this with `catkin_tools` and it's a huge issue for me because some package have many tests and if there are rostests those can take awhile to run, so if i'm debugging a single test it's a huge time sink having to always run all of a packages tests instead of just the one I want.

**Comment by mikepurvis** [comment]
There isn't a great story for this, unfortunately. Your best bet at the current time is to invoke `make` directly in the build directory corresponding to the package your test target exists in. For example to list targets:

```
# List targets
make -C build/<package> help

# Invoke specific target
make -C build/<package> run_tests_<foo>
```

Hope that's a help.

**Comment by mikepurvis** [comment]
If you're interested, I began work on a `test` verb plugin for catkin which would have automated away some of this. The [bones of it are here](https://github.com/mikepurvis/catkin_tools_test/blob/master/catkin_tools_test/test.py), but I should caution that I'm unlikely to move it forward much myself at this point— there are some hairy issues around invoking tests concurrently in particular.

**Comment by jlack1987** [comment]
No this is **exactly** what I was looking for. I get it that it's not a nicely wrapped up solution, but just having a simple way to do it is enough for me. Can't tell you how much time you just saved me as I sit here debugging 1 test but have to run a package worth of tests that takes 30+ seconds. Thanks so much, will close the ticket now.
