### ISSUE TITLE
Trollius is deprecated---is it still needed?

### ISSUE THREAD

**Issue by sanjayankur31** [catkin/catkin_tools#518]
Hi,

`requirements.txt` still lists trollius, but trollius is [now no longer maintained](https://github.com/vstinner/trollius) for python2. Is it still needed by catkin_tools?

**Comment by wjwwood** [comment]
Yes.

**Comment by sanjayankur31** [comment]
Is there a plan to drop the requirement, or will it remain until py2 dies out in 2020?

**Comment by wjwwood** [comment]
It will remain a requirement until catkin_tools no longer supports Python2 (regardless of the status of Python2 or Trollius's support). There's not another option. The only path forward is to move to Python3 exclusively, until then Trollius is required.

**Comment by sanjayankur31** [comment]
I thought so too. Thanks!
