### ISSUE TITLE
Persistent Compiler Caching with ccache or alikes

### ISSUE THREAD

**Issue by nordlow** [catkin/catkin_tools#524]
What's the preferred way of utilizing compiler caching when doing `catkin build`?

I'm currently using

```
catkin build -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
```

and it seems to work fine.

**Comment by mikepurvis** [comment]
I just do it with envvars:

```
export CC="ccache gcc"
export CXX="ccache g++"
```

**Comment by gavanderhoorn** [comment]
On Ubuntu, installing `ccache` and making sure `/usr/lib/ccache` is on the `$PATH` before any of the other locations where `gcc`/`g++` and friends can be found would also be an option.
