### ISSUE TITLE
Failed building catkin!

### ISSUE THREAD

**Issue by stribuda** [catkin/catkin_tools#525]
I'm trying to install ROS on my Ubuntu 16.04 to use the simulator Gazebo. First of all i tried to run a script that installs everything, then i got a error at the end of it. So i decided to install ROS directly from the instructions in their website, but i got the same error. Then i followed other tutorials, tried to find someone who had the same issue but no way! My last chance is here.. I gess the problem CMake, i use python3 and i installed all necessary libraries.

>sudo catkin build

Profile:                     default
Extending:                   None
Workspace:                   /home/stribuda

Build Space:        [exists] /home/stribuda/build
Devel Space:        [exists] /home/stribuda/devel
Install Space:      [unused] /home/stribuda/install
Log Space:          [exists] /home/stribuda/logs
Source Space:       [exists] /home/stribuda/src
DESTDIR:            [unused] None

Devel Space Layout:          linked
Install Space Layout:        None

Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False

Whitelisted Packages:        None
Blacklisted Packages:        None

NOTE: Forcing CMake to run for each package.

WARNING: Your workspace is not extending any other
result space, but it is set to use a `linked`
devel space layout. This requires the `catkin`
CMake package in your source space in order to be
built.

[build] Found '1' packages in 0.0 seconds.
[build] Package table is up to date.
Warning: generated devel space setup files have been deleted.
Starting  >>> catkin_tools_prebuild

Errors     << catkin_tools_prebuild:cmake /home/stribuda/logs/catkin_tools_prebuild/build.cmake.013.log          
CMake Error at /home/stribuda/build/catkin_tools_prebuild/CMakeLists.txt:12 (message):
  The catkin CMake module was not found, but it is required to build a linked
  workspace.  To resolve this, please do one of the following, and try
  building again.

   1. Source the setup.sh file from an existing catkin workspace:
      source SETUP_FILE

   2. Extend another catkin workspace's result (install or devel) space:
      catkin config --extend RESULT_SPACE

   3. Set `catkin_DIR` to the directory containing `catkin-config.cmake`:
      catkin config --cmake-args -Dcatkin_DIR=CATKIN_CMAKE_CONFIG_PATH

   4. Add the catkin source package to your workspace's source space:
      cd SOURCE_SPACE && git clone https://github.com/ros/catkin.git

cd /home/stribuda/build/catkin_tools_prebuild; catkin build --get-env catkin_tools_prebuild | catkin env -si  /usr/bin/cmake /home/stribuda/build/catkin_tools_prebuild --no-warn-    unused-cli -DCATKIN_DEVEL_PREFIX=/home/stribuda/devel/.private/catkin_tools_prebuild -DCMAKE_INSTALL_PREFIX=/home/stribuda/install; cd -

Failed     << catkin_tools_prebuild:cmake          [ Exited with code 1 ]                                                               
Failed    <<< catkin_tools_prebuild                [ 0.0 seconds ]                                                        
Abandoned <<< px4                                  [ Unrelated job failed ]                                                                                   
[build] Summary: 0 of 2 packages succeeded.                                                                                                                     
[build]   Ignored:   None.                                                                                                                                    
[build]   Warnings:  None.                                                                                                                                      
[build]   Abandoned: 1 packages were abandoned.                                                                                                        
[build]   Failed:    1 packages failed.                                                                                                                      
[build] Runtime: 0.1 seconds total
..............................................................................

If someone can help, it would be very helpful! Thanks

**Comment by gladijos** [comment]
it helped me
. /opt/ros/kinetic/setup.bash

**Comment by apache8080** [comment]
Was the solution to this just resourcing /opt/ros/kinetic/setup.bash because when I did that it still didn't fix the error.

**Comment by SatishUpadhyaya** [comment]
I have ROS melodic, and I tried sourcing /opt/ros/melodic/setup.bash. It still didn't work.

**Comment by wk39** [comment]
> I have ROS melodic, and I tried sourcing /opt/ros/melodic/setup.bash. It still didn't work.

In my case, incomplete ROS setup.

rosdep update

now it works.

http://wiki.ros.org/rosdep

**Comment by DanielArnett** [comment]
I was moving a workspace to a different machine and encountered this. Deleting the below directories fixed it after the above suggestions failed. Obviously back these up just in case there's something you need.

```
.catkin_tools/
logs/
devel/
```
Leaving only src/ behind.

**Comment by EricWiener** [comment]
For me the issue was I was using `zsh`, but sourcing `/opt/ros/melodic/setup.bash` instead of `/opt/ros/melodic/setup.zsh`.

**Comment by ArciAndres** [comment]
In my case I extended the configuration of catkin (same to source) explicitly:
`catkin config  --extend /opt/ros/melodic`

**Comment by vishal-ahirwar** [comment]
I'm getting this:
WARNING: Your workspace is not extending any other result space, but
it is set to use a `linked` devel space layout. This requires the
`catkin` CMake package in your source space in order to be built.

**Comment by AbdoAliMos** [comment]
> I'm getting this: WARNING: Your workspace is not extending any other result space, but it is set to use a `linked` devel space layout. This requires the `catkin` CMake package in your source space in order to be built.

Have you found a solution by any chance? I am having the same issue!

**Comment by timonegk** [comment]
Did you source the /opt/ros space before trying to build?

**Comment by dvogureckiy99** [comment]
same problem

**Comment by timonegk** [comment]
@dvogureckiy99 then same question; Did you source the workspace in /opt/ros before trying to build?

**Comment by dvogureckiy99** [comment]
> @dvogureckiy99 then same question; Did you source the workspace in /opt/ros before trying to build?

I have ros humble and aIl don't have it in /opt/ros/.

**Comment by timonegk** [comment]
Do you build everything from source? If yes, does your workspace contain the catkin package (https://github.com/ros/catkin)?

**Comment by timonegk** [comment]
It looks like there is a package in your workspace that requires solo12dof_quadruped but your workspace does not contain this package. Please make sure that all packages required by your packages are present. You can usually check the dependencies in the package.xml filles.

**Comment by korayaykor** [comment]
Got the same error here. I think it's about one line installing after installing the environment and dependencies for building packages again [https://wiki.ros.org/noetic/Installation/Ubuntu](url) from official site. Problem solved.
