### ISSUE TITLE
ValueError: No closing quotation

### ISSUE THREAD

**Issue by galou** [catkin/catkin_tools#528]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: `uname -a`: 4.15.0-39-generic
* Python Version: `python --version`: Python 2.7.15rc1
* Version of catkin_tools: `catkin --version` OR *Git revision*
```
catkin_tools 0.4.4 (C) 2014-2018 Open Source Robotics Foundation
catkin_tools is released under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
---
Using Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```
* ROS Distro: `echo $ROS_DISTRO`: melodic
* Shell: zsh 5.4.2 (x86_64-ubuntu-linux-gnu) but the bug appears also in bash

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [ ] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [ ] I did  not `read this`
* [x] Does not work with `catkin config`

### Expected Behavior

[//]: # (Please describe what you expected or think should happen.)

- `catkin config` should show the configuration

### Actual Behavior

[//]: # (Please describe what actually happens.)

- `catkin config` should show the configuration, I have (here shortened)
```
WARNING: Could not parse env string: `export CLUTTER_IM_MODULE=xim
...
export COMP_WORDBREAKS=$' \t\n"\'><;|&(:'
...
`
Traceback (most recent call last):
  File "/usr/bin/catkin", line 9, in <module>
    load_entry_point('catkin-tools==0.4.4', 'console_scripts', 'catkin')()
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 267, in main
    catkin_main(sysargs)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 262, in catkin_main
    sys.exit(args.main(args) or 0)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/cli.py", line 290, in main
    ctx = Context.load(opts.workspace, opts.profile, opts, append=True)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/context.py", line 175, in load
    ctx.load_env()
  File "/usr/lib/python2.7/dist-packages/catkin_tools/context.py", line 324, in load_env
    sticky_env = get_resultspace_environment(self.devel_space_abs, quiet=True)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/resultspace.py", line 160, in get_resultspace_environment
    for k, v in parse_env_str(lines).items()
  File "/usr/lib/python2.7/dist-packages/catkin_tools/common.py", line 688, in parse_env_str
    split_envs = [e.split('=', 1) for e in cmd_split(environ_str)]
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)

### Steps to Reproduce the Issue

[//]: # (Please give a series of command-line commands which cause the problem.)

[//]: # (Include a checkout URI for the workspace so that we can reproduce the issue.)
[//]: # (If we can't reproduce it on our own machines, we can't fix it!)

```bash
cd my_ros_workspace
export COMP_WORDBREAKS=$' \t\n"\'><;|&(:'
catkin config
```

Bash command `unset COMP_WORDBREAKS` solves the issue.

**Comment by galou** [comment]
Am I the only one to have this issue? Could this be a `shlex` issue?

**Comment by denissonpanta** [comment]
I am Having the same issues

**Comment by mvanlobensels** [comment]
Closing and reopening my terminal fixed it

**Comment by HareshMiriyala** [comment]
still not fixed. Does anyone know what the solution is ?

**Comment by timonegk** [comment]
I just created another pull request (#686) that aims to fix this issue. The test suite is passing and everything else I tested locally is working, so I am fairly certain that I got it right this time. Still, if you could test the fix, that would be nice.

**Comment by galou** [comment]
I'm confirming that #686 solves the issue.
