### ISSUE TITLE
Is `-x` overwriting `--install-space` a expected behavior?

### ISSUE THREAD

**Issue by foodtooth** [catkin/catkin_tools#531]
### System Info

* Operating System: `Linux SZX1000461547 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `Python 2.7.12`
* Version of catkin_tools:
```
catkin_tools 0.4.4 (C) 2014-2018 Open Source Robotics Foundation
catkin_tools is released under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
---
Using Python 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]`
```
* ROS Distro: `kinetic`

### Build / Run Issue

* [ ] The option `-x _debug` and `-i /opt/kinetic` can not work together
* [ ] `-x` option will overwrite `-i`

Is this a expected behavior?

**Comment by timonegk** [comment]
The behavior was not expected and was fixed in #560.
