### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by MatthijsBurgh** [catkin/catkin_tools#540]
The link on the `workspace mechanics` page to `linked develspace` page is broken.

The generated link is `https://catkin-tools.readthedocs.io/en/latest/advanced/linked_develspace`, while it should be `https://catkin-tools.readthedocs.io/en/latest/advanced/linked_develspace.html`. So the `.html` is missing.

Affected line: `docs/mechanics.rst#L75`

Changing the line to be similar to `docs/migration.rst#L253` might be the solution.

**Comment by mikepurvis** [comment]
Please send a PR!

**Comment by MatthijsBurgh** [comment]
@mikepurvis see #546
