### ISSUE TITLE
Packages ignored. What package and why? 

### ISSUE THREAD

**Issue by roman-tub** [catkin/catkin_tools#543]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

Hi guys,
this might be stupid, but I spent quite a while trying to find the information I'm looking for. 
Maybe this is a feature request or maybe I'm just not seeing the obvious.

### System Info

* Operating System: `Ubuntu 4.15.0-46-generic`
* Python Version: `Python 2.7.15rc1`
* Version of catkin_tools: `catkin_tools 0.4.4`
* ROS Distro: `melodic`

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [ ] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [x] Works with `catkin build`
* [x] Works with `catkin build -p1`
* [ ] I did  not `read this`

### Expected Behavior

[//]: # (Please describe what you expected or think should happen.)

I just want to know which package was ignored and why. 

### Actual Behavior

[//]: # (Please describe what actually happens.)

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)

### Steps to Reproduce the Issue

[//]: # (Please give a series of command-line commands which cause the problem.)
[//]: # (Include a checkout URI for the workspace so that we can reproduce the issue.)
[//]: # (If we can't reproduce it on our own machines, we can't fix it!)

Whitelist and blacklist are None.

```bash
VERBOSE=1 catkin build -p1 -v | grep -i ignor
```

gives: 
```bash
[build] Ignored: 1 packages were skipped or are blacklisted. 
```

**Comment by mikepurvis** [comment]
Show the packages in your workspace:

```
catkin list
```

I agree that the UI could be better here as far as having an option to show the ignored packages, or at least output the list of them to a file (for those of us who have hundreds of packages in our workspaces).

What you may be hitting is that I think catkin_tools considers metapackages to be be "skipped" in the sense that it considers them for dependency information but doesn't actually invoke anything— their `package.xml` file doesn't getting installed, so they don't appear in the final installspace (yes, this behaviour is probably a bug, see #418).

**Comment by roman-tub** [comment]
Thanks for your answer! 

I just found out, that there is an option for `catkin build` , which gives the info: 

```
--summarize, --summary, -s
                        Adds a build summary to the end of a build; defaults
                        to on with --continue-on-failure, off otherwise
```

**Comment by roman-tub** [comment]
And yes you were right. The ignored package is a metapackage. 
And yes I agree. This behaviour is confusing and probably a bug.
