### ISSUE TITLE
Support `catkin locate --this`

### ISSUE THREAD

**Issue by beetleskin** [catkin/catkin_tools#552]
For various bash commands, it would be nice to locate the package of the current working directory. My current workaround is 

```bash
catkin locate `catkin list --this -u`
```

but the missing `--this` always felt wrong, since most other verbs support it.

**Comment by mikepurvis** [comment]
A PR to add this functionality would be welcome!

**Comment by beetleskin** [comment]
I could give it a shot, would you point me to the right piece of code to put this in?

**Comment by jarvisschultz** [comment]
Note, this feature was introduced in 09e2b126, and should work on any version `>=0.4.0`

**Comment by beetleskin** [comment]
That's not true: the commit added `catkin list --this`, not `catkin locate --this`. I'm asking for the latter.

**Comment by jarvisschultz** [comment]
Doh.... sorry. Totally misread the original comment

**Comment by jarvisschultz** [comment]
Felt bad I gave dumb advice, so just submitted a PR.

**Comment by beetleskin** [comment]
haha, nice, thanks :)

**Comment by timonegk** [comment]
This was fixed in #605.
