### ISSUE TITLE
[Question] Run Build Without Install

### ISSUE THREAD

**Issue by fishyai** [catkin/catkin_tools#553]
[//]: # (Thank you for reporting an issue for catkin_tools!)

Hey, I love these tools and all the work you all are doing on them. I noticed that `catkin build` mentions that running `cmake install` is optional, but the code in cmake.py seems to always add the install job. Is there a way to build without running install? If not, it might make sense to change the docs.

Thanks!

-Adm

**Comment by mikepurvis** [comment]
The `install` step may be toggled by setting `catkin config --install` or `catkin config --no-install`. Hope that helps!

**Comment by mikepurvis** [comment]
Please re-open if this doesn't resolve the issue for you.
