### ISSUE TITLE
Need an option to only run catkin_prerun_tool to generate devel space without building anything

### ISSUE THREAD

**Issue by Vuwij** [catkin/catkin_tools#556]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: `Linux common-Oryx-Pro 4.15.0-54-generic #58~16.04.1-Ubuntu SMP Mon Jun 24 13:21:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `Python 2.7.12`
* Version of catkin_tools: `catkin_tools 0.4.5 (C) 2014-2019 Open Source Robotics Foundation*
* ROS Distro: `kinetic`

### Build / Run Issue

I need an option to run the catkin_build_prerun tool only first without building any packages so I can source all the packages without building this. The reason for this is so that I can use rosdep install -i $(rospack depends package) so I can recursively install all the dependencies for a single package rather than having to install all the package dependencies for an entire workspace.

This is useful if I want to have multiple robots with multiple high level packages and I don't want to install all system dependencies for all robots in the same workspace.

What I need is some option like catkin build --prerun-only so it can generate the files that allow me to add all files into the $ROS_PACKAGE_PATH
However rospack requires all the packages to be added to $ROS_PACKAGE_PATH and because of this I need to source all the packages in the workspace before. I've also tried catkin list --depends, but this only gives me package dependencies that are already installed rather than resolving from rosdep to get the list of system dependencies

**Comment by gavanderhoorn** [comment]
This is not an answer/resolution, but your post reminded me of [How to rosdep install dependencies of one package?](http://answers.ros.org/question/326140) on ROS Answers.

**Comment by mikepurvis** [comment]
This request sounds a little bit like !303, which also has to do with sourcing multiple package installspaces.

Note as well that if you mostly just care about inspecting the dependency tree, catkin_pkg, rosdistro, rospkg, and friends all have very nice Python APIs that you can use to get at and manipulate this kind of info. Rather than generating an unbuilt develspace to run rosdep against, it might be easier to just write a small external program which examines the src space and generates a list of system deps. See as a starting point: https://github.com/mikepurvis/ros-bundling/blob/master/rosdep_lite/deps_from_workspace.py

**Comment by Vuwij** [comment]
Well ideally I want to run something like rosdep install package and have it traverse the list of packages that it depends and install all system and distribution dependencies

My situation
package_b depends on package_a
package_c depends on package_a
package_a depends on system_dependency_e
package_b depends on system_dependency_f

rosdep install package_a --some-commands
will install a, b, e, and f

However I think rosdep install always returns something like
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
package_a: Cannot locate rosdep definition for [package_b]
```

My workaround is to do
```
rosdep install -i $(rospack depends package_a)
```

But rospack requires all files to be in $ROS_PACKAGE_PATH

So your suggestion is to write a small python script using the catkin_pkg API to add all of the files to the ROS_PACKAGE_PATH and then use my workaround.

Do you know of any better ways to do this currently?

**Comment by gavanderhoorn** [comment]
@Vuwij: did the Q&A I linked not already address this? Afaik it should do exactly what you ask for: consider all packages in a workspace for dependency resolution, but without installing dependencies for all those packages.
