### ISSUE TITLE
python3-catkin-tools debian uninstallable on bionic due to missing python3-trollius package

### ISSUE THREAD

**Issue by tfoote** [catkin/catkin_tools#558]
I tried to install python3-catkin-tools today on a new bionic machine and it failed to install

```
$ sudo apt install python3-catkin-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-catkin-tools : Depends: python3-trollius but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I've fallen back to the python2 version for now to keep working. 

It appears that the python3-trollius package is only available on xenial and not newer: https://packages.ubuntu.com/xenial/python3-trollius

**Comment by mikepurvis** [comment]
Trollius is supposed to be essentially a backport of the py3 async stuff. I have spent zero time looking into this, but I wonder how possible it would be to have the py3 version of catkin_tools just use `asyncio` directly?

I guess the other side of that question is, what features of catkin_tools are keeping users from migrating to colcon, and can they (or the necessary extension points) be added to colcon?

**Comment by paulbovbel** [comment]
I think the only thing that holds me back is https://github.com/colcon/colcon-core/issues/168, catkin profiles make it very straightforward to make sure everyone at Locus builds workspaces the same way.

**Comment by mikepurvis** [comment]
Following this up, I tried to install catkin_tools under the system Python (3.7) on Ubuntu Eoan, and I get an error about the missing Trollius:

```
# catkin
Traceback (most recent call last):
  File "/usr/local/bin/catkin", line 6, in <module>
    from catkin_tools.commands.catkin import main
  File "/usr/local/lib/python3.7/dist-packages/catkin_tools/commands/catkin.py", line 28, in <module>
    from catkin_tools.common import is_tty
  File "/usr/local/lib/python3.7/dist-packages/catkin_tools/common.py", line 23, in <module>
    import trollius as asyncio
ModuleNotFoundError: No module named 'trollius'
```
And then when I install trollius from pip, I get this instead:
```
# catkin                                                                                                                                                                       Traceback (most recent call last):
  File "/usr/local/bin/catkin", line 6, in <module>
    from catkin_tools.commands.catkin import main
  File "/usr/local/lib/python3.7/dist-packages/catkin_tools/commands/catkin.py", line 28, in <module>
    from catkin_tools.common import is_tty
  File "/usr/local/lib/python3.7/dist-packages/catkin_tools/common.py", line 23, in <module>
    import trollius as asyncio
  File "/usr/local/lib/python3.7/dist-packages/trollius/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/local/lib/python3.7/dist-packages/trollius/base_events.py", line 42, in <module>
    from . import tasks
  File "/usr/local/lib/python3.7/dist-packages/trollius/tasks.py", line 565
    def async(coro_or_future, loop=None):
            ^
SyntaxError: invalid syntax
```
Note that the pip install gives me `trollius-2.1.post2` as the most recent patches are marked on pypi as being for Python 2 use only.

**Comment by mikepurvis** [comment]
... however, if I hack the `trollius/tasks.py` file and remove/rename the offending function (on line 565), as well as its listing in the `__all__` dunder at the top of the file, then it seems to work as expected.

**Comment by mikepurvis** [comment]
The one goofy thing I got was as my build was finishing up:
```
[build] Summary: All 28 packages succeeded!                                                                                                                                                               [build]   Ignored:   2 packages were skipped or are blacklisted.
[build]   Warnings:  None.                                                                                                                                                                                [build]   Abandoned: None.                                                                                                                                                                                [build]   Failed:    None.                                                                                                                                                                                [build] Runtime: 1 minute and 34.0 seconds total.                                                                                                                                                         [build] Note: Workspace packages have changed, please re-source setup files to use them.
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fa8971964d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/trollius/base_events.py", line 395, in __del__
  File "/usr/local/lib/python3.7/dist-packages/trollius/unix_events.py", line 65, in close
  File "/usr/local/lib/python3.7/dist-packages/trollius/unix_events.py", line 166, in remove_signal_handler
  File "/usr/lib/python3.7/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

**Comment by mikepurvis** [comment]
It's not a great solution, but given that trollius is EOL and catkin_tools itself is on life support, I wonder if it would be logical to just vendor in the trollius package with the patch above, and then drop the external dependency.

@wjwwood Thoughts on such an approach?

**Comment by wjwwood** [comment]
> @wjwwood Thoughts on such an approach?

That's fine. We can also just bite the bullet and make a new release (and all future releases) of `osrf_pycommon` and `catkin_tools` Python 3.5+ only and completely remove all the trollius stuff.

**Comment by mikepurvis** [comment]
I'm fine with that option too. I mean, `trollius` is supposed to be a drop-in replacement but my recollection from when I last tried was that it wasn't as simple as just changing out the imports (if it was, they would already be in version-check block).

I'm not invested one way or the other, but at this point it's pretty valid to contemplate discontinuing Py2 support. I guess the real drag is that there aren't really any major breaking changes queued up on this side to otherwise justify a 0.5.0 release (and to the extent that there could be, I don't really a lot of time or energy for getting them ready to go).

**Comment by geesara-aet** [comment]
> The one goofy thing I got was as my build was finishing up:
> 
> ```
> [build] Summary: All 28 packages succeeded!
> [build]   Ignored:   2 packages were skipped or are blacklisted.
> [build]   Warnings:  None.
> [build]   Abandoned: None.
> [build]   Failed:    None.
> [build] Runtime: 1 minute and 34.0 seconds total.
> [build] Note: Workspace packages have changed, please re-source setup files to use them.
> Exception ignored in: <function BaseEventLoop.__del__ at 0x7fa8971964d0>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/trollius/base_events.py", line 395, in __del__
>   File "/usr/local/lib/python3.7/dist-packages/trollius/unix_events.py", line 65, in close
>   File "/usr/local/lib/python3.7/dist-packages/trollius/unix_events.py", line 166, in remove_signal_handler
>   File "/usr/lib/python3.7/signal.py", line 47, in signal
> TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
> ```
@mikepurvis . I also got this error after following the steps you have suggested. My build was success but i faced the above error as well. Is it okay to ignore it? or is there a new patch. ?
