### ISSUE TITLE
Short flag for log space not working

### ISSUE THREAD

**Issue by dseifert** [catkin/catkin_tools#567]
### System Info

* Operating System: `Linux computer 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `Python 2.7.15+`
* Version of catkin_tools: `0.4.5`
* ROS Distro: `melodic`

### Build / Run Issue

* [ ] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [ ] I did  not `read this`

### Expected Behavior

Running `catkin config -l my-new-log-dir` should configure my log directory.

### Actual Behavior

`Error: Unknown verb 'my-new-log-dir' provided.`

### Steps to Reproduce the Issue

```bash
catkin config -l my-new-log-dir
```
Also check

```bash
catkin config -l
```
which will set `Additional Make Args:        -l`

### Proposed solution

The reason why this happens is that catkin_tools/jobs/commands/make.py already defines `-l`. Easiest solution would be to change the log space short flag from '-l' to '-L'. If that is acceptable, I can create a pull request)

**Comment by beetleskin** [comment]
I guess catkin is dead - long live colcon?
