### ISSUE TITLE
catkin build issue on raspberry pi 4

### ISSUE THREAD

**Issue by Miliks** [catkin/catkin_tools#586]
Hi, i have a problem on Raspberry Pi4 4 G RAM  trying to follow this tutorial https://ros-planning.github.io/moveit_tutorials/doc/getting_started/getting_started.htm i get to the Build your catkin workspace and at the execution of :
$catkin build 
everything is hungs out on make 14% of moveit_tutorials, not only terminal, but Raspberry is not reacting on anything, so i have to powerdown it not really greacefuly.
Any idea what could be a problem?

* Operating System: `ubuntu 18.04 bionic 64bit (installed image), but the uname -a show Linux ubuntu 4.19.83-22 aarch64`
* Python Version: 2.7.15+
* Version of catkin_tools: catkin_tools 0.4.5
* ROS Distro: `melodic`

**Comment by gavanderhoorn** [comment]
This is not a problem with `catkin_tools`.

The Pi just doesn't have the resources to compile something as extensive as MoveIt with anything more than a single job. It would fail with a regular parallel `make` build as well.

Add `-j1` to your `catkin build` invocation and enable swap. That should give you a chance to build MoveIt successfully.

Please note that there should be binary packages for MoveIt provided for Ubuntu Bionic by the ROS buildfarm. That would remove the need to build things from source.

**Comment by Miliks** [comment]
Thanks a lot for the suggestion, setting the swap to 2 Gb and putting -j1 as a parameter make it work.
