### ISSUE TITLE
No module named terminos under windows

### ISSUE THREAD

**Issue by CesMak** [catkin/catkin_tools#591]
Hey there,

I want to use catkin tools for windows and I installed it with  `pip install -U catkin_tools`
I get the following error when trying to catkin build or catkin clean or whatever:

`ModuleNotFoundError: No module named 'termios'`

On searching I found that termios is not available for windows. 

Any way to resolve error?

**Comment by mikepurvis** [comment]
All we pull from that module is constants: https://github.com/catkin/catkin_tools/search?q=termios

So it's likely that both imports could be wrapped in try blocks and it would still work. However, catkin_tools has never really supported Windows, I don't think. See #554.

**Comment by dirk-thomas** [comment]
@CesMak you might want to try `colcon` instead which fully supports Windows and is actively being maintained.
