### ISSUE TITLE
error about catkin_tools-completion.bash when using zsh

### ISSUE THREAD

**Issue by jsbyysheng** [catkin/catkin_tools#598]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: `Linux b6dbc17b3902 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `Python 2.7.12`
* Version of catkin_tools: `catkin_tools 0.4.5 (C) 2014-2020 Open Source Robotics Foundation`
* ROS Distro: `kinetic`

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [ ] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [x] Works with `catkin_tools-completion.bash`
* [ ] I did  not `read this`

### Expected Behavior

[//]: # (Please describe what you expected or think should happen.)
I want to use [TAB] completion in `zsh`. For example, if I type `catkin bu` and press [TAB], I hope to get `catkin build`. In addtion, `catkin_tools-completion.bash` works well in my laptop's `bash` shell.

### Actual Behavior

[//]: # (Please describe what actually happens.)

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)
When I pressed [TAB], I got `command not found: _init_completion` .

### Steps to Reproduce the Issue

[//]: # (Please give a series of command-line commands which cause the problem.)
[//]: # (Include a checkout URI for the workspace so that we can reproduce the issue.)
[//]: # (If we can't reproduce it on our own machines, we can't fix it!)

```bash
# install zsh && oh-my-zsh
$ wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true
$ chsh -s /usr/bin/zsh
# restart terminal
# install zsh-completions
$ git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
# edit .zshrc and add the following two lines.
# plugins=(… zsh-completions)
# autoload -U compinit && compinit
# restart terminal
➜ source /etc/bash_completion.d/catkin_tools-completion.bash
➜ catkin bu + [TAB]
➜  ~ catkin bu_catkin:3: command not found: _init_completion
 _catkin:3: command not found: _init_completion
 _catkin:3: command not found: _init_completion
```

**Comment by timonegk** [comment]
The bash completion doesn't work with zsh, instead there is a separate completion file for zsh. In the current release it is still installed to the wrong location (`/usr/share/zsh/site-functions/` instead of `/usr/share/zsh/vendor-completions/`). This will be fixed in the next release. You can list the folders where zsh looks for completion files with `echo $fpath`. A workaround until the next release would be to put `export fpath=$fpath:/usr/share/zsh/site-functions` in your zshrc, i.e. manually add the folder where the completions are currently installed.

**Comment by jsbyysheng** [comment]
> The bash completion doesn't work with zsh, instead there is a separate completion file for zsh. In the current release it is still installed to the wrong location (`/usr/share/zsh/site-functions/` instead of `/usr/share/zsh/vendor-completions/`). This will be fixed in the next release. You can list the folders where zsh looks for completion files with `echo $fpath`. A workaround until the next release would be to put `export fpath=$fpath:/usr/share/zsh/site-functions` in your zshrc, i.e. manually add the folder where the completions are currently installed.

Thank you for your reply!
