### ISSUE TITLE
new release into Focal Fossa

### ISSUE THREAD

**Issue by rhaschke** [catkin/catkin_tools#603]
The binary `python3-catkin-tools` (version 0.4.5) released into Focal Fossa doesn't install, because it's dependency `python3-trollius` doesn't exist:
```
$ sudo apt install python3-trollius
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python3-trollius is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-trollius' has no installation candidate
```
The underlying issue was resolved in #574. Could you please trigger a new binary release?

**Comment by rhaschke** [comment]
Ping. This is a show stopper for https://github.com/ros-planning/moveit_ci in Focal.

**Comment by mikepurvis** [comment]
#594 is the ticket tracking a 0.5.0 release of catkin_tools. #597 is the critical issue which needs to be resolved (catkin_tools may no longer assume the version of python it is running as is the same as the version of python being used by the workspace being built).

**Comment by rhaschke** [comment]
Thanks for the information.

**Comment by MatthijsBurgh** [comment]
Please include a new release for Bionic too

**Comment by gavanderhoorn** [comment]
This has also come up on ROS Answers (with the recent Noetic release): [catkin build in Ubuntu 20.04 noetic?](https://answers.ros.org/question/353113).

**Comment by Jaeyoung-Lim** [comment]
I have the same issue. Would make migrating to ROS noetic easier if this issue is resolved

**Comment by wjwwood** [comment]
We're working on a release in this thread (which of course I botched :|), but please direct conversations there.
