### ISSUE TITLE
 <build_type condition="$ROS_VERSION == 2"> ignored (not implemented?)

### ISSUE THREAD

**Issue by facontidavide** [catkin/catkin_tools#606]
### System Info

* Operating System: Linux daf 5.3.0-51-generic # 44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 2.7.17
* Version of catkin_tools: 0.4.5
* ROS Distro: melodic

### Expected/actual beahviour

Some of my packages share the same branch between ROS1 and ROS2.
To deal with both catkin and ament, I use a lot this in package.xml (example):

      depend condition="$ROS_VERSION == 1">roscpp</depend>
      depend condition="$ROS_VERSION == 2">rclcpp</depend> 

this seems to work fine, with exception of:
```XML
    <export>
        <build_type condition="$ROS_VERSION == 2">ament_cmake</build_type>
    </export>
```
**This is not ignored in ROS1, as it should be.**

Please note that catkin_make is **not** affected by this issue.

**Comment by mikepurvis** [comment]
Thanks for pointing this out— yes, the dep resolution side we would get from `catkin_pkg`'s support of the attribute, but the `build_type` check comes from here:

https://github.com/catkin/catkin_tools/blob/af9db1ed8057eca9089a5347afdad8ae471b31ca/catkin_tools/common.py#L613-L626

But that can likely be switched to use the logic from catkin_pkg which does check the condition:

https://github.com/ros-infrastructure/catkin_pkg/blob/4a420002c06cd5d4926e9f55b5746e5d75f8fbd6/src/catkin_pkg/package.py#L148-L165

**Comment by facontidavide** [comment]
that will help me a lot ;)

**Comment by facontidavide** [comment]
Apparently solution was merged. closing the issue (and looking forward to test it)
