### ISSUE TITLE
catkin profile add --copy no longer works

### ISSUE THREAD

**Issue by tspicer01** [catkin/catkin_tools#607]
### System Info

* Operating System: Linux Ubuntu Focal
* Python Version: 3.8.2
* Version of catkin_tools: Head of catkin_tools, SHA: 856bf181d28c1bce47d1aaa3e7236b4f627a0265

### Build / Run Issue

With a set config either custom or using default as the profile if you create a new profile with the --copy option the profile is no longer copied or added.

Command: catkin profile add --copy <base profile> <new profile>
Ex:
catkin profile add --copy default main_build

This was introduced by the changes in https://github.com/catkin/catkin_tools/pull/592  (@janstrohbeck ) reverting back to the SHA before (3fa27d588acee640f18d6ac753dc967b5ba56dfe) then everything works as expected.  

### Expected Behavior
A new profile named main_build will be created with the exact same configuration as the default profile.  I expect to see the appropriate files in .catkin_tools/profiles

### Actual Behavior
catkin reports that there was a new profile created based on the copy profile but there is no profile created.

```
 catkin profile list
[profile] Available profiles:
- default (active)

:~/ws$ catkin profile add --copy default main_build
[profile] Created a new profile named main_build based on profile default
[profile] Available profiles:
- default (active)

.catkin_tools/profiles Dir listing only has the default profile/
~/ws$ ls -lrt .catkin_tools/profiles
total 4
drwxrwxr-x 3 jenkins jenkins 4096 May 21 13:00 default

```

### Steps to Reproduce the Issue

Configure the default profile with any customization:
`catkin config --whitelist mypackage`

Run the profile add with the copy option
`catkin profile add --copy default mycopy`

**Comment by timonegk** [comment]
Thanks for reporting, closed in #658.
