### ISSUE TITLE
Migration: Document command to change space names for catkin_make

### ISSUE THREAD

**Issue by rgov** [catkin/catkin_tools#620]
The migration guide explains to build with `catkin_make` first, and advises using a suffix for the build / devel spaces, but doesn't explain how:

```
catkin_make --cmake-args [CMAKE_ARGS...] --make-args [MAKE_ARGS...]
```

It seems that the invocation should be something like:

```
catkin_make --build build_cm --cmake-args -DCATKIN_DEVEL_PREFIX=devel_cm -DCMAKE_INSTALL_PREFIX=install_cm
```

**Comment by timonegk** [comment]
Closed in #696.
