### ISSUE TITLE
Setup files only generated every other build if building with `catkin config -s .`

### ISSUE THREAD

**Issue by rcywongaa** [catkin/catkin_tools#621]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)
(copied from https://answers.ros.org/question/356713/catkin-only-generates-setup-files-every-other-build/)

### System Info

* Operating System: Ubuntu 18.04
* Python Version: Python 2.7.17
* Version of catkin_tools: 0.6.1
* ROS Distro: melodic

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [ ] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [x] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [ ] I did  not `read this`

### Expected Behavior

Setup files always generated.  `devel` directory contains the following

    cmake.lock  include           local_setup.sh   setup.sh        share
    env.sh      lib               local_setup.zsh  _setup_util.py
    etc         local_setup.bash  setup.bash       setup.zsh

### Actual Behavior

Setup files only generated every other build when `src` directory is missing (i.e. building with `catkin config -s .`).
`devel` directory contains the following

    cmake.lock  etc  include  lib  share

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)

### Steps to Reproduce the Issue

1. Create and cd to an empty directory
1. `catkin config -s .`
1. `catkin build`
1. `ls devel`, observe that various setup files are created
1. `catkin build` again
1. `ls devel`, observe that setup files are gone

Running the following seems to solve the issue

1. `rm -r .catkin_tools`
1. `mkdir src`
1. `catkin build`
1. `ls devel`, observe that various setup files are created
1. `catkin build` again
1. `ls devel`, setup files are still present

**Comment by timonegk** [comment]
The problem was that `catkin_tools_prebuild`, the package providing the disappearing files, was detected as a package in the source space. In #650, a `CATKIN_IGNORE` file was added to the build folder of this package, resolving the issue.
