### ISSUE TITLE
Question: What occurs during the check stage? 

### ISSUE THREAD

**Issue by Levi-Armstrong** [catkin/catkin_tools#628]
I am running into a situation where one of my [packages](https://github.com/ros-industrial-consortium/tesseract_ros/pull/35) spends an hour in the `:check` stage and I am trying to understand why this would be occurring. Is this stage running cmake configure on the package or is there more involved?

**Comment by timonegk** [comment]
During the check stage, `make cmake_check_build_system` is executed. It is a cmake built-in that is executed only when the cmake files are already present (i.e. from the last build). It checks whether `CMakeLists.txt` has changed and if it has, `cmake` is re-executed. I would recommend to debug your problem by navigating to `build/package_name` and executing `catkin build --get-env package_name | catkin env -si /usr/bin/make cmake_check_build_system` there.

**Comment by Levi-Armstrong** [comment]
Thank you for the feed back. I will try this the next time I run into the issue. I ended up restructuring the package which solved the problem, but not sure what actually solved the issue.

**Comment by timonegk** [comment]
Okay, I will close the issue for now, feel free to reopen when the problem persists and you come to the conclusion that it is a problem with `catkin_tools`.
