### ISSUE TITLE
build: include build summary at the end of the build

### ISSUE THREAD

**Issue by wjwwood** [catkin/catkin_tools#63]
This summary should include things like workspaces being extended and compiler being used and stuff like that.

The idea is that having this at the end of the build would better notify users of their build environment.

**Comment by davetcoleman** [comment]
Seems like catkin_tools now has most of this build summary...

```
[build] Summary: All 25 packages succeeded!
[build] Ignored: 4 packages were skipped or are blacklisted.
[build] Warnings: None.
[build] Abandoned: No packages were abandoned.
[build] Failed: No packages failed.
[build] Runtime: 2 minutes and 32.2 seconds total.
```

Should this issue be closed?
