### ISSUE TITLE
Metapackage is ignored by catkin build in ROS Melodic

### ISSUE THREAD

**Issue by StefanFabian** [catkin/catkin_tools#630]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: `bionic 4.15.0-122-generic`
* Python Version: `2.7.17`
* Version of catkin_tools: `0.6.1`
* ROS Distro: `melodic`

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

### Expected Behavior

[//]: # (Please describe what you expected or think should happen.)
Following #418 and #596, metapackages should be built and produce artifacts that can be installed.

### Actual Behavior

[//]: # (Please describe what actually happens.)

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)
The metapackage is ignored even if explicitly built.

### Steps to Reproduce the Issue

[//]: # (Please give a series of command-line commands which cause the problem.)
[//]: # (Include a checkout URI for the workspace so that we can reproduce the issue.)
[//]: # (If we can't reproduce it on our own machines, we can't fix it!)

```bash
catkin build metapackage
```

**Comment by timonegk** [comment]
Version 0.6.1 does not include #596 yet. The change will be included in the next release. In the meantime, consider installing the package with `pip`.
