### ISSUE TITLE
Compile tests without running it 

### ISSUE THREAD

**Issue by lazam** [catkin/catkin_tools#631]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: `Linux Omen 4.15.0-122-generic | Ubuntu 18.10`
* Python Version: `Python 2.7.17`
* Version of catkin_tools: `catkin_tools 0.6.1`
* ROS Distro: `melodic`

### Question

The way we build the test is by using `catkin run_test` which will build and run the test, we categorized our tests so we can run them by groups in parallel. Right now, we need a way to explicitly run specific test we want (integration test with other scripts running outside of gtest). Is there a way to build all the tests as executable without running it? The goal is to have a single build using `catkin build` without running the tests, then use the same build folder to execute `rostest` to target a specific test. 

I already tried to include a `if(CATKIN_ENABLE_TESTING)` in my CMakeLists.txt and use it in my catkin config, but it didn't build the tests.

**Comment by Rayman** [comment]
Something like this?
```
catkin build --catkin-make-args tests
```

**Comment by lazam** [comment]
I tried using `catkin build --catkin-make-args tests`, but it still executed some tests (unit tests, and rostest) when building the whole application. As a workaround, I just created and separated packages to trigger it using `catkin run_test $package_name`.
