### ISSUE TITLE
How to disable NOTICE on stderr about terminal width?

### ISSUE THREAD

**Issue by zwn** [catkin/catkin_tools#632]
I'd like to disable the NOTICE about terminal width that has been added in #415. 

I am calling `catkin build` from a docker build where there seem to be no controlling terminal - at least that is what I get when I run `tty` from the Dockerfile:

<pre>Step 13/15 : RUN tty
not a tty
The command &apos;/bin/sh -c tty&apos; returned a non-zero code: 1
</pre>

According to my understanding, if there is no controlling terminal, it is expected that the width cannot be determined so seeing output on stderr about it does not seem right. I'd be happy with some kind of a hack from cmdline to get rid off it but I think that removal of the message when there is no controlling terminal would be even better.

**Comment by zwn** [comment]
It could be as simple as checking `sys.stdout.isatty()`:

<pre>Step 2/2 : RUN python3 -c &quot;import sys; print(sys.stdout.isatty())&quot;
False
</pre>

So when `stdout` is not connected to a tty, there would be no NOTICE about terminal width.

**Comment by simonschmeisser** [comment]
I've also been annoyed by that, please open a PR!

**Comment by timonegk** [comment]
The problem with using `sys.stdout.isatty()` is that it is also returning False in cases where we want to print the warning, e.g. when building over ssh. I would suggest the following solution, similar to python's `shutil.get_terminal_size()`: When the environment variable `COLUMNS` is set, that value is used and no warning is printed. In your Dockerfile, you could then simply set this environment variable. What do you think?

**Comment by zwn** [comment]
> The problem with using `sys.stdout.isatty()` is that it is also returning False in cases where we want to print the warning, e.g. when building over ssh.

I've just tested `python3 -c "import sys; print(sys.stdout.isatty())"` when running over ssh and it returns `True` for me.

I am not sure how to set COLUMNS variable in such a way that it exists while building the docker image but does not exist when the container is instantiated. My preference would be just to drop the NOTICE (following the example of `shutil.get_terminal_size()` that just returns the default when the width cannot be found).

**Comment by timonegk** [comment]
Okay, I also think that dropping the NOTICE would be a valid solution in combination with `shutil.get_terminal_size()`. When the function does not find the terminal width, the user will probably already know that something is not right and will not be surprised by the default terminal width. I will open a pull request but would like to wait for @mikepurvis or @wjwwood to approve the changes.

**Comment by timonegk** [comment]
By the way, I was talking about invoking `catkin build` over ssh in a script, like `ssh myserver catkin build`. And you could set the environment variable in your Dockerfile like this:
`RUN COLUMNS=80 catkin build`

**Comment by timonegk** [comment]
Closed in #653.
