### ISSUE TITLE
`yield from lock` support removed in python 3.9

### ISSUE THREAD

**Issue by nim65s** [catkin/catkin_tools#636]
### System Info

* Operating System: Arch Linux
* Python Version: 3.9
* Version of catkin_tools: git
* ROS Distro: noetic

### Build / Run Issue

* [x] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [ ] I did  not `read this`

### Expected Behavior

package build

### Actual Behavior

```python
[build] Found '1' packages in 0.0 seconds.                                                                                                                    
[build] An internal error occurred!                                                                                                                           
Traceback (most recent call last):
  File "…/catkin_tools/verbs/catkin_build/build.py", line 550, in build_isolated_workspace
    all_succeeded = run_until_complete(execute_jobs(
  File "…/catkin_tools/execution/executor.py", line 374, in run_until_complete
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "…/catkin_tools/execution/executor.py", line 282, in execute_jobs
    job_id, succeeded = yield from done_job_f
  File "…/catkin_tools/execution/executor.py", line 73, in async_job
    yield from lock
TypeError: 'Lock' object is not iterable
```

### Steps to Reproduce the Issue

```bash
pip install --user -U "git+https://github.com/catkin/catkin_tools.git#egg=catkin_tools"
catkin build
```

ref. https://github.com/python/cpython/pull/17533

**Comment by gavanderhoorn** [comment]
I believe this was reported in https://github.com/catkin/catkin_tools/issues/594#issuecomment-738176643. With #635 as a related PR.

**Comment by nim65s** [comment]
Thanks!
I did subascribe to that one, I don't know how I missed it.

**Comment by gavanderhoorn** [comment]
Having a separate issue might actually not be so bad: it would increase visibility and prevent others from posting duplicates.

**Comment by timonegk** [comment]
Now that the python 3 version is released, I am closing this issue.
