### ISSUE TITLE
Using `catkin config` to show current configuration unsets `--make-args`

### ISSUE THREAD

**Issue by DavidMerzJr** [catkin/catkin_tools#654]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: `Linux 5.8.0-43-generic #49~20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux` (Ubuntu 20.04)
* Python Version: Python 3.8.5
* Version of catkin_tools: catkin_tools 0.5.0
* ROS Distro: noetic

### Build / Run Issue

I looked through all open issues and the troubleshooting guide, but could not find mention of this issue.

[//]: # (If you have an issue building and running code, please verify the following:)

* [ ] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [ ] I did  not `read this`
* [x] This problem lies outside of the actual building of code

### Expected Behavior

I use `catkin config` to display the current catkin configuration.  Without any further arguments, I expect this to not change the current configuration in any way.

I set make arguments, such as the number of parallel make jobs, using `catkin config --make-args -j6`.  I expected that these arguments would persist, just like `catkin config --cmake-args`.

### Actual Behavior

If I set `make` arguments, e.g. `catkin config --make-args -j6`, it correctly sets them, and they apply to multiple successive builds.  However, if I run `catkin config` to show the current configuration, this clears the set `--make-args`.

### Steps to Reproduce the Issue

(I apologize for not giving a checkout URI, but this problem seems to be workspace-agnostic, and exists in arbitrary or empty workspaces.  My catkin _tools version is listed above.  I do not have access to another computer with different catkin_tools version to test whether it exists in other versions.)

From home directory, make a new workspace:
```bash
mkdir test_ws
cd test_ws
mkdir src
catkin init
```
Set a make argument:
```bash
catkin config --make-args -j6
```
The output from the above command shows that the make argument has correctly been set.  However, it will be unset when we try to view the config using `catkin config`:
```bash
catkin config
```

**Comment by timonegk** [comment]
Thanks for reporting the issue, I created a fix in #655.

**Comment by DavidMerzJr** [comment]
Awesome, thanks for the quick turnaround!  How long do bug fixes usually take to hit the Ubuntu apt repositories?  I am wondering whether it is worth doing a from-source install in the meantime.

**Comment by timonegk** [comment]
The current release has unfortunately been stuck for a rather long time (see #594). Therefore I would definitely recommend the source installation:
`pip3 install git+https://github.com/catkin/catkin_tools.git`
Since the pull request is merged to master, I am closing the issue.
