### ISSUE TITLE
Check for symlinks in the directory strings

### ISSUE THREAD

**Issue by JDuchniewicz** [catkin/catkin_tools#667]
I found out that catkin has significant troubles when the path is specified once as an absolute directory -> pointing to the mounted drive and then to the catkin dir, and then it is `cd`d via a symlink to the mounted drive. In this case catkin relies on hardcoded strings of the absolute directory and refuses to build properly.

I am unfamiliar with how catkin treats dir strings but it is probably possible to do a check on the cwd and resolve all symlinks to  store the strings always as absolute paths or resolve them each time on both sides (less efficient)

**Comment by timonegk** [comment]
Hi, thanks for reporting the issue. However, I don't quite understand your problem. Please provide the following information:
* What is your directory structure? Which folders are symlinked where? Where is your workspace? For example like this:
  ```
  -- catkin_ws (workspace)
      |-- src
      |    |-- package-1  (this is a symlink to /mnt/package-1)
      ...
  ```
* From where are you invoking catkin when the problem occurs? What is the exact error message?
* Are you on Windows, Linux, or Mac?
* How did you install catkin_tools?

**Comment by JDuchniewicz** [comment]
Hi sorry for the late reply. So the disk I have my `catkin_ws` is mounted and some times I access the folder by the absolute (a tmux session which I respawn on startup)location and sometimes by relative (manual `cd`).

So for example I create the `catkin_ws` and the shell prompt says I am in the absolute location of the folder. Then I `cd` into the relative link -> the shell reflects that and I try to build the folder. Such error  message transpires: 
```
Error: Attempting to build a catkin workspace using build space: "/home/jduchniewicz/Projects/UTU/Period4/RAS/OpenAI/catkin_openai/build" but that build space's most recent configuration differs from the commanded one in ways which will cause problems. Fix the following options or use `catkin clean -b` to remove the build space:
 - devel_space: /mnt/games/Projects/UTU/Period4/RAS/OpenAI/catkin_openai/devel (stored) is not /home/jduchniewicz/Projects/UTU/Period4/RAS/OpenAI/catkin_openai/devel (commanded)
 - install_space: /mnt/games/Projects/UTU/Period4/RAS/OpenAI/catkin_openai/install (stored) is not /home/jduchniewicz/Projects/UTU/Period4/RAS/OpenAI/catkin_openai/install (commanded)
 - source_space: /mnt/games/Projects/UTU/Period4/RAS/OpenAI/catkin_openai/src (stored) is not /home/jduchniewicz/Projects/UTU/Period4/RAS/OpenAI/catkin_openai/src (commanded)
 - workspace: /mnt/games/Projects/UTU/Period4/RAS/OpenAI/catkin_openai (stored) is not /home/jduchniewicz/Projects/UTU/Period4/RAS/OpenAI/catkin_openai (commanded)
```

If I keep doing this using the absolute location or relative and I am consistent in it, there is no problem.
System: Arch Linux x64
Catkin_tools installed via `pacman`
Shell: `fish`

**Comment by timonegk** [comment]
Thank you, a patch is on the way!
