### ISSUE TITLE
catkin creates package.xml with wrong license placeholder

### ISSUE THREAD

**Issue by christian-rauch** [catkin/catkin_tools#670]
### System Info

* Operating System: Linux gungnir 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 3.8.5
* Version of catkin_tools: catkin_tools 0.5.0
* ROS Distro: noetic

### Build / Run Issue

Minor issue: `catkin create pkg` will create a `package.xml` with:
```
  <license>D</license>
  <license>O</license>
  <license>O</license>
  <license>T</license>
```

### Expected Behavior

In older versions, e.g. melodic, this used to be `<license>TODO</license>`.

### Actual Behavior

Multiple license tags.

### Steps to Reproduce the Issue

1. install ROS noetic
2. `sudo apt install python3-catkin-tools`
3. `catkin create pkg my_node`

**Comment by timonegk** [comment]
Thanks for the report, a patch is on the way!
