### ISSUE TITLE
`ValueError: Invalid placeholder in string: line 1, col 1` when building a package with warnings

### ISSUE THREAD

**Issue by sharminramli** [catkin/catkin_tools#677]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: `5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `3.8.5`
* Version of catkin_tools: `0.5.0, using Python 3.8.5`
* ROS Distro: `noetic`

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [x] Works with `catkin_make`
* [x] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [ ] I did  not `read this`

### Expected Behavior

[//]: # (Please describe what you expected or think should happen.)
When building a package with warnings, catkin should print the warning and continue the build.

### Actual Behavior

[//]: # (Please describe what actually happens.)

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)

The build succeeds, but an exception is thrown and the warning is not printed:
```
Exception in callback _UnixReadPipeTransport._read_ready()cmake - 1.0]                                                                                                                                              
handle: <Handle _UnixReadPipeTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 500, in _read_ready
    self._protocol.data_received(data)
  File "/usr/lib/python3/dist-packages/osrf_pycommon/process_utils/async_execute_process_asyncio/impl.py", line 111, in data_received
    protocol.on_stderr_received(data)
  File "/usr/lib/python3/dist-packages/catkin_tools/jobs/commands/cmake.py", line 89, in on_stderr_received
    colored = self.color_lines(data_head)
  File "/usr/lib/python3/dist-packages/catkin_tools/jobs/commands/cmake.py", line 115, in color_lines
    colored_lines = [self.colorize_cmake(line) for line in lines]
  File "/usr/lib/python3/dist-packages/catkin_tools/jobs/commands/cmake.py", line 115, in <listcomp>
    colored_lines = [self.colorize_cmake(line) for line in lines]
  File "/usr/lib/python3/dist-packages/catkin_tools/jobs/commands/cmake.py", line 146, in colorize_cmake
    cline = fmt(r, reset=False)
  File "/usr/lib/python3/dist-packages/catkin_tools/terminal_color.py", line 135, in fmt
    return t.substitute(_ansi) + (ansi('reset') if reset else '')
  File "/usr/lib/python3.8/string.py", line 126, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/lib/python3.8/string.py", line 123, in convert
    self._invalid(mo)
  File "/usr/lib/python3.8/string.py", line 106, in _invalid
    raise ValueError('Invalid placeholder in string: line %d, col %d' %
ValueError: Invalid placeholder in string: line 1, col 1
```

### Steps to Reproduce the Issue

[//]: # (Please give a series of command-line commands which cause the problem.)
[//]: # (Include a checkout URI for the workspace so that we can reproduce the issue.)
[//]: # (If we can't reproduce it on our own machines, we can't fix it!)

1. Create a test package (e.g. `catkin_create_pkg test`)
2. Modify the `package.xml` to use `<depend>catkin</depend>` instead of `<build_depend>catkin</build_depend>` (this is to force a warning message)
3. `catkin build test`

### Workaround
The exception happens when `msg` in `terminal_color.py:fmt()` is `@(yf){}@{reset}`. I assume that the `(yf)` causes template substitution to mistake the first `@` as a dangling placeholder, so I modified the filter `@(yf){}@|` in `jobs/commands/cmake.py` to use `@{yf}{}@|` instead, and was able to get the warning to appear without any exceptions:

![image](https://user-images.githubusercontent.com/62992256/115224360-5706b100-a13f-11eb-8d6f-8e4dbfddd08d.png)

However, I see that this filter has not been changed since 2019, and no one else seems to have opened a similar issue on this repo, so could it be that there is something wrong with my setup? I've also just upgraded from ROS Melodic/18.04 to ROS Noetic/Ubuntu 20.04 a few days ago.

**Comment by timonegk** [comment]
Thank you for reporting the issue. I don't know how this was never noticed, but it seems to be a simple typo. (It has apparently been in the code [since 2016](https://github.com/catkin/catkin_tools/commit/cc842c8775ec8a7a0a13f3bc8a280ea0fa373c14)!)
