### ISSUE TITLE
specifying custom path in "catkin list"

### ISSUE THREAD

**Issue by ptiza-v-nebe** [catkin/catkin_tools#679]
### System Info

* Operating System: `uname -a`
Linux hero 5.4.0-71-generic #79~18.04.1-Ubuntu SMP Thu Mar 25 05:45:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* Python Version: `python --version`
Python 2.7.17

* Version of catkin_tools: `catkin --version` OR *Git revision*
catkin_tools 0.6.1 (C) 2014-2021 Open Source Robotics Foundation
catkin_tools is released under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
Using Python 2.7.17 (default, Feb 27 2021, 15:10:58) [GCC 7.5.0]

* ROS Distro: `echo $ROS_DISTRO`
melodic

### Expected Behavior
As in the [documentation](https://catkin-tools.readthedocs.io/en/latest/cheat_sheet.html) stated by issuing following command, a all nodes inside of a specific directory will be build. (in this case a metapackage)

```bash
catkin build $(catkin list -u ./src/my_metapackage/)
```

### Actual Behavior
The command:
```bash
catkin list -u ./src/my_metapackage
```
does not recognize additional path argument

```bash
catkin: error: unrecognized arguments: ./src/my_metapackage/
```

### Suggestion
Making it simpler to build a metapackage by doing just:
```bash
catkin build my_metapackage
```

Thank you!

**Comment by timonegk** [comment]
The problem is that you have to use `-d` before the directory.
This issue is a duplicate of #571, the documentation is already updated upstream but not deployed, sorry.

**Comment by ptiza-v-nebe** [comment]
thanks!

The suggestion with metapackage was actually unneccesary as this is already normal functionality. I was just missing  few <exec_depend>packagename</exec_depend> in the metapackage package.xml.
