### ISSUE TITLE
build: install and develspace interplay

### ISSUE THREAD

**Issue by NikolausDemmel** [catkin/catkin_tools#69]
*I just noticed these issues following a discussion in https://github.com/catkin/catkin_tools/issues/64#issuecomment-45735131:*

Calling `catkin build --install` after `catkin build` is broken for pure cmake packages. After the first call they will have been installed into the devel space and the second call will not install them to the source space.

*Edit: I moved the second issue to #70*

**Comment by jbohren** [comment]
Since merging #249, installing is now fixed for pure CMake packages.
