### ISSUE TITLE
unrecognized argument --limit-status-rate 

### ISSUE THREAD

**Issue by YannickdeHoop** [catkin/catkin_tools#698]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: `5.11.0-40-generic #44~20.04.2-Ubuntu`
* Python Version: `Python 3.8.10`
* Version of catkin_tools: `0.8.0`
* ROS Distro:  `noetic`

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (https://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (https://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [ ] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [ ] I did  not `read this`

### Expected Behavior

[//]: # (Please describe what you expected or think should happen.)

### Actual Behavior

[//]: # (Please describe what actually happens.)

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)

`catkin: error: unrecognized arguments: --limit-status-rate 0.5`

### Steps to Reproduce the Issue

[//]: # (Please give a series of command-line commands which cause the problem.)
[//]: # (Include a checkout URI for the workspace so that we can reproduce the issue.)
[//]: # (If we can't reproduce it on our own machines, we can't fix it!)

```bash
catkin run_tests <package> --no-dep -j1 --limit-status-rate 0.5
```

**Comment by timonegk** [comment]
The reason for the issue is that in version 0.8.0, a new verb, `catkin test` was added that makes testing packages easier (for example the output is more helpful and you don't have to run `catkin_test_results` manually). `run_tests` is now an alias for this new verb, and I forgot to add the `--limit-status-rate` option. I will add it and will release a new version with the fix later today. Thanks for reporting!
