### ISSUE TITLE
Installed libraries reference devel space

### ISSUE THREAD

**Issue by NikolausDemmel** [catkin/catkin_tools#70]
*I split of the second half of #69, since it was really two separate issues.*

When calling `catkin build --install` some of the installed libraries still reference linked libraries in the develspace. However, the install space is supposed to be self contained, right? I don't know if the same issue arises with cm/cmi or on platforms other than OS X (where shared library linking is a bit different than on Linux).

Notice the reference to the devel space for `librospack`:

```
$ otool -L installtest/lib/libroslib.dylib
installtest/lib/libroslib.dylib:
	libroslib.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/demmeln/work/hydro_ws/develtest/lib/librospack.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libtinyxml.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
	/usr/local/lib/libboost_filesystem-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_program_options-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)```

**Comment by jbohren** [comment]
On the current master, you can no longer perform `catkin build --install`. You must run `catkin config --install; catkin build`. If you try to do that without clearing the build space, it produces a warning. I think this can be closed now.
