### ISSUE TITLE
--src option and stability of the CLI

### ISSUE THREAD

**Issue by StefanFabian** [catkin/catkin_tools#701]
### System Info

* Operating System: Ubuntu
* Python Version: 3.8.10
* Version of catkin_tools: 0.8.0
* ROS Distro: noetic

### Build / Run Issue

In #691 the `--src` option was replaced by `--source-space`. This change broke our build server as it used `catkin locate ... --src PACKAGE` to locate the source directory.
I would suggest keeping the old name as an alias to stay backward compatible.
That is of course unless the CLI is not intended to be used for scripting, in that case, an appropriate notice should probably be added to the docs.

**Comment by timonegk** [comment]
Sorry. The API is supposed to be stable. I will fix it right away.

**Comment by timonegk** [comment]
The issue is now fixed and the updated version has been released as 0.8.2.
