### ISSUE TITLE
Somehow list known external verbs

### ISSUE THREAD

**Issue by NikolausDemmel** [catkin/catkin_tools#71]
Low priority, nice to have enhancement about commands plugins:

For external verb plugins, like the recently added `caktin lint`, catkin tools should ideally have some soft reference to it, allowing to give the user some information about how to install it.

E.g. when `catkin_lint` is not installed, calling `catkin lint` should maybe suggest `pip install catkin_lint` or give a link to the catkin_lint homepage or something instead of just saying the command is not found.

This would also provide some sort of documentation which external commands have already been released externally to reduce name clashes. There might be a `--list-known-verbs` or similar option to display this information. Of course, if an installed package other than `catkin_lint` defines the `lint` verb entry point, catkin tools should happily accept that as well.

**Comment by jbohren** [comment]
I think instead of rolling it into the command, it should just be listed in the online documentation. That would provide links to documentation and a few notes on what the contributions do.

**Comment by jbohren** [comment]
This is included in #250.
