### ISSUE TITLE
when exporting compile_commands.json, -std=c++11 is added automatically to googlemock and googletest

### ISSUE THREAD

**Issue by SubaruArai** [catkin/catkin_tools#713]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: `Linux ros-env 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `Python 3.8.10` (no `python`, just `python3`)
* Version of catkin_tools:
```
catkin_tools 0.8.2 (C) 2014-2022 Open Source Robotics Foundation
catkin_tools is released under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
---
Using Python 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```
* ROS Distro: `noetic`

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (https://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (https://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [ ] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`

### Expected Behavior

[//]: # (Please describe what you expected or think should happen.)
By setting `add_compile_options(-std=c++17)` in `CMakeLists.txt`, every compile command should have `-std=c++17` and no other `-std=` flags.

### Actual Behavior

[//]: # (Please describe what actually happens.)
Auto generated `googletest` and `gooclemock` overwrites the setting by adding another `-std=c++11`.
Compile commands from `add_executable` are not affected.

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)
[gist](https://gist.github.com/SubaruArai/e19b1f25a2e4cd6fceaf71481fa77e21) contains `compile_commands.json` and output of `catkin build -p1 -v`

### Steps to Reproduce the Issue

[//]: # (Please give a series of command-line commands which cause the problem.)
[//]: # (Include a checkout URI for the workspace so that we can reproduce the issue.)
[//]: # (If we can't reproduce it on our own machines, we can't fix it!)

1. Create  a new package
```bash
catkin create pkg error_repro --catkin-deps roscpp
```
2. Edit `CMakeLists.txt` and uncomment `add_compile_options(-std=c++11)`, change the `11` to `17`
3. Create `error_repro_node.cpp` in src
```c++
int main(int argc, char const *argv[])
{
    return 0;
}
```
4. Add `add_executable(${PROJECT_NAME}_node src/error_repro_node.cpp)` in `CMakeLists.txt`
5. Run build with export flag
```bash
catkin build -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
6. check the output in `build/error_repro/compile_commands.json`

**Comment by timonegk** [comment]
Could you try to build the package manually?
1. Source your workspace
2. In the `error_repro` package, create a `build` folder and navigate into it
3. Run `cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=1`
4. Run `make`

Does the problem still exist? If yes, this is a problem with [`catkin`](https://github.com/ros/catkin) and you should try to open it there.

**Comment by SubaruArai** [comment]
@timonegk thank you for the response!
Yes, I can reproduce it.
I'll close this ticket and open another one in [catkin](https://github.com/ros/catkin), thank you!
