### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by davetcoleman** [catkin/catkin_tools#72]
What is the equivalent to 
```
catkin_make run_tests_control_toolbox
```
?

I tried
```
catkin build run_tests_ROS_PACKAGE_NAME
```
But I don't see any documentation and @vrabaud mentioned it probably doesn't exist yet. What is the work around? Thanks!

**Comment by davetcoleman** [comment]
Done https://github.com/catkin/catkin_tools/issues/72#issuecomment-64701060

**Comment by bluenote10** [comment]
Is there a reason why the [official documentation](http://docs.ros.org/api/catkin/html/howto/format2/run_tests.html?highlight=run%20test) still recommends to use `catkin_make run_tests` while it should be `catkin build [...] --catkin-make-args run_tests` according to the change mentioned above?

**Comment by wjwwood** [comment]
@bluenote10 `catkin_tools` was never officially recommended, and so the documentation has never been updated. `catkin_make` and/or `catkin_make_isolated` is the only "supported" use case.

See: https://github.com/catkin/catkin_tools/issues/90
