### ISSUE TITLE
catkin clean package autocompletion not working/implemented

### ISSUE THREAD

**Issue by ipa-jsk** [catkin/catkin_tools#742]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)
I'm not sure if it is an issue or an feature request, or if there already was a discussion about it.

### System Info

* Operating System: `uname -a`: `Linux WN1209 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Python Version: `python --version`: `Python 3.8.10`
* Version of catkin_tools: `catkin --version` OR *Git revision*: `catkin_tools 0.9.0 (C) 2014-2022 Open Source Robotics Foundation`
* ROS Distro: `echo $ROS_DISTRO`: `noetic`

### Issue

For `catkin clean`, autocompletion for package names does not work.

### Expected Behavior

When I type `catkin clean my_awesome_pa` and there is a built and sourced ROS package named `my_awesome_package`, pressing TAB autocompletes to `catkin clean my_awesome_package`. The same way like it works for `catkin build`.

### Actual Behavior

No autocompletion on TAB (nothing happens).

### Steps to Reproduce the Issue

```bash
cd catkin_ws
catkin clean <first letters of an existing package>
```
press TAB.

Thanks!

**Comment by timonegk** [comment]
Are you using bash or zsh?

**Comment by ipa-jsk** [comment]
bash
