### ISSUE TITLE
How to suppress warning messages when invoking catkin build "package name"

### ISSUE THREAD

**Issue by Mechazo11** [catkin/catkin_tools#743]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: Ubuntu 20.04
* Python Version: 3.8.10
* Version of catkin_tools: 0.9.0
* ROS Distro: Neotic

[//]: # (If you have an issue building and running code, please verify the following:)

* [ ] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [x ] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [] I did  not `read this`

### Expected Behavior
Suppress all warning messages

[//]: # (Please describe what you expected or think should happen.)
Would like to know what argument I can add with the `catkin build` command to suppress **ALL** warning messages so that only error messages are printed out

### Actual Behavior
A large number of unnecessary warning messages are generated. As a result, it is getting very difficult to find error messages and troubleshoot the code.

[//]: # (Please describe what actually happens.)
When invoking `catkin build "orb_slam_3"`, a large number of depreciation warning is generated by the newest version of Eigen linear algebra library. I am not looking to downgrade to an older Eigen version since the warning messages are depreciation warnings and so far has not comprised functionality of the SLAM pipeline. However, with the large number of warning messages that gets printed out, it requires me to manually scroll through all of it to find the errors. This is very annoying and time consuming.

Is there any way I can suppress all the warning messages when using `catkin build` command?

**Comment by timonegk** [comment]
Catkin just prints everything cmake/make print to stderr. You can suppress warnings in cmake, either by adding `add_compile_options(-w)` to your CMakeLists.txt or by running catkin build with `-DCMAKE_CXX_FLAGS=-w`. `-w` is the compiler flag that suppresses warnings.

**Comment by Mechazo11** [comment]
@timonegk Thanks. I will try it out and let you know if the problem is solved.

**Comment by Mechazo11** [comment]
@timonegk It works thank you for the information.
