### ISSUE TITLE
Read the Docs latest documentation is out of date

### ISSUE THREAD

**Issue by hfiggs** [catkin/catkin_tools#744]
The documentation marked as "latest" on Read the Docs is actually [a build from Dec. 21](https://readthedocs.org/projects/catkin-tools/builds/15491791/). It was generated from the following commit: [2c3494ed7fb56f19be2b12889b8963c08608b503](https://github.com/catkin/catkin_tools/commit/2c3494ed7fb56f19be2b12889b8963c08608b503)

Perhaps Read the Docs has changed their build system? I am not familiar with how Read the Docs works

This discrepancy makes it difficult to learn how to use catkin_tools, because if you just install `python3-catkin-tools`, the docs don't match

@wjwwood @NikolausDemmel @timonegk are listed as maintainers on the docs site

**Comment by timonegk** [comment]
Hi, sorry for the issue, I just updated the docs.

**Comment by hfiggs** [comment]
Thank you!
