### ISSUE TITLE
Pypi releases not up-to-date

### ISSUE THREAD

**Issue by MatthijsBurgh** [catkin/catkin_tools#749]
The last version released on pypi is `0.9.0`. While the last release on GH is `0.9.3`. Could you please keep this in sync?

**Comment by wjwwood** [comment]
@timonegk is this related to https://github.com/catkin/catkin_tools/pull/740#issuecomment-1378032310?

0.9.2 is on our debian repository, did you ping me fore 0.9.3? Maybe I missed it. Either way the pypi version should be up-to-date right?

**Comment by timonegk** [comment]
@wjwwood I pinged you [here](https://github.com/catkin/catkin_tools/pull/728#issuecomment-1442123178). But it seems like I forgot the pypi upload. I just uploaded 0.9.3 there, could you do the debian upload?

**Comment by wjwwood** [comment]
@timonegk just a bit of an update, I'm having trouble getting the release to work. I'm not sure if it's my setup or something else. I'm trying to find time to debug it with one of my colleagues. I'll let you know when it's done.

**Comment by timonegk** [comment]
@wjwwood I have now tagged 0.9.4 in the hope of getting rid of the readthedocs deprecation warnings.

**Comment by wjwwood** [comment]
Ok, I'll try the release process again (may have been something with the previous version), but I still need to find time to debug the process if not.

**Comment by wjwwood** [comment]
Ok, I know this is a long standing issue, but I _finally_ found time and the issue: https://github.com/ros-infrastructure/ros_release_python/issues/40

So now 0.9.4 is in the apt repositories. I tested it on ubuntu 20.04.

However, we should consider updating this file:

https://github.com/catkin/catkin_tools/blob/86632fef204606716b7089d7a5e18a63e9c42d59/stdeb.cfg#L4

So it's on more (newer) ubuntu versions. `rosdep` is a good comparison:

https://github.com/ros-infrastructure/rosdep/blob/78f3744f9054ed188bc23b830854080dc9face70/stdeb.cfg#L18
