### ISSUE TITLE
No setup.bash

### ISSUE THREAD

**Issue by davetcoleman** [catkin/catkin_tools#87]
I have a workspace that has 1 catkin package and 1 non-catkin package (OMPL). After building the workspace (catkin build) it only has as setup.sh file, not a setup.bash file. Why is this? Is something wrong? All my other workspaces have a setup.bash file which is what Im used to sourcing on Ubuntu 12.04.

**Comment by scpeters** [comment]
I've noticed the same problem, since I use `catkin_tools` for plain cmake packages quite often. I don't know why it happens either, but a solution is to clone https://github.com/ros/catkin.git into the workspace `src` folder. This is what I will recommend to users building gazebo using catkin, unless this issue is someday resolved.

**Comment by davetcoleman** [comment]
I believe you could just use an empty catkin package, e.g. ``catkin_create_pkg dummy roscpp``

**Comment by scpeters** [comment]
Note that cloning catkin into the workspace `src` folder doesn't require ROS to be installed or sourced.

**Comment by davetcoleman** [comment]
ah good point

**Comment by jbohren** [comment]
@scpeters @davetcoleman As an aside, my ["linked-devel" prototype](https://github.com/catkin/catkin_tools/pull/196) that supports cleaning individual packages will automatically generate setup files in the devel / install space even if you don't have a catkin package in your workspace.

**Comment by scpeters** [comment]
@jbohren thanks for the heads-up; that sounds like a nice set of new features that would resolve this issue. I'll keep my eye on it.

**Comment by davetcoleman** [comment]
I'm setting up a new workspace and just re-ran into this problem, I'm going to re-open atleast until https://github.com/catkin/catkin_tools/pull/196 is merged in

**Comment by scpeters** [comment]
Don't forget the workaround of cloning catkin into the workspace src folder.
